### ISSUE TITLE
cn.bing.com

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10100]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://cn.bing.com/search?q=windows+11&cvid=bfdb2d23a32147f88dad8e960f0a43a8`

### Describe the issue

You may need a VPN to China and select "Domestic Edition (`国内版`)", and the ad does not recur consistently
Since the ad doesn't appear when I use AdGuard, I don't think they'll deal with it

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66902050/135488909-54997bfb-ac19-4a65-955d-8ff177281c53.png)

### uBlock Origin version

v1.38.0

### Browser name and version

Microsoft Edge 94.0.992.31 (64-bit)

### Settings

Filter rules are default, but there are additional regional filter lists in China `CHN: AdGuard Chinese (中文)`

**Comment by uBlock-user** [comment]
Disable Edge's built-in blocker. Filters present in uBO's main list block the ad as expected.

**Comment by shenzhiming88** [comment]
> Disable Edge's built-in blocker. Filters present in uBO's main list block the ad as expected.

Well, I don't think there is built-in blocker in Edge

**Comment by uBlock-user** [comment]
@shenzhiming88 `https://techcommunity.microsoft.com/t5/discussions/is-there-any-way-to-turn-off-the-built-in-ad-blocker-for-some/m-p/2400082`

**Comment by felix-22** [comment]
> uBlock-user : https://github.com/uBlockOrigin/uAssets/commit/0f50431a912cd93a099af7a8e7f94277280f4a0e?#r57313937

Stop trolling and turning the facts and putting the blame on me, it's clear it has been spirillen who has been harassing me on uAssets tracker for a long time, everyone saw that, and you come in and saying nonsense that I am the one who starts, what a bullshit.

Also when your friend mapx- wrote a comment against baseless thumbs down emoji, it did not bother you: https://github.com/uBlockOrigin/uAssets/issues/7332#issuecomment-626233811 nowhere do I see you writing him the same bullshit you have written me, now it does bother you suddenly when I have done the same?

You haven't grown up to moderate, what kind of modertion is this? Instead of defending the one being harassed you yourself harass the harassed one, now I'm being harassed by two? Spirillen + you. 

@gorhill could you take an action and delete uBlock-user's slanderous comment? It was spirillen who should "Take his personal squabbles somewhere else. This is not the place." and not me, uBlock-user reply to me is a slander and lie.

**Comment by felix-22** [comment]
Why don't you hide your own comments full of rubbish? You are only hiding my comments that are truthful?

I will consider contacting github administration to take care of your abusive unfair moderation and harasment.

**Comment by okiehsch** [comment]
> I will consider contacting github administration to take care of your abusive unfair moderation and harasment, you should be removed from the community, because you are very disrespectful.

You do that, in the meantime stay on topic in this repo, I will unhide your comments,  so we all know your point of view.
This issue will remain locked. If you continue making off topic comments I will ban you.
