### ISSUE TITLE
Anti-adblock in rustorka.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10141]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://rustorka.com/forum/index.php`

### Describe the issue

This might be quite annoyed since the website needs signing in to get anti-adblock triggered. Sorry about the annoyance.

After signing in for a few seconds (around 5 seconds), the anti-adblock screen appears.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/136020376-4fec42ed-a19a-4d84-97f4-2a72fa37828b.png)

### uBlock Origin version

1.38.2

### Browser name and version

Firefox 92.0.1

### Settings

No change

### Notes

This filter helps

`rustorka.com##^script:has-text(checkCookie)`

For chromium, since we can't apply HTML filtering, I think this filter helps

`@@||rustorka.com/forum/misc/js/popunder.js$script,1p`

**Comment by uBlock-user** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
For many years, this site has had an auto-redirect initiated by the server itself. It could only be avoided by setting special cookies. The issue was discussed here: https://github.com/uBlockOrigin/uBlock-issues/issues/1518

At the end of May this year, the admin declared war on the blockers and arranged a vote: http://rustorka.com/forum/viewtopic.php?t=267906

As you can see from its results, only 28% of users refused to disable the ad blocker, 41% voted to ban it, and 30% indicated that they didn't care.

At the moment, the admin in real time checks the functionality of denying access to those users who use blockers, and the rules added to regular filters do not work for more than several hours. Therefore, the problem is solved in the optional filter Counters: https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

**Comment by dimisa-RUAdList** [comment]
@stephenhawk8054 
@mapx- 
Please add in uBlock filters – Ads:
`game4you.top,innal.top,naylo.top,rustorka.com,rustorka.net,rustorka.top,rustorkacom.lib##+js(trusted-set-cookie-reload, godbayadblock, godbayadblock)`
