### ISSUE TITLE
[Filter] Tracking and fingerprinting script found on Baidu services.

### ISSUE THREAD

**Issue by subsys-R9boq8** [uBlockOrigin/uAssets#10160]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`baidu.com`

### Describe the issue

Tracking and fingerprinting script found on Baidu services.

A JavaScript facilitating tracking and fingerprinting functions is found on Baidu. It collects device platform information, browser name and version, number of CPU cores, canvas fingerprints, device screen length/width, browser plugin installed. It also monitors device motion information based on DeviceMotionEvent, and detects common headless browsers like phantom, nightmare, Selenium, puppeteer, too.
It's clear that this script invade user privacy heavily, thus shall be added to the uBlock Filters - Privacy Filter.

Script address:
`https://dlswbr.baidu.com/heicha/mw/abclite-2020-s.js`
Archive:
`https://archive.ph/cajdq`
Formatted:
https://gist.github.com/yingziwu/6e16c14565eec77e6768411677ed1ff3

Based on research of mastodon user @bgme@bgme.me
`https://bgme.me/@bgme/106874443906503464`

### uBlock Origin version

1.37.2

### Browser name and version

Any

### Settings

Not relevant

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by Heporis** [comment]
||dlswbr.baidu.com^ 
This filter breaks site: map.baidu.com. 
You can't click any address or search for any navigation route. It can almost be said that it has lost its most basic functions.
Maybe we can add a rule: @@||dlswbr.baidu.com^$domain=map.baidu.com in exchange for using its basic functions, and other websites will continue to be blocked. 
Related scripts: 
`https://dlswbr.baidu.com/heicha/mw/abclite-2059-s.js`

**Comment by stephenhawk8054** [comment]
Can you record video how to reproduce the issue?

**Comment by Heporis** [comment]
There are many scripts distinguished by number under `dlswbr.baidu.com` for different websites , such as: 
abclite-2036-s.js on `baijiahao.baidu.com`
abclite-2030-s.js on `wenku.baidu.com`
abclite-2059-s.js on `map.baidu.com`
I don't know if the script(abclite-2059-s.js) is also a tracking script, since it is encrypted. Other websites seem to work normally with ||dlswbr.baidu.com^, but `map.baidu.com` will not work properly without the script. 

block abclite-2059-s.js:

![Image](https://github.com/user-attachments/assets/c42b715e-7cbe-4d15-87ba-b2729498a932)

then release the script and open a new private window: 

![Image](https://github.com/user-attachments/assets/34e7b1cd-ac1a-4ede-8cbe-bd5f5618df9d)
