### ISSUE TITLE
Breakage in visualstudio.microsoft.com

### ISSUE THREAD

**Issue by YoshiTabletopGamer** [uBlockOrigin/uAssets#10186]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16`

### Describe the issue

The filter `||monitor.azure.com^` in EasyPrivacy blocks the download of Visual Studio from Microsoft's website (more specifically, the download does not start when `js.monitor.azure.com/scripts/c/ms.jsll-3.min.js` is blocked)

### uBlock Origin version

1.38.4

### Browser name and version

Firefox 93.0

### Settings

- Default

**Comment by przemo20** [comment]
Hi.

This issue came back. uBlock Origin now blocks downloading Visual Studio 2026.

_(I am writing here, because – if I understood the Prerequisites on the Create new issue page correctly – I'm supposed to comment in the old relevant issue, instead of creating a new one)_

URL: `https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&channel=Stable&version=VS18&source=VSLandingPage&cid=2500&passive=false`

#### Steps to reproduce
1. Either visit the above URL directly, or go to `https://visualstudio.microsoft.com/`, then click on the `Get free download` purple button.

#### Result
Waiting a couple of seconds on the “Thank you for downloading Visual Studio” page, or clicking on the “click here to retry” link, doesn't start the download.

If I disable uBO, the download starts fine.

Could you reopen this issue?

#### Troubleshooting information
```
uBlock Origin: 1.67.0
Firefox: 145
filterset (summary):
 network: 160464
 cosmetic: 42011
 scriptlet: 24112
 html: 2601
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 42076-69, 7m
  ublock-badware: 10569-31, 7m
  ublock-privacy: 3547-2, 7m
  ublock-unbreak: 2771-1, 7m
  ublock-quick-fixes: 419-14, 7m
  easylist: 82487-157, 7m
  easyprivacy: 54882-44, 7m
  urlhaus-1: 30390-5, 8m
  plowe-0: 3473-970, 8m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2041 ms
 maxAssetCacheWait: 110 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  microsoft.com: 7
  azure.com: 2
  clarity.ms: 1
  newrelic.com: 1
```

**Comment by stephenhawk8054** [comment]
Caused by `||browser.events.data.microsoft.com/onecollector/`

@ryanbr

**Comment by przemo20** [comment]
Hi there.

Unfortunately, this is again broken.

#### URL
`https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&channel=Stable&version=VS18&source=VSLandingPage&passive=false&cid=2500`

#### Steps to reproduce
1. Go to `https://visualstudio.microsoft.com/vs/community/`
2. Click on the Download button

#### Result
Waiting a couple of seconds on the “Thank you for downloading Visual Studio” page, or clicking on the “click here to retry” link, doesn't start the download.

#### Troubleshooting information
```
uBlock Origin: 1.72.2
Chromium: 150
filterset (summary):
 network: 203432
 cosmetic: 50959
 scriptlet: 36523
 html: 0
listset (total-discarded, last-updated):
 added:
  POL-0: 9109-51, 1m
  POL-3: 18918-0, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 51939-94, 1m
  ublock-badware: 10287-27, 1m
  ublock-privacy: 4079-15, 1m
  ublock-unbreak: 2778-17, 1m
  ublock-quick-fixes: 481-0, 1m
  easylist: 87420-490, 1m
  easyprivacy: 55967-1, now
  urlhaus-1: 47935-11, 1m
  plowe-0: 3524-684, 1m
filterset (user): [empty]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 607 ms
 maxAssetCacheWait: 198 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  azure.com: 1
  clarity.ms: 1
  newrelic.com: 1
```
