### ISSUE TITLE
Anti-adblock in informaxonline.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10265]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://link.adslinkfly.online/vUFmpH`

### Describe the issue

After accessing the URL, it redirects to `https://informaxonline.com/` page. After fininishing the captcha and click on `I'm not robot`, the anti-adblock page appears.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/138198264-20f80645-eccf-4ef3-b0aa-0ee68dcf1891.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 93.0

### Settings

No change

### Notes

Proposed filter:

`informaxonline.com##+js(nobab)`

**Comment by garry-ut99** [comment]
Ad placeholders caused by `ghide` from "uBlock filters".
Example subpage: `https://informaxonline.com/google-is-rolling-out-android-13-beta-2-1-patch-for-pixel-devices-makes-several-improvements/`
Example ad placeholder (here full [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/216777963-1aa56214-bd81-4d21-8dec-f798640ee406.png) shootage)
![22222](https://user-images.githubusercontent.com/72945564/216777961-fa604dae-59a9-4b66-9024-e25cb11feb1a.png)
