### ISSUE TITLE
Incorrect blocking in topcryptoz.net and allcryptoz.net

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10291]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://topcryptoz.net/?link=2lE9R
https://uniqueten.net/?link=KXNyT5
```

### Describe the issue

Captcha and continue button doesn't appear

### Screenshot(s)

With `topcryptoz.net`

- Expected:

![image](https://user-images.githubusercontent.com/66517106/138540395-7d1ba5dc-370f-4d4b-ace4-82d4160d6b38.png)

- Issue:

![image](https://user-images.githubusercontent.com/66517106/138540413-a535d6a6-b2bc-4179-b5ed-27cb8144886f.png)

After continuing to page 3, it redirects to `allcryptoz.net` domain

- Expected:

![image](https://user-images.githubusercontent.com/66517106/138540441-613bc8d4-3a96-4890-bccc-d4e1e2d24445.png)

- Issue:

![image](https://user-images.githubusercontent.com/66517106/138540460-7dce9016-4bb8-4014-8458-300e0b9bd0c6.png)

The same situation happens with `uniqueten.net` and `ultraten.net` domains

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 93.0

### Settings

No change

### Notes

Sorry I didn't realize there are other 2 links with the same situation (`uniqueten.net` and `ultraten.net`) so I can't edit the title. Proposed filter:

`topcryptoz.net,allcryptoz.net,uniqueten.net,ultraten.net#@#.adb-top`

**Comment by Sandor-Helper** [comment]
The problem is similar to the one described here https://www.reddit.com/r/uBlockOrigin/comments/v7lncl/another_antiadblocker/
Link examples:
https://urlsfly.bid/w/HPCS
https://shortsfly.bid/w/uK7I5296
https://webbfly.bid/w/08WX4PJA
https://crewus.net/backup/w/?get=MG8wURc
https://thumb8.net/backup/w/?get=SDFMm
https://thumb8.net/backup/w/?get=nEEBnWOx
https://allcryptoz.net/backup/w/?get=rlmnJU

1) The uBlock detection occurs which sees the following scripts due to blocking:
https://*.cleverwebserver.com/*.js.net
||*.pub.network/
https://js.wpadmngr.com/static/adManager.js
2) If possible, I would like the captcha field to be immediately visible as it is done on shinchu.net

**Comment by Sandor-Helper** [comment]
The problem returned, again swears at the adblock (uBlock)
