### ISSUE TITLE
m.acestream.net popup

### ISSUE THREAD

**Issue by fakelok76** [uBlockOrigin/uAssets#10323]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Please add a scriptlet to close already open windows. Ace Stream opens a browser tab with ads. Add the ability to close already open windows. I beg your pardon for poor English.

### A specific URL where the issue occurs

`https://m.acestream.net/plan/select?popup=noads`

### Steps to Reproduce

Launch the ACE Stream program, which allows you to watch p2p broadcasts.

### Expected behavior

// ==UserScript==
// @name     Acestream close
// @version  1
// @include  `https://m.acestream.net/plan/select?popup=noads`
// @grant     window.close
// ==/UserScript==
window.close();

### Actual behavior

ACE Stream program, which allows you to watch p2p broadcasts, but before showing, automatically opens a tab in the browser with ads

### uBlock Origin version

uBlock Origin 1.38.6

### Browser name and version

Google Chrome 95.0.4638.54 x64 

### Operating System and version

Windows 10 x64

**Comment by dimisa-RUAdList** [comment]
@gorhill 
To solve this problem, AdGuard has created a special "window-close" scriptlet:
https://github.com/AdguardTeam/Scriptlets/issues/158
https://github.com/AdguardTeam/Scriptlets/commit/8f600c7468b3b5e3f6bc36be81a8e56aab445e87

You can add its analog for uBlock Origin?

**Comment by gorhill** [comment]
> You can add its analog for uBlock Origin?

Yes, will do.

**Comment by dimisa-RUAdList** [comment]
@gorhill 
What should be the syntax for the patch in the case of `https://m.acestream.net/plan/select?popup=noads`?

Rule `m.acestream.net##+js(window-close-if, /plan/select?popup=noads)` - does not work.

Rule `m.acestream.net##+js(window-close-if)` - works, but it is redundant

**Comment by dimisa-RUAdList** [comment]
Open `https://m.acestream.net/plan/select?popup=noads` in a new window.

**Comment by gorhill** [comment]
Ugh, typo in scriptlet, will fix asap

**Comment by dimisa-RUAdList** [comment]
In version uBlock Origin development build 1.39.3b11, the rule works great!

**Comment by gwarser** [comment]
@gorhill 

Does not work? Tried:

    m.acestream.net##+js(window-close-if, /plan/select?popup=noads)


>Scripts may not close windows that were not opened by script.

https://developer.mozilla.org/en-US/docs/Web/API/Window/close

>This method can only be called on windows that were opened by a script using the Window.open() method. If the window was not opened by a script, an error similar to this one appears in the console: Scripts may not close windows that were not opened by script.

**Comment by dimisa-RUAdList** [comment]
Really. When using the AceStreamMedia program at the address: `https://acestreamsearch.net/?q=Match+TV` - rule `m.acestream.net##+js(window-close-if, /plan/select?popup=noads)` - does not work due to restriction "_Scripts may close only the windows that were opened by them_".

At the same time, the script:
```
// ==UserScript==
// @name Acestream close
// @Version 1
// @include https://m.acestream.net/plan/select?popup=noads
// @grant window.close
// ==/UserScript==
window.close();
```
uploaded to Tampermonkey or Violentmonkey, works as intended. Probably, these extensions have more rights than uBlock Origin.

However, the added scriptlet is not useless at all. It allows you to force the window to close using this rule: https://github.com/easylist/ruadlist/commit/d8d3d65caeed58c0690ce978e8cde5315431dd9c

**Comment by gwarser** [comment]
OK, it seems to work in Firefox when launched from command line or even when opening from bookmarks as new tab.

I cannot fool it like this in Chrome.

**Comment by gorhill** [comment]
> `https://acestreamsearch.net/?q=Match+TV`

What is supposed to happen when I navigate there? Nothing happens on my side in neither Chromium nor Firefox.

**Comment by dimisa-RUAdList** [comment]
First you need to install: `http://download.acestream.media/products/acestream-full/win/latest`
Further: `https://imgur.com/a/bwcsOM6`

**Comment by gorhill** [comment]
Ok I won't be able to reproduce this case. I see the popup navigates to `https://m.acestream.net/plan/select?popup=noads` from some  `silvercube12.xyz` -- I would expect a plain `popup` filter would work.

Maybe `window-close-if` could be a special scriptlet for which the closing of the window is handled through extensions API, [`browser.tabs.remove()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/remove).

**Comment by dimisa-RUAdList** [comment]
Currently, the only scriptlet that can solve this problem is `window-close-if`. But it blocks the initiator `silvercube12.xyz,` it cannot close the landing page `https://m.acestream.net/plan/select?popup=noads`. This means that as soon as the initiator address changes, the problem will reappear. And if the initiator's address becomes random, then it will become impossible to solve the problem at all. To achieve a stable solution to the problem, the scriptlet needs to be able to close the final landing page `https://m.acestream.net/plan/select?popup=noads`.

This is exactly what is described here: https://github.com/AdguardTeam/Scriptlets/issues/170

**Comment by gorhill** [comment]
With Chromium, with your filter `m.acestream.net##+js(window-close-if, /plan/select?popup=noads)`, when select and right-click on `https://m.acestream.net/plan/select?popup=noads` and select _"Go to `https://m.acestream.net/plan/select?popup=noads`"_, the new tab being opened is properly close by the scriptlet. So if I understand correctly, this does not work when the tab is opened by the application?

**Comment by dimisa-RUAdList** [comment]
Yes that's right. When using an application, this rule does not work.

**Comment by gorhill** [comment]
I feel like the fact that the new window is not detected as a popup candidate is what should be investigated.

**Comment by gorhill** [comment]
Ok, though I can't reproduce using the Windows application, I can reproduce similar scenario using the command line:

    chromium --new-window https://silvercube12.xyz/dispatch

Which allows me to put breakpoints in uBO's code.

So it turns out uBO has code to detect popups opened in a separate window, which was added because of <https://github.com/uBlockOrigin/uBlock-issues/issues/1659#issuecomment-879905137>. In the current case though, I see the the added code bails out at <https://github.com/gorhill/uBlock/blob/1.39.2/platform/chromium/vapi-background-ext.js#L70>, because the `transitionType` property is **not** `client_redirect`, but rather `start_page`. So maybe it's a matter of fine-tuning that one condition.

**Comment by uBlock-user** [comment]
So we don't need `window-close-if` scriptlet then ?

**Comment by gorhill** [comment]
Not if the change I can make has no bad side effect. I just tested what would happen if the browser is launch with that command line -- i.e. there are no existing instance, and the browser window in such case is not closed, which is a good thing, it would be bad if a false positive prevented the browser from launching at all.

**Comment by dimisa-RUAdList** [comment]
When using uBlock Origin development build 1.39.3b12, the following rules work and close the new window:
```
||silvercube12.xyz/dispatch?$popup
||m.acestream.net/plan/select?popup=noads$popup
silvercube12.xyz##+js(window-close-if, /dispatch)
```

**Comment by gwarser** [comment]
So `window.close()` can be tested by calling from dev tools console. Pages are closed when launched directly in tabs - opened directly from command line but also from bookmark by middle click. Does not work when opened (navigated) from address bar, by launched from bookmark in current tab.

***

Session restored tabs are closed in Firefox. So, if you have for example two `example.com` tabs open -> list updates in the background (add `example.com##+js(window-close-if)` and close Dashboard) -> close Firefox -> browser cannot be opened now because all tabs and browser closes immediately.

**Comment by gwarser** [comment]
> Session restored tabs are closed in Firefox. So, if you have for example two `example.com` tabs open -> list updates in the background (add `example.com##+js(window-close-if)` and close Dashboard) -> close Firefox -> browser cannot be opened now because all tabs and browser closes immediately. Edit: on first restart both tabs will be closed, on second restart only one tab will be restored, but again browser will be closed.

No bug in Chrome - on next browser start "New tab" is opened.
