### ISSUE TITLE
soft98.ir ads and detection

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#10883]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://soft98.ir`
`https://soft98.ir/internet/web-browser/3545-microsoft-edge.html`

### Related to: https://github.com/uBlockOrigin/uAssets/issues/3011

Some of these filters from the [uBlock filters](https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L10765) aren't working anymore (similar filters can be found in the [IRN: Adblock-Iran](https://github.com/farrokhi/adblock-iran/blob/master/filter.txt#L677) list from @farrokhi):
```
soft98.ir##+js(nostif, e(), 3000)
soft98.ir##+js(set, Object.prototype.checkAdBlocker, noopFunc)
@@||soft98.ir^$ghide

soft98.ir##.a1d2x
||redlini.ga^
```

* The `soft98.ir##.a1d2x` doesn't work anymore because `a1d2x` is now called `a7d8x` in the website and it seems to be constantly changing, so we need something regex like `soft98.ir##.a*x` (_Screenshot 1_).

* The `||redlini.ga^` doesn't work anymore because the URL has changed to `orgiin.gq` (`orgiin.gq/padvish3.az`) so a _cosmetic filter_ to block the ads would work more efficiently instead. _(because it seems that the website developer changes the URL on purpose to evade adblockers)_

* The `soft98.ir##+js(nostif, e(), 3000)` and `soft98.ir##+js(set, Object.prototype.checkAdBlocker, noopFunc)` **doesn't defuse the anti-adblock** function inside the soft98.ir's jquery.js because it can still detect cosmetic filters like `soft98.ir##.a7d8x` and disables all links (including download links) (_Screenshot 2_):
```
var T = {
    error_a7d8x: "Ø¬Ù‡Øª Ù…Ø´Ø§Ù‡Ø¯Ù‡ Ù„ÛŒÙ†Ú©ØŒ Ø§ÙØ²ÙˆÙ†Ù‡ Ø­Ø°Ù ØªØ¨Ù„ÛŒØºØ§Øª Ø±Ø§ Ø¯Ø± Ù…Ø±ÙˆØ±Ú¯Ø± Ø®ÙˆØ¯ ØºÛŒØ±ÙØ¹Ø§Ù„ Ùˆ Ø¯Ú©Ù…Ù‡ F5 Ø±Ø§ Ø¨Ø²Ù†ÛŒØ¯",
}
var bK = ".a7d8x, .a7d8x *",
    on = "js-enable-",
    rn = D.get("error_a7d8x", {
        onclick: "location.reload();
        return false;
        "
    });
```

### Screenshot(s)

* Screenshot 1:
![Break25](https://user-images.githubusercontent.com/17685483/145704138-f2216fe1-1922-4cfd-91ca-01a14a6fb21c.png)

* Screenshot 2:
![Break26](https://user-images.githubusercontent.com/17685483/145704274-daac7c69-f41b-4b83-8296-1b6a1477ee59.png)

* Screenshot 3:
![Break27](https://user-images.githubusercontent.com/17685483/145704654-15ed054b-e936-4555-9bfe-79b632d68fba.png)

### Notes

* A network filter like `||orgiin.gq/padvish3.az$image` and `||cdn.hostdl.com/assets/soft98.gif$image` seems to work **for now** but the website developer has changed the address in the past (it was `redlini.ga` before), and he might do it again; So a _cosmetic filter_ would be the best option.

* https://github.com/DRSDavidSoft/user-scripts/issues/1#issue-551162615:
There is a [soft98_ad-unblocker.user.js](https://github.com/DRSDavidSoft/user-scripts/raw/master/soft98_ad-unblocker.user.js) script created by @DRSDavidSoft that works perfectly by defusing soft98.ir's anti-adblock and removing all ads and empty spaces (_Screenshot 3_) but it requires Tampermonkey.

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78477
  cosmetic: 40414
  scriptlet: 16273
  html: 0
listset (total-discarded, last updated): 
  added: 
    IRN-0: 1315-0, 1m
  default: 
    easylist: 61638-10, 3m
    easyprivacy: 26484-17, 3m
    plowe-0: 3687-810, 3m
    ublock-abuse: 72-0, 3m
    ublock-badware: 3565-61, 3m
    ublock-filters: 29884-130, 3m
    ublock-privacy: 189-2, 3m
    ublock-unbreak: 1712-39, 3m
    urlhaus-1: 7830-0, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 359
  launchFromSelfie: false
```
</details>

**Comment by uBlock-user** [comment]
Can't repro anti-adblock, I only see ads.

**Comment by MasterKia** [comment]
> Can't repro anti-adblock

Add `soft98.ir##.a7d8x` to my filters and refresh the page.

**Comment by MasterKia** [comment]
Please reopen the issue because the **anti-adblock has been updated** and it's back.

When I created the issue, the site used jquery.js [v2](https://soft98.ir/templates/soft98_default/js/jquery.js?v=2) but now it users jquery.js [v3](https://soft98.ir/templates/soft98_default/js/jquery.js?v=3).

**Comment by MasterKia** [comment]
Can we force the site to use a _modified version_ of jquery.js without the anti-adblock function?

**Comment by MasterKia** [comment]
> Please reopen the issue 

@mapx-

**Comment by uBlock-user** [comment]
> Please reopen the issue because the anti-adblock has been updated and it's back.

fixed, admin is watching, re-opening only attracts un-necessary attention.

**Comment by DRSDavidSoft** [comment]
As @mapx- also stated in https://github.com/uBlockOrigin/uAssets/issues/3011, the Soft98 admins are tracking changes to many lists -- that especially focus on combatting the useless ads on Soft 98.

As previously discussed with him (I believe his name is Salar), he genuinely has the impression that hiding the useless Padvish ads (and kaprilla, etc) on the site directly results in lost revenue.  (Personally, I disagree, since I never _look at_, let alone click on these scummy and flashing ads on the page).

In any case, as @MasterKia also mentions, it is indeed possible to replace the (in-aptly named) `jquery.js` file with a version that _doesn't mess_ with the download links, but it's also possible that the admins/developers change the HTML in a way that would render this approach unsuitable.

Personally, the user script that I wrote can handle the changes to class names, and also removes the useless elements in a way that Soft98 can't easily detect; and additionally _if_ they could detect it and disable the download links' functionality, my script attempts to restore the correct download links back to the initial state.

It would be nice if uBlockOrigin could support cases slightly more complex like this _natively_, but since I already use Tampermonkey to fix up a couple of other sites that pull stunts similar to this, I thought it'd be worth the attempt.

AdGuard is currently using a similar approach to diffuse Soft98's ad-detecting mechanisms, I believe.

Watching this issue and #3011 for possible future development. In the meantime, I invite people to give my user script a try, it could work both as a standalone script, or in tandem with uB<sub>0</sub>.  Cheers! 😄

**Comment by MasterKia** [comment]
The ads is now back again:
![image](https://user-images.githubusercontent.com/17685483/146663916-b59490a3-b299-4671-bf42-ca7deea00701.png)

**Comment by MasterKia** [comment]
@uBlock-user @mapx-

**Comment by detectbug** [comment]
Если UBLOCK активирован, поиск не работает и новости фотографии не отображаются.

**Comment by MasterKia** [comment]
The ads is back again.

**Comment by uBlock-user** [comment]
text ad, not clickable anymore.

**Comment by MasterKia** [comment]
> text ad, not clickable anymore.

They are reinserting the text ads, when the website is loaded the text ads are gone for a few seconds then they reappear and now they're clickable.
Also the jguery.js is now on v6.

**Comment by MasterKia** [comment]
Please reopen, if it's possible.

**Comment by MasterKia** [comment]
@mapx- Please reopen.

**Comment by uBlock-user** [comment]
> s0ft98-defuser.js: https://github.com/DRSDavidSoft/user-scripts/raw/master/soft98_ad-unblocker.user.js

If you're suggesting adding that only gorhill can add that. Then again, it can also be easily bypassed if the admin is willing to fight back.

**Comment by MasterKia** [comment]
> adding

I'm suggesting that maybe it could help to solve the issue **without  a userscript** and with **scriptlets** instead, but adding it to uBO is a good solution too.



> it can also be easily bypassed if the admin is willing to fight back.

Well so far admin's attempt to bypass uBO hasn't affected that userscript yet and it still works despite the ad-reinsertion, but that could change as you said.



> if the admin is willing to fight back

I've talked to @DRSDavidSoft and he told me that he's willing to _further maintain_ the userscript in the event that the admin applies a bypass.

**Comment by uBlock-user** [comment]
@gorhill

**Comment by DRSDavidSoft** [comment]
@uBlock-user @gorhill @MasterKia -- sorry before hand for the long comment, as I tend to usually write

Hey all, I've written this userscript since (to the best of my knowledge) uBlock Origin lacked the functionality to either:
1) preserve the download links, before they get removed
2) Block specific javascript running based on what it's doing

I'm willing to maintain my userscript to the best of my ability.  I would very much rather to _not_ rely on a userscript myself, but as long as the features I'm using (Sentinel to detect new insertions, ability to preserve original tag href, etc) is not present in the uBO's core, I think this is the way to go.

I'm pretty much an anti-ads freak, whenever I see any type of ads, I feel the need to nuke them from the orbit! 😅 So I'm pretty willing to maintain my userscript -- though, if it's going to be officially added to uBO (kind of like how AdGuard has a similar userscript), I would like to re-write it from scratch with better coding styles (and less swear words, lol)

As you can see from the [commit history](https://github.com/DRSDavidSoft/user-scripts/commits/master), it's been working for six months, after the latest changes I did (you can read the source code). The only commit after that was to fix links not being able to clicked on, which due to what @uBlock-user said:

> text ad, not clickable anymore.

I figure out that's what disabled links with the `target` attribute, and caused me to release this path: https://github.com/DRSDavidSoft/user-scripts/commit/190b4645836208e66df4a6de7b8e91a755741824

BTW I've talked to the site owner (@soft98admin on Telegram) -- he's a nice and pretty cool guy, but he seems not to understand that **we** don't want to click on Kaprilla, Padvish, and other garbageware ads on the website.  He refused to share an answer when I asked him if it affects the website _not to_ display useless ads, when the user is _not_ clicking on them anyway.

Instead, he (or the developers) are quite keen on making sure the ads are displayed on the website, possibly to satisfy the ad customers.

Any ways, I tried pushing some filters to the known iranian filters (https://github.com/farrokhi/adblock-iran/blob/master/filter.txt) and that didn't quite work (remnants are still present), so I went ahead and wrote my userscript.

If it's to be included officially in uBO, I'll be happy to re-write it with uBO standards in mind.

**Comment by farrokhi** [comment]
This is potentially a cat and mouse game, since they closely monitor blocklist updates and adjust accordingly.

**Comment by DRSDavidSoft** [comment]
@farrokhi I'm positive that is surely is, that's why in my userscript, I've tried to outsmart them by not using a fixed class name altogether

**Comment by gorhill** [comment]
I won't add a huge scriptlet which is to be used for one single site, and which could become quickly obsolete. or such cases, user scripts is the way to go.

**Comment by MasterKia** [comment]
So uBO is taking the [acceptable ads](https://acceptableads.org) approach?
This site has a rank of 950 in the global ranking (according to [alexa](https://www.alexa.com/siteinfo/soft98.ir)).

**Comment by gorhill** [comment]
> So uBO is taking ABP's acceptable ads approach?

Now you are just trolling.

This is no different than Twitch for which an external solution is advised.

**Comment by uBlock-user** [comment]
Adguard themselves are not fixing this site in their own lists and rather moved it to AdGuard Extra for the same reason @farrokhi mentioned. It's not worth it.

**Comment by MasterKia** [comment]
> Now you are just trolling.

Sorry.

> This is no different than Twitch for which an external solution is advised.

Well that's true. AFAIK it's only Twitch and s0ft98, for **now**.

I'm afraid what would happen if more sites start to adapt the same (simple) solution where they put all of their site's functionality in a _jquery.js_ (or other in-aptly named files) and implement ad-reinsertion as well.

**Comment by uBlock-user** [comment]
> where they put all of their site's functionality in a jquery.js (or other in-aptly named files) and implement ad-reinsertion as well.

You install AdGuard Extra, it specifically deals with such sites.

**Comment by gorhill** [comment]
> where they put all of their site's functionality in a _jquery.js_

A reference library used by many sites would then make it worth to add scriptlet to counter it, just like we do have such code for blockadblock.

**Comment by uBlock-user** [comment]
@gorhill Unfortunately it's their custom anti-adblock script detection, not used anywhere else.

**Comment by MasterKia** [comment]
> Unfortunately it's their custom anti-adblock script detection, not used anywhere else.

True.

`https://soft98.ir/templates/soft98_default/js/jquery.js?v=12`

The unpacked and formatted version for examination (Search for _b7d9x_):
https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/soft98-antiadb.js

**Comment by gorhill** [comment]
> Unfortunately it's their custom anti-adblock script detection

I understand this. I was answering to _"what would happen if more sites start to adapt the same (simple) solution"_.

**Comment by DRSDavidSoft** [comment]
Personally, I don't mind using external solutions (e.g. Anti AdBlock Killer, FuckFuckAdBlock, AdsBypasser, etc) for situations like this.  As @gorhill said, it's not a functionality suited well for uBO's, it doesn't make sense to start cooking up solutions for each and every site (e.g. Twitch). The extra or external packages are made just for dealing with this stuff.

It's be neat not to have to rely on Userscripts just to remove ads from various websites, but when I'm going to use Userscripts for these scenarios anyway, why would it matter

I'm still interested to achieve the functionality of my Userscript with pure filters list, but currently, I think this is the way to go.

@gorhill Nice work BTW, huge fan and hats off, sir.  I really appreciate the work you do!

@MasterKia for now, I hope my Userscript continues to work.  I'll look up for ways to merge it with other more popular scripts, so at least its installation is more justified.
