### ISSUE TITLE
Resource abuse list is not blocking BTC miner on theappguruz.com

### ISSUE THREAD

**Issue by agottardo** [uBlockOrigin/uAssets#1106]
### URL(s) where the issue occurs

[http://www.theappguruz.com/](http://www.theappguruz.com/)

### Describe the issue

[The page contains a Bitcoin miner (Coinhive). uBlock is not blocking it. Linked in the first line of HTML source, `<script src='/vendor/composer/installed.js'></script>`.]

### Versions

- Browser/version: Safari 11.0.2.
- uBlock Origin version: 1.14.14

### Settings

- No changes to the default settings, all default lists enabled, including 'uBlock filters – Resource abuse'.

**Comment by okiehsch** [comment]
I also added `theappguruz.com##script:inject(abort-on-property-read.js, miner)`, to prevent this site from
simply renaming their script to continue mining.

**Comment by gorhill** [comment]
> to prevent the site from simply renaming the script to continue mining.

Maybe we could start using a CSP directive to prevent working around filters by merely changing names:

    theappguruz.com$csp=child-src 'none';frame-src *;worker-src 'none';

**Comment by okiehsch** [comment]
That would be even better, provided nothing breaks, which should not be a problem in this case.

Just to clarify I added the `script:inject` filter mainly because the location of the mining script, i.e.
**above** the DOCTYPE-declaration looked strange to me and the site is blocked by `Norton Safe Web`.
So I am not sure the website owner is actually aware of the mining-script.
