### ISSUE TITLE
Double rule `statcounter.com`

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#11321]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

**NSFW** example `https://neukcontacten.info/`

### Describe the issue

In uBlock unbreak is the same rule as in EasyPrivacy `||statcounter.com^$3p`. 
I think double rules should be removed.

### Screenshot(s)

<details><Summary>Screenshot</Summary>

![image](https://user-images.githubusercontent.com/81161435/149616040-240121ef-531c-4e92-a174-45d6440b6f78.png)

</details>

### uBlock Origin version

1.39.2 (this is the latest version in MS Edge - still not updated)

### Browser name and version

MS Edge v97

### Settings

<details><summary>uBlock settings</summary>

```
uBlock Origin: 1.39.2
Chromium: 97
filterset (summary): 
  network: 67442
  cosmetic: 42442
  scriptlet: 16441
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2994-10, 2h.12m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal%20List%20(uBo).txt: 1913-1, 2h.12m
  default: 
    ublock-filters: 30243-93, 2h.3m
    ublock-unbreak: 1750-10, 2h
    easylist: 63005-150, 1h.58m
    easyprivacy: 26626-89, 1h.56m
filterset (user): [array of 146 redacted]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 7 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  firewallPaneMinimized: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#4242CA 00001
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  uiFlavor: classic
  updateAssetBypassBrowserCache: true
supportStats: 
  launchToReadiness: 28281
  launchFromSelfie: false

```

</details>

**Comment by okiehsch** [comment]
The rule in `unbreak` is there because we "badfiltered" a filter in `Peter Lowe's list`,
We decided some time ago that we would add a third-party block filter for such cases to ensure that users who have that list enabled and disable `EasyPrivacy` can still be sure that `Peter Lowe's` list still works as intended.

If you look through the `unbreak` list you will find many more "duplicates" of the same nature.

**Comment by stephenhawk8054** [comment]
Is it ok to block all of `statcounter.com` links? Since sometimes I see other websites use their sources to display charts.

Example URL:
`https://www.windowscentral.com/microsoft-edge-closing-gap-safari-second-place-great-browser-wars`

There's a chart of browser market share but it's blocked due to `||statcounter.com^. These scripts are responsible for the charts

```
gs.statcounter.com/chart.php$script
www.statcounter.com/js/fusioncharts.js$script
www.statcounter.com/js//fusioncharts.charts.js$script
```

**Comment by stephenhawk8054** [comment]
Also with this URL:
`https://gs.statcounter.com/browser-market-share/desktop/worldwide/#monthly-202102-202202`

Looks like there should be 
```
||www.statcounter.com^$badfilter
```
besides `||statcounter.com^$badfilter` too? Since when I enable `MVPS HOSTS`, the icons in that URL are blocked

<details><summary>Screenshot (icons blocked)</summary>

![image](https://user-images.githubusercontent.com/66517106/154844665-51c1f40d-5581-4e1a-b9b7-732b5c04d956.png)

</details>

The logger tells that the images are blocked by MVPS list

<details><summary>Screenshot (logger)</summary>

![image](https://user-images.githubusercontent.com/66517106/154844693-7203c0ce-1bb1-4dea-a94f-6ee06809315a.png)

</details>

**Comment by uBlock-user** [comment]
> Since when I enable MVPS HOSTS

MVPS is not a **default list**

**Comment by stephenhawk8054** [comment]
Actually because I see this comment that address `statcounter` filter issues in 4 filter lists, including MPVS and Dan Pollock also, so I thought I should report that situation too

```
! To counter `statcounter.com` in Peter Lowe's, MVPS, Dan Pollock's and hpHosts
||statcounter.com^$badfilter
||statcounter.com^$3p
```

Enabling Dan Pollock gives the same issue.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d5eba59bc1f95cf2d07cfdc68b17df6482d04b3f#diff-f25213e47a9079152b6b778b89dcd2b9060fb7e390d13899c061067712c2444dR28

That text was added before the rule was enacted. Regardless the rule still stands.

**Comment by stephenhawk8054** [comment]
So we should remove `||www.statcounter.com^$badfilter`?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/f376bb8ee60ff2e399a59f30f2e1f8ca60f14051
