### ISSUE TITLE
echo-online.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#11915]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.echo-online.de/`

### Describe the issue

After i accepted the consent banner i get anti adblock

### Screenshot(s)

![Unbenannt](https://user-images.githubusercontent.com/48647394/155850785-459f8069-71c3-4346-bc07-b544363a23d7.PNG)

### uBlock Origin version

1.41.8

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock Origin Annoyances

**Comment by garry-ut99** [comment]
Ad placeholders all over the site caused by `ghide` in "uBlock filters"

<details>
   <summary>SCREENSHOOT</summary>

![1 (2)](https://user-images.githubusercontent.com/72945564/215221384-4b838028-7a48-4f60-acfc-ce6d602e8daa.png)
![1 (3)](https://user-images.githubusercontent.com/72945564/215221389-3b05f29d-a8eb-4a89-abd9-a342ad9b2f53.png)
![1 (4)](https://user-images.githubusercontent.com/72945564/215221392-1c844671-54a0-4220-b245-077e786ba56b.png)
![1 (5)](https://user-images.githubusercontent.com/72945564/215221395-f06e610b-381c-433b-9301-d3a8bff9c8fc.png)
![1 (6)](https://user-images.githubusercontent.com/72945564/215221398-1a81075d-2a98-46e8-a6da-31a530d14b95.png)

</details>

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon @okiehsch There's a part in the home page containing `Lokales` and `Meine Nachrichten` that is blocked unless allowing these

```adb
@@||scdn.cxense.com/cx.cce.js$script,domain=echo-online.de
@@||api.cxense.com/public/widget/data$xhr,domain=echo-online.de
```

Screenshot  
<details>

![image](https://user-images.githubusercontent.com/66517106/215237331-9e765cb9-f8ac-401d-92a7-72214d5bedb1.png)

</details>

Do you think above filters would be needed?

**Comment by garry-ut99** [comment]
> https://github.com/uBlockOrigin/uAssets/commit/0a01bb06d8aa8332fd3c8102b2e411d25d9c460f

Other ad placeholders have been hidden, but the ad placeholders "Anzeige" visible on the screenshoot https://github.com/uBlockOrigin/uAssets/issues/11915#issuecomment-1407167951 still not hidden, maybe you forgot, this worked: `echo-online.de##.adSlot`

**Comment by mapx-** [comment]
`Lesen Sie jetzt` broken, @stephenhawk8054 exceptions working fine

**Comment by garry-ut99** [comment]
Other websites from the same family affected by placeholders: https://github.com/uBlockOrigin/uAssets/issues/12360#issuecomment-1407314583
