### ISSUE TITLE
http://kinotochka.net websockets

### ISSUE THREAD

**Issue by TheFinalCut83** [uBlockOrigin/uAssets#123]
### URL(s) where the issue occurs

http://kinotochka.net/3552-cherepashki-nindzya-2-2016.html

### Describe the issue

Exactly the same situation as in #120. 

### Screenshot(s)

[Link with ads in red frame](http://i.imgur.com/Q88Ng6D.jpg)

### Versions

- Browser/version: Cyberfox 48.0.2, Firefox 49.0b7
- uBlock Origin version: 1.9.4

### Settings

default settings

Filter lists:
uBlock filters
uBlock filters – Badware risks‎
uBlock filters – Privacy‎
uBlock filters – Unbreak‎
Adblock Warning Removal List
Anti-Adblock Killer | Reek
EasyList
EasyPrivacy‎
Malvertising filter list by Disconnect‎
RUS: Adguard Russian Filter
RUS: BitBlock List
RUS: RU AdList

### Notes

Candidate for inclusion in `*$websocket,domain=extratorrent.cc|free-torrents.org|natureworldnews.com|opensubtitles.org|parentherald.com|pornhub.com|redtube.com|redtube.com.br|tomshardware.com|tube8.com|tube8.es|tube8.fr|xtube.com|youporn.com|youporngay.com`

But this is becoming a frightening trend - 2nd website with missing websockets for a 2 days and the number of websockets missed that way could spontaneously increase. 
RU AdList is [already got fix](https://hg.adblockplus.org/ruadlist/rev/1bb0c7e84944) for subject (in the same way as [for free-torrents.org 2 days ago](https://hg.adblockplus.org/ruadlist/rev/d277c4ba858c)).
Cyberfox with only ABP - [all is fine](http://i.imgur.com/ZSHh0HG.jpg) because of `|ws://*.kinotochka.net^`
Cyberfox with only [Adguard addon](https://addons.mozilla.org/ru/firefox/addon/adguard-adblocker) - [all is fine](http://i.imgur.com/nBriJNo.jpg) because of `|ws://*.kinotochka.net^`
uBO really needs ABP syntax for websockets (because uBO just can't deal with ABP websocket syntax at the moment) until it will become a huge problem for all uBO users under Gecko-browsers.

**Comment by gorhill** [comment]
Unable to reproduce. The websocket request is being blocked by RUAdlist's `.kinotochka.net^$~object-subrequest,domain=kinotochka.net` in uBO 1.9.4.

**Comment by gorhill** [comment]
Your RUAdlist was updated before you submitted this issue: <https://hg.adblockplus.org/ruadlist/rev/14d75c6c8b7e>. Be sure you use the most up to date lists before submitting an issue.

However, I still need to add `*$websocket,domain=kinotochka.net` not for your specific issue, but for Chromium-based browsers.

**Comment by TheFinalCut83** [comment]
I cleared all the caches right before the investigation of this issue. Unfortunately, filter lists in uBO don't update instantly. Still, conclusion of "Notes" section remains actual - similar issues in the near future can occur more often (this naturally coincided with the update of ABP in Chrome with websockets support). And can i clarify - are you always investigating issues in Chromium?

**Comment by dimisa-RUAdList** [comment]
I deliberately introduced a rule in membership due to the fact that using a standard ABP-syntax uBO not block anything.  TheFinalCut83 was initially aware of this problem and this commit. I debited from it. Soon, these resources will be very much. We are talking about support for ABP-syntax.

**Comment by gorhill** [comment]
> conclusion of "Notes" section remains actual

Except that it is incorrect to claim that ABP blocked the websocket connection because of `|ws://*.kinotochka.net^`: that filter does not work -- maybe it used to but it does not work with the current state of the site. It's quite probably why RUAdList was updated.

So you tested with ABP and Adguard with an up to date RUAdList. You tested with uBO without an up to date RUAdList.

**Comment by gorhill** [comment]
> I deliberately introduced a rule in membership due to the fact that using a standard ABP-syntax uBO not block anything.

Blocking the fetching of a resource should always be the first choice rather than hiding it after the fact. Are you making the point that using `[-abp-properties="..."]` was your solution of choice rather than outright blocking the network request fetching the resource?

I do not consider all of ABP's choice regarding filter syntax to be religious doctrine. I stick to pragmatism.

**Comment by lainverse** [comment]
Gorhill, I think you misunderstood a few things.

dimisa-RUAdList is maintainer of RU Adlist. Same as me. He added that `|ws://*.kinotochka.net^` rule and it works just fine with Adblock Plus.
Here is an example: http://pasteboard.co/f24zUJHJf.png

He had to replace it with `.kinotochka.net^$~object-subrequest,domain=kinotochka.net` later since first one, even though it's _a completely valid ABP filter_ didn't work in uBO.

In fact he has to resort to `|ws://*.kinotochka.net^` syntax because `||kinotochka.net^$other` blocks access to site in uBO for some reason even though it has to be `$document` instead of `$other`. No?

Also, he didn't mentioned `[-abp-properties="..."]` anywhere here even once. We do need it in some cases, but this is not the one.

**Comment by gorhill** [comment]
I looked a bit more afterward. Here is what is happening.

I had assumed @dimisa-RUAdList was referring to `[-abp-properties="..."]` when he said _"about support for ABP-syntax"_ as this has been a litigious point with him in the past. Now you are right there is no `[-abp-properties="..."]` involved.

The issue which affected uBO on FF was not because of _"[e]xactly the same situation as in #120"_ as stated by @TheFinalCut83.

The issue was the site adding `display: block !important` on the element targeted by the cosmetic filter `kinotochka.net###\36 00`. uBO does not make use of user stylesheets on Firefox (I may start to look into this), so it is more sensitive to sites adding inline display style to target elements. ABP suffers exactly the same problem on Chromium-based browser, so this is not a ABP-syntax support issue.

The issue does not occur on Chromium-based browsers because of the filter `|ws://*.kinotochka.net^`, which I gather was created to address the issue strictly for the `display: block !important` issue on Chromium-based browsers: without the websocket filter, ABP suffers exactly the same fate as uBO on Firefox.

The websocket request is not blocked on Firefox, the click bait ads are just hidden by the filter `kinotochka.net###\36 00`. Easy to verify with `||kinotochka.net^$element-hide`.

The best solution for all browsers of course is to block websocket requests for that site, so that the click-bait ads are not downloaded in the first place, and not inserted into the DOM. This can be done for Firefox as well with:

    ||etg.kinotochka.net^

This would work for both Firefox and Chromium, and for both uBO and ABP. (Or do they change the `etg` part regularly and it's why the `*` in `|ws://*.kinotochka.net^`?)

**Comment by gorhill** [comment]
> In fact he has to resort to |ws://*.kinotochka.net^ syntax because ||kinotochka.net^$other blocks access to site in uBO for some reason even though it has to be $document instead of $other. No?

`other` should not trigger strict blocking, I consider this a bug. I was not aware of this and even surprised, thanks for bringing this to my attention. I suspect it's an old code path I forgot to remove after I started to use `document` instead of `other`.

**Comment by dimisa-RUAdList** [comment]
I spent 8 months on the adaptation RU AdList under the uBO. Rule `.kinotochka.net^$~object-subrequest,domain=kinotochka.net` not the only one added specifically because of uBO, such rules hundreds, closer to thousands. I need not so much - to work the syntax of ABP. This applies to `ws://, wss://`(for Firefox) and `abp-properties`. And when I found that option `other` locks the resource, I was very surprised. We can cooperate, if no, then let it be your decision.

**Comment by gorhill** [comment]
> when I found that option other locks the resource, I was very surprised.

Me too, this is a bug which is fixed in 1.9.5b1. When I moved to use `document` instead of `other` for strict blocking, I needed a transition period before I stop using `other` to ensure strict blocking still worked for those with older filter lists. I just forgot to come back to finish the fix after the transition period. I will try to publish the fix asap given that now `other` is used a lot more than it used to.

Also, I added code to internally add `websocket` filter option everywhere `other` is used. It's unfortunate that ABP sees websocket requests as `other`, I think this is going to be an issue sooner than later, given that there are other useful things that go in the `other` basket.

> This applies to `ws://`, `wss://` (for Firefox)

Just to be sure this is understood, the filter `|ws://*.kinotochka.net^` does nothing on Firefox, websocket connections are not blocked for that site on Firefox with ABP. Also, I was mistaken when I said `||etg.kinotochka.net^` would block websocket connections for Firefox/ABP, but for some reasons it does not work. This needs to be investigated by ABP devs. The only thing preventing the click-bait ads from being visible with Firefox/ABP is element hiding, not websocket blocking.

**Comment by lainverse** [comment]
I've reported lack of 'websocket' type into ABP's issue tracker: https://issues.adblockplus.org/ticket/4387

**Comment by lainverse** [comment]
Hi Gorhill,

Are you using mutli-threaded version of Firefox? I'm using 50.0a2 and it looks like ABP doesn't see any WS connections there at all!
However, it does see then in the normal Fx version. Here is an example from free-torrent.org:
https://drive.google.com/open?id=0BzbKPhiCU6YUcjBKRXRkVXVyWHp2TlZtZ29sQmlOSU83WDc0
Here is the same site in Fx 50.0a2:
https://drive.google.com/file/d/0BzbKPhiCU6YURWhsdDZSdDhHQmRVTXVsRENtU0pyZ1B2OUdn/view?usp=sharing
As you can see they appear as upgraded there and doesn't appear in blockable items at all.

So, Dimisa tested `|ws://*.kinotochka.net^` filter with normal non-multithreaded Fx and it worked there.

**Comment by gorhill** [comment]
Yes, I was using Nightly.

**Comment by gorhill** [comment]
Dev build 1.9.5b2 is on AMO, it solves many of the issues raised here:
- `other` no longer trigger strict blocking
- when encountering filter option `other`, uBO will internally also apply the filter to `websocket` requests
- cosmetic filtering make use of user style sheet

I tested the page in OP's comment with Firefox stable + 1.9.5b2 with default settings minus uBlock filters + RUAdList, and all seems ok -- except that the video does not play, but there appear to be a blocking filter in RUAdList preventing the video from loading: `.kinotochka.net^$media,domain=kinotochka.net`. If I bypass the block filter for media resources from `cdn6.kinotochka.net`, the video played fine.

**Comment by dimisa-RUAdList** [comment]
Ok, I added an exception `media` to the rule: https://hg.adblockplus.org/ruadlist/rev/476dd6c1f3fc

By the way, this option `media` does not detect all the browsers. In any case, this is a temporary solution. When can we expect `ws://, wss://` (for Firefox)?

**Comment by mapx-** [comment]
you have to add also "other" for chromium browsers
`.kinotochka.net^$~media,~other,~object-subrequest,domain=kinotochka.net`

**Comment by dimisa-RUAdList** [comment]
What for? You can more details?

**Comment by mapx-** [comment]
$media for chrome browsers is seen like $other
for example see easylist examples:
`@@||vidible.tv/stage/$media,object,other`

**Comment by dimisa-RUAdList** [comment]
How does this relate to the kinotochka.net?

**Comment by mapx-** [comment]
You excluded $media, right ? to be able to see the video in firefox browser.
The same you have to do for chromium browsers ==> using $other keyword.

**Comment by dimisa-RUAdList** [comment]
By default, it is not necessary. It is necessary only if the hand-off Flash plugin (`chrome://plugins/`).

**Comment by gorhill** [comment]
> When can we expect ws://, wss:// (for Firefox)?

uBO can handle `ws://`/`wss://`, it does for Chrome with companion extension.

On Firefox, uBO is only given something like `http://etg.kinotochka.net:8040/304`/`websocket` for that page.

If I bypass the filter `.kinotochka.net^$~object-subrequest,domain=kinotochka.net` to not block the above websocket request, the Network tab in the dev console does not show anything else, there is no `ws://...` in it.

I tried with Firefox/ABP, and there was a `ws://...` in its blockable items list.

So it seems a lot of the confusion here stems from this -- I see no `ws://...` with uBO in the browser's Network pane.

Now I am wondering, is ABP internally remapping the URL `http://etg.kinotochka.net:8040/304` into `ws://etg.kinotochka.net:8040/304`?

I will investigate.

**Comment by mapx-** [comment]
in firefox 49, ABP, I can see:
`ws://etg.kinotochka.net:8040/304`

in firefox (developer edition 50.0a2 (2016-08-31)) not anymore as Lain said above.

W.Palent filed an issue on bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1299766

**Comment by dimisa-RUAdList** [comment]
Ok,
https://hg.adblockplus.org/ruadlist/rev/eb9d1a250c3b#l1.13

**Comment by gorhill** [comment]
I think I see what is going on.

A `shouldLoad` observer sees a websocket request as `ws://...`.

A HTTP obsever sees a websocket as `http://...`.

uBO works mostly as HTTP observer level, while ABP works mostly as `shouldLoad` level.

I will try to see what can be done on uBO's side so that filter list maintainers do not have to worry about these implementation-specific details.

**Comment by mapx-** [comment]
@gorhill, did you read https://github.com/uBlockOrigin/uAssets/issues/123#issuecomment-244053037
?

**Comment by gorhill** [comment]
@mapx- Ok, so that helps making the decision of where I should add a special handling path for websockets in FF/uBO: this will be in its HTTP handler, so that it won't be affected by that issue.

**Comment by gorhill** [comment]
1.9.5b3 is on AMO: `http(s):`-based websocket requests are mapped to `ws(s):`-based ones.
