### ISSUE TITLE
 http://megaurl.in : anti adblock

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#12326]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

` http://megaurl.in/9GZ9A`

### Describe the issue

1. Go to `https://leechpremium.link/download.php`
2. generate a download.
3. click on the download button.
4. This takes you to megaurl link where the adblock is detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80951522/159105587-3bbc1187-2748-4bf9-bdc9-0044a6926122.png)

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 98.XX

### Settings

All default settings

**Comment by Procyon-b** [comment]
It's solved by the annoyance list.
Open ublock's dashboard (click ublock's icon, click the "gears" icon) go to the "Filter lists" tab, scroll down and click on "Annoyances", then check "uBlock filters – Annoyances". Click "Apply changes". Try the links again.
It might not work immediately because of the browser's cache and the fact that it's a redirect.

**Comment by blazesprings** [comment]
Thanks @Procyon-b I have made the changes. Let's see how it goes. Thanks again.
