### ISSUE TITLE
uBlock Origin doesn't work

### ISSUE THREAD

**Issue by jsO17** [uBlockOrigin/uAssets#1340]
Your efforts to develop uBlock Origin are appreciated, but basically uBlock Origin is useless, as it doesn't actually block ads reliably, and I assume you closed this thread because you don't have an answer to fix that issue? Is uBlock Origin still in beta? You should only release software to the public that actually works. A piece of software with a great concept, but that doesn't actually work is just useless. You should stop trying to develop uBlock Origin since you're obviously incompetent, and let a real software developer with talent, who knows what they're doing take over your project instead. Maybe you would be better suited working at something else that you'd be better at. Have a nice day. 

@gorhill Thanks.
@mapx- F*ck. Don't lock.

**Comment by mapx-** [comment]
read here
https://github.com/uBlockOrigin/uAssets/issues/1319#issuecomment-359275176

and stop spamming

**Comment by PhillipeBrosard** [comment]
The link you posted doesn't work, it just says "404 This is not the web page you are looking for.". Do you have a link that works? Do you have a solution to make uBlock Origin work reliably? I'm sorry that you don't seem to want to hear that uBlock Origin doesn't work well, if at all, on most websites, but commenting to let you know that, and asking for help about how to fix issues with uBlock Origin on certain websites, isn't the same thing as spamming. Instead of being rude to people who try to let you know that uBlock Origin doesn't work reliably, why don't you try and fix it instead? Have a nice day. Thanks.
