### ISSUE TITLE
app.plex.tv: breakage

### ISSUE THREAD

**Issue by ElvenYT** [uBlockOrigin/uAssets#14251]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.plex.tv/desktop/`

### Category

breakage

### Describe the issue

Watching Plex with uBlock enabled, skips advertisements just fine but the content itself is entirely white.
For local content without ads, content is still white with uBlock enabled.
Audio still plays but unable to watch.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79991
  cosmetic: 45020
  scriptlet: 17477
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 69080-51, 1d.3h.36m
    easyprivacy: 27478-123, 1d.3h.37m
    plowe-0: 3640-777, 1d.3h.41m
    ublock-abuse: 76-0, 1d.3h.40m
    ublock-badware: 4171-92, 1d.3h.35m
    ublock-filters: 32425-123, 1d.3h.11m
    ublock-privacy: 230-3, 1d.3h.39m
    ublock-unbreak: 1851-42, 1d.3h.10m
    urlhaus-1: 4912-0, 2h.39m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 219 ms (selfie)
  maxAssetCacheWait: 62 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    plex.tv: 7
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    microsoft.com: 2
    sentry.io: 1
    springserve.com: 1
    visualstudio.com: 1
```
</details>

**Comment by gorhill** [comment]
I cannot reproduce using default settings/lists.

Also, on my side I do not see the following servers being used:

    imasdk.googleapis.com
    microsoft.com
    springserve.com
    visualstudio.com

Did you really test with uBO as the only extension/blocker?

**Comment by ElvenYT** [comment]
Yes and when I disable uBlock it loads just fine, Ads and all. I've tried it on two separate computers/chrome installations. I will try a third one tomorrow to confirm.
________________________________

**Comment by ElvenYT** [comment]
![Capture](https://user-images.githubusercontent.com/104946819/183251381-51f71b2f-1c17-4f22-b51b-6b6e37b66b88.PNG)

**Comment by ElvenYT** [comment]
![Untitled](https://user-images.githubusercontent.com/104946819/183251511-36a11781-8d73-4891-82ca-f86b9b30cc73.png)

**Comment by ElvenYT** [comment]
I just installed Firefox, not used it before, added the uBlock Origin add-in and the issue occurs straightaway.
Worth noting I use a Gmail account for my Plex, though it happens when I 'Sign in with Google' or sign in by using my full gmail email.

**Comment by ghajini** [comment]
i can reproduce this `white screen` 
at 

`https://app.plex.tv/desktop/#!/provider/tv.plex.provider.vod/details?key=%2Flibrary%2Fmetadata%2F5dd7817b090320001f6b14ed&context=home%3Ahub.movies.bollywood-gems~1~2`

due to 
`||springserve.com^` in peter lowe's list

This will work
`||assets.springserve.com^$media,domain=app.plex.tv,redirect=noopmp3-0.1s`

**Comment by Antsy4904** [comment]
This is happening again, free shows and channels won't play. I assume I should use this year old issue instead of creating a new one? Even though it's closed? The issue template is not very clear if closed issues should be used.

1. go to the website with no account and no cookies etc. (fresh profile)
1. click a show to watch, either live TV or not.
1. start playing the show.
1. the show doesn't start.

if you disable ublock for this site:
1. start playing a show.
1. you get a pop up asking for consent about ad tracking
1. click `I agree` or `I Do Not Agree`.
1. then the show starts playing.
1. you can now enable ublock again and it works fine.

I haven't tested if any actual ads show up later on or not but ublock is at least preventing free shows from starting.

Other extensions:
None, fresh Firefox profile. default ublock settings.

Config:
<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 98524
 cosmetic: 39485
 scriptlet: 18317
 html: 1028
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35396-97, 1m
  ublock-badware: 7908-1, 1m
  ublock-privacy: 570-0, 1m
  ublock-unbreak: 2170-1, 1m
  ublock-quick-fixes: 235-3, 1m
  easylist: 69996-706, 1m
  easyprivacy: 33265-718, 1m
  urlhaus-1: 5770-0, 1m
  plowe-0: 3724-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 515 ms
 maxAssetCacheWait: 166 ms
popupPanel:
 blocked: 16
 network:
  plex.tv: 8
  googletagmanager.com: 1
  sentry.io: 2
  statsigapi.net: 5
```
</details>

**Comment by mapx-** [comment]
add

`@@||clients.plex.tv/api/$xhr,domain=app.plex.tv`

@ryanbr
