### ISSUE TITLE
bestbuy chat

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1459]
### URL(s) where the issue occurs

`https://www.bestbuy.com/site/misc/expert-service-unbeatable-price/pcmcat345300050032.c?id=pcmcat345300050032`

### Describe the issue

Chat link broken

### Notes

Adding the following fixes it. Double check though.
```
@@analytics-dotcom
@@js/tracking
@@ensighten.com
@@247px
```

**Comment by okiehsch** [comment]
Does
````
@@||assets.bbystatic.com/analytics-dotcom/*$script,domain=bestbuy.com
@@||img.bbystatic.com/BestBuy_US/js/tracking/*$script,domain=bestbuy.com
@@||nexus.ensighten.com/*/Bootstrap.js$script,domain=bestbuy.com
@@||d1af033869koo7.cloudfront.net/*/247px.js$script,domain=bestbuy.com
````
work for you?

**Comment by mapx-** [comment]
working fine, I tested the chat.

@fanboy

**Comment by terrorist96** [comment]
Yep. Thanks guys!

**Comment by gorhill** [comment]
I was looking at this case: <https://www.reddit.com/r/firefox/comments/i1tl04/is_it_normal_for_one_tab_to_use_around_1300_mb_of/>.

Though I couldn't reproduce 1.3GB, I was surprised to find out that uBO caused the page to consume more memory than ABP with EasyPrivacy enabled. Turns out I think the exception filters here are causing, because uBO ends up consuming less than ABP once I disable _"uBlock filters -- Unbreak"_.

Test page: <https://www.bestbuy.com/site/hp-15-6-touch-screen-laptop-intel-core-i5-12gb-memory-256gb-ssd-natural-silver/6413692.p?skuId=6413692>.

Maybe these filters are obsolete -- the chat seems to still work fine after I disable  _"uBlock filters -- Unbreak"_.
