### ISSUE TITLE
linkedin.com: breakage

### ISSUE THREAD

**Issue by oakaigh** [uBlockOrigin/uAssets#14634]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.linkedin.com`

### Describe the issue

Annoying grey boxes.

### Screenshot(s)

`https://www.linkedin.com/feed/`
https://user-images.githubusercontent.com/28533997/188031742-fcb2c51d-d425-4e83-aee6-149e70abb8a1.png

`https://www.linkedin.com/school/*`
https://user-images.githubusercontent.com/28533997/188031748-aa33b76c-f91d-4527-9e78-4a89ac6198fd.png

`https://www.linkedin.com/in/*`
https://user-images.githubusercontent.com/28533997/188031752-39fc7b62-855e-4dd7-86df-6ff2c2293f82.png

### uBlock Origin version

1.43.0

### Browser name and version

Google Chrome Version 103.0.5060.134 (Official Build) (64-bit)

### Settings

Added filter `www.linkedin.com##.ad-banner-container` to remove the annoyance.

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
For some reasons, looks like `##.ad-banner-container` in EL does not apply here:

https://github.com/easylist/easylist/blob/master/easylist/easylist_general_hide.txt#L7998

At first, I thought it's because of

```
#@#.ad-banner
~ananweb.jp##.ad-banner:not([style="height: 5px; width: 5px; position: absolute; top: 0;"]):not(.blocker-tester + .ad-banner):not(:empty)
```

as there's an `.ad-banner` child node inside `.ad-banner-container` but looks like it's not related to the issue.

I can't see any filters hiding, showing `.ad-banner-container` or `ghide` in the log.

![image](https://user-images.githubusercontent.com/66517106/188148498-a62d9c24-4b00-4c8f-af1b-8b5d5aaa5b8e.png)

Any one has any ideas?
