### ISSUE TITLE
rewards.hypixel.net: ads

### ISSUE THREAD

**Issue by 3kh0** [uBlockOrigin/uAssets#14643]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rewards.hypixel.net/claim-reward/85922851`

### Category

ads

### Describe the issue

There is a 30 sec countdown and ublock does not get rid of this

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/58097612/188125819-00040b87-90ab-4f61-a62a-41cb71c821d0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 200350
  cosmetic: 80933
  scriptlet: 30883
  html: 735
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 67273-5453, 1d.23h.24m
    adguard-mobile: 8029-150, 1d.23h.27m
    adguard-spyware: 26676-1115, 1d.23h.25m
    adguard-spyware-url: 738-3, 1d.23h.26m
    block-lan: 43-0, 13d.19h.40m
    curben-phishing: 81940-6, 9h.52m
    curben-pup: 188-0, 9h.54m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33132-53, 1d.13h.47m
    ublock-badware: 4181-0, 1d.23h.31m
    ublock-privacy: 249-0, 9d.6h.14m
    ublock-abuse: 76-0, 9d.6h.13m
    ublock-unbreak: 1859-0, 1d.23h.30m
    easylist: 66748-771, 1d.23h.29m
    easyprivacy: 27446-9484, 1d.23h.28m
    urlhaus-1: 7511-0, 9h.51m
    plowe-0: 3633-3, 9d.21m
    ublock-quick-fixes: 417-0, 9h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2313 ms (selfie)
  maxAssetCacheWait: 554 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    hypixel.net: 2
    cloudflareinsights.com: 2
    doubleclick.net: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    youtube.com: 13
```
</details>

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/188127002-dfcd2344-9ace-4685-ae00-53c28d09cb34.png)

**Comment by 3kh0** [comment]
The link is a rewards thing, you join the mc server, then do a few actions to get a custom link to get rewards

**Comment by MasterKia** [comment]
Can you send an unused custom link?

**Comment by 3kh0** [comment]
I can get a new link in 16h

**Comment by krystian3w** [comment]
Worse if this server side.

**Comment by 3kh0** [comment]
It is just a embedded YouTube video: https://hypixel.net/claim-reward/b71dac69

**Comment by 3kh0** [comment]
@MasterKia @okiehsch 

> It is just a embedded YouTube video: https://hypixel.net/claim-reward/b71dac69

**Comment by krystian3w** [comment]
So can't be speedup to redirect `noop.mp4` - needed test scriptlets arsenal.

**Comment by 3kh0** [comment]
https://hypixel.net/threads/technical-overview-rewards-hypixel-net.4759148/

**Comment by random817** [comment]
Hi, I'm still getting ads on the website.

 Sponsorblock somewhat works for this(since the ad is a 30sec yt video), but the whole video has to be filled with sponsor skips for it to work, which some of the videos don't allow, since "users voted against it". There are like 4 yt videos.

If you have bought a rank on the server, then you get a "skip button". for the videos that sponsorblock works for it's still faster. 

I was hoping that ubo could deal with this better and then I found this and that it's been closed, since the guy with a minecraft account didn't give you a working reward link. I have no problem with doing so. (I have 2 accounts, one with a rank and one without)

But if someone claims it or it expires, then if any of the volunteers have a minecraft account they can just join "mc.hypixel.net", click on the " delivery man" in the lobby and click "the daily reward". 

also tysm for what you do.

for now here are my 2 links: rank: "https://hypixel.net/claim-reward/de79163a"
no rank: "https://hypixel.net/claim-reward/17fae5cb"

**Comment by Baarris5** [comment]
rank: "https://rewards.hypixel.net/claim-reward/3b9acf84"
no rank: "https://rewards.hypixel.net/claim-reward/713fca6f"

**Comment by random817** [comment]
rank: https://rewards.hypixel.net/claim-reward/295ef736
no rank: https://rewards.hypixel.net/claim-reward/ea7743b1

**Comment by random817** [comment]
rank: https://hypixel.net/claim-reward/690306a6
no rank: https://hypixel.net/claim-reward/319b8108

**Comment by random817** [comment]
I talked to the sponsorblock team and they allowed me to add chapters so that you can create a custom filter to skip it. 

add this to "advanced skip options" to sponsorblock:

 // Auto skip chapters that contain the word Hypixel ads
if category == "chapter" and chapter.name *= "Hypixel ads"
Auto Skip
