### ISSUE TITLE
mail.yandex.ru: ads

### ISSUE THREAD

**Issue by Printdie** [uBlockOrigin/uAssets#14700]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.yandex.ru/`

### Category

ads

### Describe the issue

There has been no advertising for a long time. But today she appeared again. The upper plate with advertising.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![изображение](https://user-images.githubusercontent.com/44601670/188600776-359cdd61-fb06-4ce0-9570-7e038c6c82d6.png)

![изображение](https://user-images.githubusercontent.com/44601670/188600798-46592d3b-1131-4282-a2b8-8080ffbd051a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 100088
  cosmetic: 64332
  scriptlet: 18987
  html: 744
listset (total-discarded, last updated): 
  default: 
    user-filters: 13-0, never
    ublock-filters: 33219-32, 1d.20h.39m
    ublock-badware: 4221-1, 13h.50m
    ublock-privacy: 263-0, 8d.19h.25m
    ublock-abuse: 76-0, 8d.19h.24m
    ublock-unbreak: 1860-0, 1d.20h.42m
    ublock-quick-fixes: 424-1, 13h.49m
    easylist: 64894-614, 1d.20h.41m
    easyprivacy: 27457-578, 1d.20h.40m
    urlhaus-1: 7510-0, 13h.48m
    plowe-0: 3634-3, 8d.19h.22m
    RUS-0: 42131-148, 1d.20h.38m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1433 ms (selfie)
  maxAssetCacheWait: 258 ms
popupPanel: 
  blocked: 46
  blockedDetails: 
    yandex.net: 9
    yandex.ru: 37
```
</details>

**Comment by mapx-** [comment]
subscribe RU counters list
https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters

and test again

**Comment by Printdie** [comment]
Yes, it helped. Thanks!

**Comment by MasterKia** [comment]
@mapx- Any reason uBO doesn't ship with RU Counters list out of the box?

**Comment by mapx-** [comment]
idk if @dimisa-RUAdList asked it .. @gorhill

**Comment by dportvine** [comment]
https://github.com/gorhill/uBlock/issues/2241

**Comment by MasterKia** [comment]
> [gorhill/uBlock#2241](https://github.com/gorhill/uBlock/issues/2241)

I see.
Maybe(?) @dimisa-RUAdList could make a uBO.txt with the following context:
```adb
!#include main_list.txt
!#include counters.txt
```

**Comment by mapx-** [comment]
The fact is `RU Counters` should be enabled only manually otherwise the "big guys" will quickly fight back

**Comment by mapx-** [comment]
it's probably ok as it is now, if it were added to uBO (even not enabled  by default) it would draw attention to it

**Comment by dimisa-RUAdList** [comment]
The fact is that Yandex is a problem site. And they very quickly and efficiently bypass any locks contained in the default filters. Therefore, RU AdList and AdGuard are forced to solve this problem with the help of third-party tools. For AdGuard it is [AdGuard Extra](https://github.com/AdguardTeam/AdGuardExtra), for RU AdList it is [RU AdList JS Fixes](https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes).

A couple of years ago, I placed rules in Counters that are similar in their action and purpose to the code contained in the RU AdList JS Fixes script. Thus, users of uBlock Origin got the opportunity to block ads on problem sites without resorting to third-party tools.

But what if you make the Counters filter default in uBlock Origin, the rules from it (for Yandex and other problem sites) will very quickly become useless.

The only option that may be more user-friendly, but also more risky due to bypass, is to add Counters as a default but inactive, like uBlock filters - Annoyances.

However, Raymond does not like combined filters, because in addition to trackers specific to Runet, Counters also contains rules for cleaning urls (removeparam).

But the risk is still quite high and depriving users of a stable lock can be easy.

**Comment by MasterKia** [comment]
> However, Raymond does not like combined filters, because in addition to trackers specific to Runet, Counters _**also contains rules for cleaning urls (removeparam)**_.

And somehow that's a bad thing?

**Comment by dimisa-RUAdList** [comment]
Probably yes. Since the purpose of these rules does not apply to blocking trackers.

**Comment by MasterKia** [comment]
I presumed URL parameters are 99% used for tracking.
