### ISSUE TITLE
9anime.id: breakage

### ISSUE THREAD

**Issue by nk70424** [uBlockOrigin/uAssets#14804]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.id/home`

### Category

breakage - episode lists missing

### Describe the issue

clicks have stopped working, episode list has gone missing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
on the left side of the screen, episode list have stopped showing

![Screenshot 2022-09-13 134947](https://user-images.githubusercontent.com/113443121/189905682-95ec979f-d8fa-4ab7-a418-cec32eb6f768.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 83522
  cosmetic: 41014
  scriptlet: 17885
  html: 746
listset (total-discarded, last updated): 
  default: 
    user-filters: 17-3, never
    ublock-filters: 33406-129, 8h.35m
    ublock-badware: 4239-0, 2h.33m
    ublock-privacy: 273-0, 5d.23h.32m
    ublock-abuse: 76-0, 5d.23h.31m
    ublock-unbreak: 1865-0, 1d.15h.1m
    easylist: 64103-506, 13h
    easyprivacy: 30569-1714, 12h.59m
    urlhaus-1: 7022-0, 2h.31m
    plowe-0: 3671-3, 9d.5h.31m
    ublock-quick-fixes: 438-0, 2h.32m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3805 ms (selfie)
  maxAssetCacheWait: 1902 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    9anime.id: 1
    addthis.com: 1
    amung.us: 1
    bidgear.com: 1
    cloudflare.com: 2
```
</details>

**Comment by Miloliness** [comment]
@nk70424 I had this same issue. For me this was due to an EasyList filter you can find by searching the [raw list](https://easylist.to/easylist/easylist.txt) page for:

/^https?:\/\/.*\/.*(sw[0-9a-z._-]{1,6}|\.notify\.).*/$script,domain= located on line 50685

This filter blocks https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/js/swiper.min.js which is needed for proper functionality.

Creating a URL rule in filter Authoring Mode to Allow (green) the the above URL solved the issue. The rule is as follows:

9anime.id https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/js/swiper.min.js script allow

Maybe you can just copy and paste this in your My rules.

The complete filter is:

/^https?://./.(sw[0-9a-z._-]{1,6}|.notify.).*/$script,domain=123films.cc|123proxy.biz|1337x.to|9anime.id|animekisa.tv|anonfiles.com|aparat.cam|bdupload.asia|bitfly.io|cashurl.in|clicknupload.to|clk.ink|cloudvideo.tv|cocomanhua.com|downloadpirate.com|filmix.co|filmlinks4u.is|flashx.pw|fmovies.taxi|fmovies.world|getlink.pro|hurawatch.at|igg-games.com|indishare.org|katflys.com|linksly.co|megaup.net|mixdrop.ch|mixdrop.co|mp3-convert.org|nutritioninsight.com|ouo.press|pcgamestorrents.com|pouvideo.cc|powvideo.net|powvldeo.cc|primewire.sc|proxyer.org|sendit.cloud|sendspace.com|shrinke.me|shrinkhere.xyz|solarmovie.to|theproxy.ws|uiz.io|up-load.io|upload.ac|uploadever.com|uploadproper.net|uploadrive.com|uplovd.com|upstream.to|userscloud.com|v96-surf.com|vev.red|vidbull.tv|videobin.co|vidlox.me|vidop.icu|vidoza.co|vidoza.net|vidtomp3.com|vidup.io|vumoo.life|watchtvseries.video|xtgem.com|xtits.com|yourbittorrent2.com|ziperto.com|zippyshare.com

**Comment by sugarfreesweetener** [comment]
@ryanbr

**Comment by Miloliness** [comment]
This is no longer a problem after purging and updating filter lists. The filter I had was a day old. 

See [issue 14818](https://github.com/uBlockOrigin/uAssets/issues/14818#issuecomment-1246774072)
