### ISSUE TITLE
9anime.id: breakage

### ISSUE THREAD

**Issue by rsmyst** [uBlockOrigin/uAssets#14818]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.id/watch/k-on.v84/ep-1`

### Category

breakage

### Describe the issue

nothing plays. can't see episode count or any episodes with ublock enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/30620767/190097116-5c2c6a43-1a9e-42e6-8307-07e4de2cad4f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 338613
  cosmetic: 41025
  scriptlet: 17878
  html: 756
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    https://block.energized.pro/porn/formats/hosts.txt: 255547-403, 19h.46m
  default: 
    ublock-filters: 33399-35, 1d.16h.3m
    ublock-badware: 4239-0, 1d.16h.2m
    ublock-privacy: 267-0, 6m
    ublock-abuse: 76-0, 5m
    ublock-unbreak: 1858-0, 1d.16h.1m
    ublock-quick-fixes: 437-0, 15h.24m
    easylist: 64101-615, 1d.16h.4m
    easyprivacy: 30569-1703, 1d.16h.5m
    urlhaus-1: 7022-0, 19h.45m
    plowe-0: 3674-3, 4m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2446 ms (selfie)
  maxAssetCacheWait: 423 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    9anime.id: 2
    addthis.com: 2
    amung.us: 1
    bidgear.com: 4
    cloudflare.com: 2
```
</details>

**Comment by Miloliness** [comment]
@rsmyst I had this same issue. For me this was due to an EasyList filter you can find by searching the [raw list](https://easylist.to/easylist/easylist.txt) page for: 

`/^https?:\/\/.*\/.*(sw[0-9a-z._-]{1,6}|\.notify\.).*/$script,domain=`    located on line 50685

This filter blocks `https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/js/swiper.min.js` which is needed for proper functionality.

Creating a URL rule in filter Authoring Mode to Allow (green) the the above URL solved the issue. The rule is as follows:

`9anime.id https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/js/swiper.min.js script allow `

Maybe you can just copy and paste this in your ***My rules***.

The complete filter is:

/^https?:\/\/.*\/.*(sw[0-9a-z._-]{1,6}|\.notify\.).*/$script,domain=123films.cc|123proxy.biz|1337x.to|9anime.id|animekisa.tv|anonfiles.com|aparat.cam|bdupload.asia|bitfly.io|cashurl.in|clicknupload.to|clk.ink|cloudvideo.tv|cocomanhua.com|downloadpirate.com|filmix.co|filmlinks4u.is|flashx.pw|fmovies.taxi|fmovies.world|getlink.pro|hurawatch.at|igg-games.com|indishare.org|katflys.com|linksly.co|megaup.net|mixdrop.ch|mixdrop.co|mp3-convert.org|nutritioninsight.com|ouo.press|pcgamestorrents.com|pouvideo.cc|powvideo.net|powvldeo.cc|primewire.sc|proxyer.org|sendit.cloud|sendspace.com|shrinke.me|shrinkhere.xyz|solarmovie.to|theproxy.ws|uiz.io|up-load.io|upload.ac|uploadever.com|uploadproper.net|uploadrive.com|uplovd.com|upstream.to|userscloud.com|v96-surf.com|vev.red|vidbull.tv|videobin.co|vidlox.me|vidop.icu|vidoza.co|vidoza.net|vidtomp3.com|vidup.io|vumoo.life|watchtvseries.video|xtgem.com|xtits.com|yourbittorrent2.com|ziperto.com|zippyshare.com

**Comment by mapx-** [comment]
@Miloliness did you purge / update all filter lists ?

**Comment by Miloliness** [comment]
@mapx- I didn't purge all caches, but this started happening after a recent update at least a day ago.

**Comment by mapx-** [comment]
try updating again, no 9anime in that filter right now

**Comment by Miloliness** [comment]
@mapx- Ok so I purged all caches and updated and removed the Allow URL rule and sanitized my Firefox browser. The EasyList filter no longer blocks that URL.
