### ISSUE TITLE
theinquirer.net

### ISSUE THREAD

**Issue by F4z** [uBlockOrigin/uAssets#150]
Google Chrome 53.0.2785.116 m (64-bit)
uBlock Origin 1.9.4

uBlock filters
uBlock filters – Badware risks‎
uBlock filters – Experimental‎
uBlock filters – Privacy‎
uBlock filters – Unbreak‎
Adblock Warning Removal List
Anti-Adblock Killer | Reek
EasyList
Peter Lowe’s Ad server list‎
EasyPrivacy‎
POL: polskie filtry do Adblocka i uBlocka‎

Website detects adblock - `http://www.theinquirer.net/inquirer/review/2471472/iphone-7-review`

![image](https://cloud.githubusercontent.com/assets/11742596/18732999/b11cb17e-8067-11e6-8484-30b7664a2a9d.png)

This rule works for me:
`theinquirer.net##script:inject(r3z-defuser.js)`

**Comment by Tmp341** [comment]
Not here.

**Comment by gorhill** [comment]
> Not here

I could reproduce with default filter lists.

**Comment by Tmp341** [comment]
Works now. o/

**Comment by gotitbro** [comment]
@okiehsch @gorhill Multiple ad requests and ad spaces are created on https://www.theinquirer.net due to numerous whitelist filters in EasyList (added to tackle anti adb).

**SS:** 
http://i.imgur.com/mrNd5ca.png (Ad spaces)
http://i.imgur.com/Ghde851.png (Ad requests)

**Error URL:** 
https://www.theinquirer.net/inquirer/news/2408736/mobile-operators-set-sights-on-google-with-plans-to-block-online-ads

Recommend blocking the ad network requests as uBO filters already deal with this website's anti adb.
