### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1545]
![2018-02-15-elektroda pl - elektronika forum dyskusyjne forum komputerowe forum gsm foru](https://user-images.githubusercontent.com/5884000/36248871-31cfa740-1239-11e8-8978-904728a855c8.png)
`elektroda.pl`

ads

https://github.com/MajkiIT/polish-ads-filter/issues/6230#issuecomment-365861451
> has said "As for the advertisements, I not changed your "squares"."

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.31
Nano Defender 13.32
Chrome 64.0.3282.167

</details>

**Comment by mapx-** [comment]
add as custom filters
```
elektroda.pl##img[src*=".gif"]
elektroda.pl##.visible-sec
elektroda.pl##.tme-description
```

**Comment by garry-ut99** [comment]
Because this is a known fact that there is no ads fixing activity on POL repo tracker since long time as stated in:
`https://github.com/uBlockOrigin/uAssets/issues/21023#issuecomment-1837433286`
I was the only person who on POL repo was fixing actively ads last 2 months via PRs, but not anymore, due to an incident: `https://github.com/uBlockOrigin/uAssets/issues/12214#issuecomment-1930583342` 
,hence POL repo is now back to it's "very low ads fixing activity state" again.

**Comment by JobcenterTycoon** [comment]
I get a soft anti adblock + a ad mentioned in https://github.com/uBlockOrigin/uAssets/issues/1545#issuecomment-1934145392

```
elektroda.pl#@#+js(set, loadElement, noopFunc)
elektroda.pl##div:has(> .top-box-caption + a[href*="?utm_"])
```

**Comment by garry-ut99** [comment]
Yes, your filters works fine for both anti-adblock and ads.
( also by the way here is an old anti-adblock thread: https://github.com/uBlockOrigin/uAssets/issues/13966 )

**Comment by garry-ut99** [comment]
I missed some ads: 
`https://www.elektroda.pl/section117.html`
`https://www.elektroda.pl/section77.html`

![ss_33](https://github.com/uBlockOrigin/uAssets/assets/72945564/ec00c659-4faa-424a-9fe1-592a8ee31375)

**Comment by garry-ut99** [comment]
The ads from yesterday are still hidden, but I've noticed ads (3x) on a new different link , example : 
`https://www.elektroda.pl/rtvforum/topic4034617.html`
(I don't know whether I missed them the last time or they have appeared recently)

@JobcenterTycoon

**Comment by gulson-dev** [comment]
I am writing to bring to your attention a matter regarding a current filtering rule which is inadvertently affecting content visibility on our platform. Specifically, the rule in question is:

`elektroda.pl##*:has(> a[href*="?utm_"])`

As a result of this rule's implementation, there has been an unintended consequence where entire posts are being hidden. An example of this can be observed at the following URL:
[https://www.elektroda.pl/rtvforum/topic4035645.html](https://www.elektroda.pl/rtvforum/topic4035645.html)

The issue arises when users include links containing the "?utm_" parameter within their posts. Upon doing so, all accompanying text becomes invisible, as exemplified in the link provided.

Additionally, I would like to address the contributions from the user [garry-ut99](https://github.com/garry-ut99). It has been noted that this individual has a history of proposing changes that have previously led to malfunctions, specifically affecting our menu and post features.

I recommend that we review the implications of the aforementioned filtering rule and assess the contributions of the user in question to prevent further disruptions to our website's functionality.

Thank you for your attention to this matter. I look forward to your prompt response and am available to assist with any further information or discussion as needed.

**Comment by garry-ut99** [comment]
_Beware - this guy gulson is a troll, he made a drama on POL tracker, and now he has come to make same drama on uAssets, it's not me who has started the off-topic here, and I'm just repying to this troll's off-topic, because he publicly slanders and defames me here, most likely our comments will be hidden by moderators of uAssets_

> gulson-dev : has a history of proposing changes that have previously led to malfunctions, he has a history of resurrecting old issues and attempting to sway the decisions of filter developers to implement changes that could negatively impact the website's functionality, activity that seems to be aimed at disrupting the functionality of our platform.

What history? Where? Show evidence or go troll elsewhere, I added a single filter for elektroda, and you made a drama on POL tracker.

> gulson-dev : garry-ut99 actions appear to be motivated by a vendetta against Elektroda rather than any concern for user experience.

So funny, go troll elsewhere, because it's perfectly the opposite, it were your actions motivated by vendetta, not mine.

> gulson-dev : Garry-ut99's interactions with the team at polish-filters, who have previously engaged with him, have left them dissatisfied due to his confrontational behavior.

Go troll elsewhere, the only confrontational behavior was your hardcore trolling towards me on POL tracker just because I added a filter you didn't like. 


I added a filter for elektroda which didn't break anything on your site, and you didn't like it because it was too broad and you were afraid it can break something on your site in the future, I understood peacefully your concerns and told you to ask the main POL admin about it and that the main POL admin will most likely agree to replace the filter and your problem will be gone.

But you instead of just doing what advised, started your drama, and begun to troll, harass and attack me personally, just because I didn't replace your filter immediately, you spammed 2 separate threads on POL tracker with your comments full of personal insults/trolling towards me, then you intentionally broke your website and then you were lying and blamed the filter for the breakage, then you even blocked me on github for no reason, thus I couldn't reply anymore to you in your thread.

You were acting so hostile, like a furious psycho,  and trolling so badly, that apart of defending myself, I was just waiting for the main POL admin to come and calm you down or even ban you, but unfortunately when the main POL admin came back along with the other POL annoyance filters admin, they both licked and cleaned your arsehole, joined you and took your side, and then trolled me 3vs1, then hid comments, locked threads. That was very unnice, and that's why I no longer contribute to POL repo, because it's full of troll-admins, I was the only person who for 2 last months was keeping POL repo alive and who was fixing tons of ads and offloading uAssets developers, now due to your and 2 POl admins hostile and disrespectful actons, POL repo is back to it's "very low ads fixing activity state", and PL users will switch back to report many PL sites to uAssets again, thanks to individuals like you, and admins of POL repo.

**Comment by freezer2022** [comment]
3 x AD again, like in: https://github.com/MajkiIT/polish-ads-filter/issues/22029. 
This example link: `https://www.elektroda.pl/rtvforum/topic4032112.html`.

**Comment by freezer2022** [comment]
Hey, yes  - the fix works fine.

<hr>

However, I've also found right now another ads but different - annoying sponsored yellow ads (full screenshoot [HERE](https://github.com/user-attachments/assets/2bec3074-8daa-4a50-af17-92956c4b4217)):

![Image](https://github.com/user-attachments/assets/028af092-acbd-48e5-a297-f91144cd652c)

It appears in the same subforum, in many other threads, for example:
`https://www.elektroda.pl/rtvforum/topic1656300.html`

A single ad per page, it appears not always at the top, but sometimes also in the middle or at the bottom instead.

**Comment by freezer2022** [comment]
He has reacted quickly, all ads I reported in my two last comments and you fixed recently are back again today (at the same links). Altogether with an anti-adblock message:![Image](https://github.com/user-attachments/assets/a705113f-c1d4-4172-99d3-af89e002bd0e)

**Comment by gulson-dev** [comment]
Our website is able to remain completely free for all users because of the revenue generated through our advertisements. These ads are our only source of income that allows us to:
- Maintain our servers and infrastructure
- Create new content
- Pay our dedicated team
- Continue providing our services without implementing a paywall.

Creating custom rules to block additional ad elements beyond what standard ad blockers target can potentially break our page functionality. While we respect your right to control your browsing experience, we'd like to gently request that you consider allowing our small advertisements to display related to the topic of the portal.

The small text links you're currently blocking have minimal impact on your browsing experience but make a significant difference to our sustainability. Without this crucial revenue, we may eventually face difficult decisions.

Thank you for your understanding.

**Comment by freezer2022** [comment]
You're repeating the same fairy tale like in previous issue on POL tracker under your other nick "gulson":
- https://github.com/MajkiIT/polish-ads-filter/issues/13991

<br>

And I'm basically repeating answers from #13991:

> gulson-dev: beyond what standard ad blockers target

Not beyond, other adblockers target them too (if reported of course).

> gulson-dev: our small advertisements

The opposite: 3x big ads on a single forum page, full screen width and 1/3 of screen high each of them, in invasive placement - between comments, which causes hard to read forum discussion.

> gulson-dev: The small text links you're currently blocking have minimal impact on your browsing experience

The opposite - they have big impact: they are yellow, eyes invasive, full screen width, annoying and distracting.

**Comment by freezer2022** [comment]
> https://github.com/uBlockOrigin/uAssets/issues/1545#issuecomment-2866529968 ==> https://github.com/uBlockOrigin/uAssets/commit/ebae37ed857a3ab75adf5076db215d35c10faf2b

They yellow ads are back again, same links.

**Comment by freezer2022** [comment]
The 3 x AD again, like in https://github.com/uBlockOrigin/uAssets/issues/1545#issuecomment-2850935106, but in different links, for example: `https://www.elektroda.pl/rtvforum/topic4119141.html`

**Comment by freezer2022** [comment]
Both: yellow ADS https://github.com/uBlockOrigin/uAssets/issues/1545#issuecomment-2866529968 + 3 x AD https://github.com/uBlockOrigin/uAssets/issues/1545#issuecomment-2891830967 are back again.

**Comment by freezer2022** [comment]
The 3 x AD again, in all the links from both:
- https://github.com/uBlockOrigin/uAssets/issues/1545#issuecomment-1934145392
- https://github.com/uBlockOrigin/uAssets/issues/1545#issuecomment-2891830967

**Comment by playonevideo** [comment]
Detection, again:

<details>

<img width="1280" height="2772" alt="Image" src="https://github.com/user-attachments/assets/cf4ba56a-5072-4044-a07e-9a0f8f56a22b" />

</details>

**Comment by stephenhawk8054** [comment]
Are there any breakages or it's just the banner?

**Comment by playonevideo** [comment]
From what I notice, there are no breakages, just the banner.

**Comment by krystian3w** [comment]
But as far as I remember, that warning doesn't appear once the ads load, so maybe it's just a clever placeholder.

**Comment by krystian3w** [comment]
@stephenhawk8054 worth reset padding: `https://www.elektroda.pl/rtvforum/topic3522967.html`

<details>
<summary>Details</summary>

<img width="1859" height="943" alt="Image" src="https://github.com/user-attachments/assets/38d31c77-e6dc-4819-b9af-a23ee51f3fc3" />

</details>

?
