### ISSUE TITLE
anwb.nl : optimizely blocked

### ISSUE THREAD

**Issue by moonbyt3** [uBlockOrigin/uAssets#15786]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.anwb.nl/kampioenen/inspiratieborden/rick-laura/wildkamperen-zweden`
`https://www.anwb.nl/kampioenen/shorts/jasmijn-vd-zwaan/fietstocht-waddeneilanden`

### Describe the issue

The designer told me she can't see the pages I'd developed. She has uBlock Origin 1.45.2 and it seems like the extension is blocking Optimizely script. ANWB website doesn't show any ads but we are using Optimizely to inject static HTML content to our page. Currently uBlock prevents a page from rendering the whole content, so users can only see the header and footer which are not being injected with Optimizely.

Can you add ANWB website to the whitelist please?

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24306614/203739563-236970c6-ea99-4bcf-95d9-f4e4064f9800.png)

### uBlock Origin version

1.45.2

### Browser name and version

Google Chrome 107.0.5304.110 (Official Build) (64-bit)

### Settings

/

**Comment by krystian3w** [comment]
Blocked in many places:

https://github.com/uBlockOrigin/uAssets/blob/9cacf21669ac2d7967d2f97fd8a8a61bcceb8089/thirdparties/pgl.yoyo.org/as/serverlist#L2556 - overrided by:

https://github.com/uBlockOrigin/uAssets/blob/e29ed061ca9dc418f5e06b67f782a4545b2a36d2/filters/unbreak.txt#L810-L813

And at end in EP: https://github.com/easylist/easylist/blob/247f990f4061ade43fa80dcb32576d5bf337f416/easyprivacy/easyprivacy_trackingservers.txt#L1829

The chances of fixing some are, EP and uBO unbreak have some permissions so that the webmaster does not rewrite the site asap.

**Comment by moonbyt3** [comment]
Thanks for solving our issue guys it's working now, you rock! ❤️
