### ISSUE TITLE
mobile.de: breakage

### ISSUE THREAD

**Issue by andreewmat** [uBlockOrigin/uAssets#15985]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://suchen.mobile.de/fahrzeuge/search.html?c=SportsCar&dam=0&ft=PETROL&isSearchRequest=true&ref=srp&refId=388d4747-5ce8-5b63-5d04-3a0591012352&s=Car&sb=rel&tr=MANUAL_GEAR&vc=Car`

### Describe the issue

I get an error when I try to see some cars from this site. 

This is how I have done to see the error: 
- I opened the website, then selected the yellow button with "results".
- After that, on the left side there are filters, I selected some filters: fuel, transmission and vehicle type.
- Then, this time, I see the error from the first ad, below the "Top" ad result. Other times, the error is on other ad, not the first one.
- After that if I open other ad, I see this error everywhere.

### Screenshot(s)

Error:
![image](https://user-images.githubusercontent.com/79897301/206928219-32eb6b8f-114a-4d44-8247-b7acb501d999.png)

### uBlock Origin version

1.45.2

### Browser name and version

Firefox 107.0.1

### Settings

Default settings

**Comment by mapx-** [comment]
I was able to reproduce the issue only once. I'm not sure if could be a site issue !?

test

`@@||logx.optimizely.com/v1/events$xhr,domain=suchen.mobile.de`

**Comment by mapx-** [comment]
@ryanbr if you can reproduce the issue

**Comment by andreewmat** [comment]
> I was able to reproduce the issue only once. I'm not sure if could be a site issue !?
> 
> test
> 
> `@@||logx.optimizely.com/v1/events$xhr,domain=suchen.mobile.de`

The filter you mentioned doesn't change the issue. I tried to purge all caches but no luck. I am note sure if it's a site issue or not. Please let me know if you need other informations.

**Comment by mapx-** [comment]
Are you sure the issue does not happen disabling uBO ?

**Comment by MrCr00k** [comment]
The issue is still there.
I've been running into it constantly for the last year or so.
Currently FF 117.0.1 (64-bit) and uBlock Origin 1.52.0

Doing cookies cleanup or even Fifrefox refresh (did it twice and then added uBlock Origin again) is not solving the problem for me. I'm starting to get the same error as reporter after several minutes of navigation on the mobile.de site again.
The only way to avoid - disable uBlock Origin completely.

**Comment by mapx-** [comment]
same behaviour as above in my other comments: first time I can reproduce the issue, after that switching uBO off / on + clearing storage + cookies on site => now is working

**Comment by MrCr00k** [comment]
Yes, it's working... for some time
and then, after several searches/opening results in new tabs it stops...
I'll try to reproduce on completely fresh/new Notebook/Win11/FF install next week

**Comment by MrCr00k** [comment]
Ok, so just to recap after numerous experiments:
The issue is not related to uBlock.
The site itself has bad handling of its own cookies.
So if you don't accept all cookies (press **Accept/Einverstanden**) on your first visit and go **Privacy Settings > Save and proceed** way instead, then eventually the site breaks after a while.
