### ISSUE TITLE
tommy.com: detection 

### ISSUE THREAD

**Issue by afkvido** [uBlockOrigin/uAssets#16071]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://usa.tommy.com/`

### Describe the issue

To reproduce:
- With uBO, go to tommy.com
- Browse around for a little while, usually 10 to 15 pages
- You'll get (see screenshot) a message asking you to verify that you're human, and also disable your adblocker, ex. uBO.

### Screenshot(s)

https://user-images.githubusercontent.com/69060894/208548858-3beb9920-1025-4208-b624-a12e9a01217e.png

After holding the button:

https://user-images.githubusercontent.com/69060894/208549047-a2ad7afb-b411-420d-99ea-eeafc8c75f13.png

### uBlock Origin version

1.45.2

### Browser name and version

Mozilla Firefox 108.0.1

### Settings

None. I'm just using the default settings.

### Notes

No im not using noscript, and turning off uBO fixes the problem

**Comment by mapx-** [comment]
After holding the button it's all ok on my end

**Comment by afkvido** [comment]
@mapx- That doesn't change the fact that you can still be detected and annoyed unless you disable uBO.

**Comment by stephenhawk8054** [comment]
That page is caused by fast continuous activities that the system thinks it's caused by bots, even when I don't use uBO. Same thing happens with pages like crunchbase

This is an example when I open a few pages in new tabs while not using any blockers

![image](https://user-images.githubusercontent.com/66517106/209031921-68b9920e-eef8-4294-acd9-8398b23a5cfb.png)

The bottom message appears when its `px-client` connection is blocked, and there _**might**_ be higher chances to get that page when blocking those connections but there's no reliable way to have reproducible steps for both enabling and disabling uBO cases.

You can test if these filters reduce the chance of getting that page or not:

```adb
@@||collector-*.px-client.net/b/g$xhr,domain=tommy.com
@@||tommy.com/*/xhr/b/c/beacon$ping,1p
@@||tommy.com^$elemhide
```
