### ISSUE TITLE
mdn.lol: detection

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#16345]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mdn.lol/2022/08/22/should-you-invest-into-forex/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 100627
  cosmetic: 59689
  scriptlet: 18040
  html: 871
listset (total-discarded, last-updated): 
  default: 
    user-filters: 5-0, never
    ublock-filters: 32524-85, 1d.15h.54m
    ublock-badware: 4298-0, 1d.15h.54m
    ublock-privacy: 305-0, 5d.15h.59m
    ublock-abuse: 77-0, 5d.15h.59m
    ublock-unbreak: 1940-2, 1d.15h.54m
    ublock-quick-fixes: 464-0, 22h.47m
    easylist: 61755-637, 5d.15h.59m
    easyprivacy: 30894-1849, 5d.15h.59m
    urlhaus-1: 6868-0, 22h.47m
    plowe-0: 3668-2, 5d.15h.59m
    RUS-0: 39211-19, 1d.11h.54m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1784 ms (selfie)
  maxAssetCacheWait: 483 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    d3u598arehftfk.cloudfront.net: 1
    doubleclick.net: 1
    google-analytics.com: 2
    googletagmanager.com: 2
    themoneytizer.com: 2
    wpadmngr.com: 1
```
</details>

**Comment by garry-ut99** [comment]
Unable to reproduce, probably fixed here: https://github.com/uBlockOrigin/uAssets/issues/16207#issuecomment-1383084292, try updating filters.

**Comment by ghajini** [comment]
test link from https://github.com/uBlockOrigin/uAssets/issues/15156#issuecomment-1267939013
`clks.pro/Ojot` => `mdn.lol`

**Comment by garry-ut99** [comment]
Weird, visiting directly a link the OP provided doesn't trigger an anti-adblock, but visiting through `clks.pro/Ojot` does, the link is different but I guess even if it was the same one, an anti-adblock would still appear as well, as it seems an anti-adblock is triggered when being redirected but not when visiting the link directly or the anti-adblock is triggered only on the first visit as the links are randomly generated.

**Comment by stephenhawk8054** [comment]
@Lahiru2002 Next time, if you can, please post original URL that redirects to `mdn.lol` page.

**Comment by garry-ut99** [comment]
It's fixed for Opera (so I assume it's fixed for Chrome as well).

But it's still not fixed for Firefox (or fixed only partially), still can reproduce on Firefox, visiting links provided here: 
   - a) https://github.com/uBlockOrigin/uAssets/issues/16345#issuecomment-1383175687 
   - or here b) https://github.com/uBlockOrigin/uAssets/issues/15278#issuecomment-1279736484 / 
   https://github.com/uBlockOrigin/uAssets/issues/15278#issuecomment-1279742182 (same link I know)

Steps to reproduce:
- 1 clear Firefox cookies & cache (for all sites)
- 2 visit whatever link you want (a or b) and notice the anti-adblock will not appear
- 3 visit whatever link you want (a or b) again as many times as you want and notice the anti-adblock will appear every time unless you repeat step 1

I investigated and found out that the anti-adblock message is caused by this script, and most plikely because the script is located early at the bottom of the page, none of the following scriplets work due to race condition:
- `mdn.lol##+js(aopr, adBlockEnabled)`
- `mdn.lol##+js(acs, document.write, adBlockEnabled)`
- `mdn.lol##+js(set, adBlockEnabled, false)`

But each of these works (separately): 
- `mdn.lol##^script:has-text(adBlockEnabled)`
- `@@||js.wpadmngr.com/static/adManager.js$xhr,domain=mdn.lol` (I don't say to add this nasty solution, just an example)

```js
var canRunAds = true;
async function detecf274162071bcb5d0b56206569fe0c56b8e737523f254867e0ba81413d8031547() {
    let adBlockEnabled = false
    const myAdUrl = 'https://js.wpadmngr.com/static/adManager.js'
    try {
        await fetch(new Request(myAdUrl)).catch(_ => adBlockEnabled = true)
    } catch (e) {
        adBlockEnabled = true
    } finally {
        if (adBlockEnabled) {
            document.write("<h1>Please disable adblock.</h1>")
        } else {}
    }
}
detecf274162071bcb5d0b56206569fe0c56b8e737523f254867e0ba81413d8031547();
```

**Comment by garry-ut99** [comment]
- this is insane, over the past few hours I have been able to reproduce it every time - doing step 3 always resulted in anti-adblock appearing, even if repeating 20 times in a row.

- I didn't touch anything since then, and have been trying just right now again step 3 20 times and couldn't reproduce a single time, until it finally appeared one time only

- it's randomness makes it hard to reproduce (race condition?):
   - sometimes always reproduced 20 times in a row
   - sometimes never reproduced: 0 out of 20 tries
   - sometimes 1 time per/after 20 tries

- to make it clear, by "visit" I mean **each** time paste the link **a** or **b** into a browser address bar
- however there is an alternative method for step 3 which in comparision to the main method, **always** works, so if you can't reproduce with the main method, use the alternative method for step 3: **refresh (F5)**
