### ISSUE TITLE
[nsfw] neko-sama.fr: popups

### ISSUE THREAD

**Issue by skunaed** [uBlockOrigin/uAssets#16653]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.neko-sama.fr/`

### Category

popups

### Description

even with the popups filter enabled, the site opens a new tab from a nsfw website everytime you try to play a video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 103169
  cosmetic: 47165
  scriptlet: 17025
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://hentaiforce.net/: 0-0, never
  default: 
    user-filters: 1-0, never
    FRA-0: 30002-28, 3d.6h.17m
    easylist: 61071-111, 2d.8h.40m
    easyprivacy: 30923-1495, 2d.8h.39m
    plowe-0: 3667-924, 2h.33m
    ublock-abuse: 77-1, 1d.3h.53m
    ublock-badware: 4205-140, 3d.6h.20m
    ublock-filters: 31920-247, 3d.6h.19m
    ublock-privacy: 260-1, 1d.3h.52m
    ublock-quick-fixes: 428-20, 2h.32m
    ublock-unbreak: 1868-46, 3d.6h.18m
    urlhaus-1: 6657-0, 2h.31m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 257 ms (selfie)
  maxAssetCacheWait: 636 ms
popupPanel: 
  blocked: 3
  no-popups: true
  blockedDetails: 
    cloudflareinsights.com: 1
    occurclaimed.com: 1
    rxeosevsso.com: 1
```
</details>

**Comment by electrolove77** [comment]
I've been using necko-sama for a long time without any trouble, but i was about to create a report for the exact same reason described.
I'm a lambda user of uBlock with firefox browser, and i first had several nsfw pop-up on my smartphone last week. I thought it was because of this device as i never used necko-sama.fr onmy phone before, but then it happened on my computer too.
On the PC, i now always have to click 3 times on the play button before it starts reading the video, after the fourth hit. Sometimes, all of the three pop-up are blocked, and the tab is closed by itself as quick as it appears, sometimes only the first two tabs disapear themselves and the third one is, sometimes opened with a uBlock message, sometimes opened in its full content. And a few times of these, but on a "kids" japanese animes streaming site, this is adult explicit content (in this case adress = www.xvidzz.com )... so i had to warn my 13 years old daughter 👎 !

Hope my comment can help someone able to fix this, despite this issue has been closed two weeks ago...
