### ISSUE TITLE
hipsonyc.com: popups / popunders

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#16699]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hipsonyc.com/2023/02/how-to-solve-your-tax-debt-problems.html#?o=aeeb9d54024a8e13269d5c36265ddada5d66b1f3abe0dbe65df40f87307de6cf6ff8d8f4a1a6f39287fc5c076315345a08d2daf2d4cc161a`

### Category

popups

### Description

Porn ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 109
filterset (summary): 
  network: 85475
  cosmetic: 28518
  scriptlet: 16985
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32868-307, 1d.3h.1m
    ublock-badware: 4316-5, 1d.3h
    ublock-privacy: 310-1, 4d.2h.33m
    ublock-abuse: 77-0, 3d.23h.8m
    ublock-unbreak: 1890-0, 9h.13m
    ublock-quick-fixes: 447-2, 2h.2m
    adguard-mobile: 8789-34, 2h.4m
    easylist: 61379-17547, 1d.3h.3m
    easyprivacy: 30933-1771, 1d.3h.2m
    urlhaus-1: 7170-0, 2h.3m
    plowe-0: 3668-138, 3d.6h.34m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 633 ms (selfie)
  maxAssetCacheWait: 272 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
The button at the bottom uses `window.open` to open the real url at new tab and `window.location.href` to load ads site at current tab

```js
gotolink.on("click", function() {
	var realurl = aesCrypto.decrypt(convertstr($.urlParam('o')), convertstr('root'));
	window.open(realurl, '_blank');
	window.location.href = 'https://buoydeparturediscontent.com/eg2w1n48z?key=2c570799211f686774d4d254bcd0be0e'
});
```

I don't think we have any solutions for it at the moment except blocking that domain (which is already blocked).

---

@gorhill Recently I see more sites using combo `open` to load real url and `location.href` to load ads site (opposite with the popup we usually encounter). I cannot figure out any possible solutions to stop the ads site loading (since the site can rotate to new ads domains). Do you have any ideas about this?

Similar issues:

- https://github.com/uBlockOrigin/uAssets/issues/16679#issuecomment-1423820428
- https://github.com/uBlockOrigin/uAssets/issues/16658#issuecomment-1420681983

Searching on internet gives me that it's quite difficult to handle `location.href`, so I'm not sure what we can do about this. Except could there be any ways to remove a string from a response? In the above case, for example `window\.location\.href.+`. It might be similar to adguard's `$replace` but just remove as we don't need to add new information.

**Comment by mapx-** [comment]
some .. indirect solutions:

`*$popunder,domain=theforyou.in`
or
`buoydeparturediscontent.com##+js(window-close-if, /^/)`

**Comment by ghajini** [comment]
sites can rotate to new adservers (adsterra)& in that case `window-close-if` will not work

**Comment by stephenhawk8054** [comment]
Yeah I have tried `+js(window-close-if, /^/)` with previous issues but looks like it's not compatible well if the domain (`buoydeparturediscontent.com`) is blocked, but I forgot about `popunder`, tks 👍 We can set it as a temp solution.

---

Just realized that `buoydeparturediscontent.com` is not blocked yet.

**Comment by garry-ut99** [comment]
> `popunder`

Keep in mind: https://github.com/uBlockOrigin/uBlock-issues/issues/1393

**Comment by mapx-** [comment]
`replace` scriptlet

add `http://axistrivia.altervista.org/list/_r15.js` to `userResourcesLocation`

filter:
`hipsonyc.com##+js(repl, /click.*_blank.*location\.href/, window.location.href = 'https, window.location.href)`

param1 (regex): matching a specific inline script
param2 which part
param3 what to replace
