### ISSUE TITLE
onedrive.live.com: privacy

### ISSUE THREAD

**Issue by Banaanae** [uBlockOrigin/uAssets#17041]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://onedrive.live.com/edit.aspx`

### Category

privacy

### Description

`https://powerpoint-telemetry.officeapps.live.com` can connect without being blocked by the filter
I tried on other office apps but could not replicate (probably need to spend x hours before it starts collecting telemetry)
However going to above website redirects you to office.com but replacing powerpoint with something else (eg `https://fakeofficeapp-telemetry.officeapps.live.com`) gives a could not connect to server, using this I found word, onenote and excel telemetry also exists.

Could be fixed with `(wildcard)-telemetry.officeapps.live.com`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/83927639/222935219-a4758043-b496-4583-b081-7faef9a49026.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 84988
  cosmetic: 38879
  scriptlet: 17046
  html: 890
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32858-86, 15h.5m
    ublock-badware: 4615-0, 1h.26m
    ublock-privacy: 323-0, 3d.8h.32m
    ublock-abuse: 79-0, 5d.17h.16m
    ublock-unbreak: 1915-16, 1h.24m
    ublock-quick-fixes: 339-0, 23h.30m
    easylist: 62967-517, 5d.17h.18m
    easyprivacy: 30976-1782, 5d.17h.17m
    urlhaus-1: 6555-0, 23h.29m
    plowe-0: 3753-2, 1d.10h.6m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1762 ms
  maxAssetCacheWait: 1030 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    azure.com: 2
    b-msedge.net: 3
    microsoft.com: 19
    office.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Currently we are having `$ping,3p` in EP. I wonder if it's good to block `$ping` in 1st-party in general. Does anyone know any issues in the past with blocking it in `1p`?

**Comment by mapx-** [comment]
This list contains 15 `telemetry.officeapps.live.com` entries:

https://badmojr.gitlab.io/1hosts/Xtra/dnsmasq.conf

**Comment by Yuki2718** [comment]
> Currently we are having `$ping,3p` in EP. I wonder if it's good to block `$ping` in 1st-party in general. Does anyone know any issues in the past with blocking it in `1p`?

In fact the rule was originally `$ping` but adjusted by a few troubles.

**Comment by garry-ut99** [comment]
They hide behind cname: 

```
nslookup word-telemetry.officeapps.live.com
Non-authoritative answer:
Name:   pgtus1-word-telemetry-vip.officeapps.live.com
Address:  52.108.78.30
Aliases:  word-telemetry.officeapps.live.com
          word-telemetry.wac.trafficmanager.net
```

**Comment by Yuki2718** [comment]
It turned out uBO takes `||*-telemetry.officeapps.live.com` as a generic pattern-based rule than a domain rule. So I added `$pinig,xhr` for additional safety.

**Comment by chrisbro-MSFT** [comment]
Hi @Yuki2718 - I'm an engineer at Microsoft.  These telemetry endpoints in question are only used by the Office Online application that the user is actively using.  For example, if you click on a PowerPoint file on onedrive.live.com, it will open PowerPoint Online so you can view and edit the file.  While in this application, and only while in the application, it will communicate to the *telemetry.officeapps.live.com endpoint for that application.  The telemetry is primarily used to diagnose client-side issues like crashes, failure to load javascript files, and similar problems with the applications.

I see that the EasyPrivacy policy does indicate that it blocks telemetry, and it does have a category for 1st-party tracking.  If blocking an application's own telemetry on its own site is the goal then that's fine, keep it on the blocklist.  If telemetry for the application/webpage isn't the goal then I'd like to ask that this blocklist entry be reconsidered, as it's never used from any other site, just from within the Office Online application being used by the user.  (For context, I was trying to investigate my own crashes and realized that they were invisible because I was blocking my own telemetry!)

Thanks!

**Comment by Yuki2718** [comment]
@chrisbro-MSFT Hi, we do not decide solely by partiness, rather decide on the basis whether it sends data unnecessary to user or not, and whether blocking it causes trouble to user, in short if it is beneficial to user or not.
