### ISSUE TITLE
toodaloo.com: breakage

### ISSUE THREAD

**Issue by clarkl17** [uBlockOrigin/uAssets#17109]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://toodaloo.com/products/custom-bundle-4-bags`

### Category

breakage

### Description

When I click the 'Add to Cart' button for the Custom Bundle, it does not add anything to the cart.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 85410
  cosmetic: 21952
  scriptlet: 17059
  html: 894
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32883-266, 3d.6h.57m
    ublock-badware: 4644-0, 3d.6h.7m
    ublock-privacy: 332-1, 8d.4h.24m
    ublock-abuse: 79-0, 8d.4h.22m
    ublock-unbreak: 1915-12, 3d.6h.20m
    easylist: 63428-17405, 4d.17h.36m
    easyprivacy: 31014-1767, 4d.17h.35m
    urlhaus-1: 6523-0, 1d.2h.35m
    plowe-0: 3750-2, 7d.18h.28m
    ublock-quick-fixes: 372-0, 1d.2h.34m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1375 ms (selfie)
  maxAssetCacheWait: 430 ms
popupPanel: 
  blocked: 30
  blockedDetails: 
    bing.com: 1
    convertexperiments.com: 1
    djnf6e5yyirys.cloudfront.net: 1
    doubleclick.net: 2
    dttrk.com: 1
    facebook.net: 2
    google-analytics.com: 1
    google.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 4
    hotjar.com: 1
    impactcdn.com: 1
    rebuyengine.com: 2
    sentry.io: 2
    shopify.com: 3
    shopifysvc.com: 1
    skimresources.com: 1
    tiktok.com: 2
    youtube.com: 2
```
</details>

**Comment by gorhill** [comment]
It also does not work without uBO.

**Comment by garry-ut99** [comment]
>  but **it works with uBO once you select four items.**

Yes, working fine with at least 4 items:
- OP either didn't seclect at least 4 itmes
- or OP needs to update his filter lists

>  * [x]  I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

Not true.

>  * [x]  I did not answer truthfully to **ALL** the above checkpoints.

True.

**Comment by gorhill** [comment]
> thats the opposite of what most websites do.

It's to detect people who just check the boxes without reading and performing the required steps (they exist to root out issues outside uBO) -- which appears is what you have done. For instances, all your lists show as being days old in troubleshooting information.  I also asked you to mind your own filters/rules, and you provided no feedback on this.

Since we can't reproduce, you will have to investigate more on your side.

**Comment by clarkl17** [comment]
I looked at my filters and my rules last night when I submitted this issue, and they are not the problem.
Today, I turned off the DuckDuckGo extension and tried again, and the website worked. I did not realize that the extension was a 'similarly-purposed blocker'. In my defense, linking to a twitter thread is not a great way to explain what is and is not a 'similarly-purposed blocker'.

**Comment by garry-ut99** [comment]
> I didn't see the word 'not' in there, because thats the opposite of what most websites do.

Strange / odd excuse, because half of the checkpoints contain 'not' as well : 4, 5, 6, 7 and 9, and you overlooked only the last one...

> I followed the instructions for purging the caches.

Log says otherwise, but possible other explanations: maybe you updated lists while reading the form's checkpoint, means after the troubleshooting information has been already generated or you updated filter lists on a different browser / browser profile (btw maybe good to add: "or I have verified that my lists are updated").

> linking to a twitter thread is not a great way to explain what is and is not a 'similarly-purposed blocker'.

(Quote from [LINK](https://twitter.com/ammr/status/1031692444511948802)): "Don't blame others as an excuse for your not working hard enough" 
Even before reading the Twitter link, an user on mozilla add-ons site, is already provided with an information that the both extensions are the similiar purpose:
1 They belong to the same "Privacy & Security" category on mozilla addons site, listed nearby each other: [LINK](https://addons.mozilla.org/en-US/firefox/extensions/category/privacy-security/)
2 Their descriptions say that one of their main purposes is to block trackers to protect privacy:
 "uBO blocks ads, trackers," - [LINK](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) "Duck is privacy protection for your browser: tracker blocking," [LINK](https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/ )
