### ISSUE TITLE
lightnovelpub.com: ads

### ISSUE THREAD

**Issue by Tarzan9348** [uBlockOrigin/uAssets#17257]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lightnovelpub.com/`

### Category

ads/anti-adblock

### Description

When adblock is enabled it shows what is seen in the attached picture. I've found one of the elements: div.hdmGTxag_.hdmGTxag:nth-of-type(1) and the number at the end is usually 1-10 whereas the random letters "hdmGTxag_.hdmGTxag" change every 24~ hours so even if you add them to the filter list it will appear again the next day,

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![chrome_ul5n39TpP0](https://user-images.githubusercontent.com/41215615/226894351-3d50b26c-e40d-4310-a9cb-0e3113c0cd7e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 86449
  cosmetic: 39087
  scriptlet: 17051
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64204-44, 2d.12h.23m
    easyprivacy: 31059-1174, 2d.12h.22m
    plowe-0: 3757-931, 6d.12h.52m
    ublock-abuse: 78-0, 6d.12h.50m
    ublock-badware: 4736-114, 2d.12h.21m
    ublock-filters: 32020-83, 2d.12h.20m
    ublock-privacy: 291-1, 6d.12h.45m
    ublock-quick-fixes: 387-33, 23h.49m
    ublock-unbreak: 1932-40, 2d.12h.19m
    urlhaus-1: 6712-0, 23h.48m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 31020 ms (selfie)
  maxAssetCacheWait: 118 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    connatix.com: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    translate.googleapis.com: 1
```
</details>

**Comment by gorhill** [comment]
I don't see anti-blocker message, but I do see placeholders. Does this work?

    lightnovelpub.com##.ofh

**Comment by garry-ut99** [comment]
> this worked perfectly

Not perfectly, even `lightnovelpub.*#@#.adsbygoogle:upward(1)` still causes ad placeholders appearing / blinking for a fraction of second before they are hidden.

After disabling already existing filters:
```
lightnovelpub.*#@#.adsbygoogle:upward(1)
lightnovelpub.*,webnovelpub.com#@#div[class] > ins.adsbygoogle:upward(div[class])
```

and adding this one instead: `lightnovelpub.*##div:has(>.adsbygoogle)` which uses a scope,
there is no blinking anymore, and the ad placeholders are hidden instantly, 
(at least in Chromium (Opera) because in Firefox they're still blinking).

**Comment by gorhill** [comment]
There are 200+ `div` on that page, so I rather we keep `##.adsbygoogle:upward(1)`. Once Firefox natively supports `:has()`, we can start preferring it to procedural filters.

**Comment by gorhill** [comment]
> hidden by existing filters

Yes, the ones @mapx- added 4 hours ago.

**Comment by gorhill** [comment]
I could reproduce the placeholders, and `##.cnx_container` was not enough, see <https://www.lightnovelpub.com/hub_08032132>. Anyway, as far as I am concerned, case closed, I'm out.

**Comment by garry-ut99** [comment]
> Once Firefox natively supports `:has()`, we can start preferring it to procedural filters. 
(and I don't see the blinking on my side with `:upward()`).

Or to use `!#if env_` [directives](https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#if-condition) until then, but only if several users confirm page's elements blinking in a given site.

<hr>

> What does `##.adsbygoogle:upward(1)` actually hide? On my side they're already hidden by existing filters. Only needing `##.cnx_container`.
> 
> `https://www.lightnovelpub.com/novel/lord-of-the-mysteries-wn-14032207`

Even before I wrote [my comment](https://github.com/uBlockOrigin/uAssets/issues/17257#issuecomment-1479817825) I already noticed the same strange thing like you: 
I could reproduce ad placeholders before https://github.com/uBlockOrigin/uAssets/commit/2fe9517aa99c3f763069b6a6b0be213c4ec853cd landed, 
but after I updated my filters I get no ad placeholders anymore even with https://github.com/uBlockOrigin/uAssets/commit/2fe9517aa99c3f763069b6a6b0be213c4ec853cd whitelisted, because the old filter:
`lightnovelpub.*,webnovelpub.com##div[class] > ins.adsbygoogle:upward(div[class])` hides them already.
The question is why the old filter wasn't hiding them before https://github.com/uBlockOrigin/uAssets/commit/2fe9517aa99c3f763069b6a6b0be213c4ec853cd landed.
