### ISSUE TITLE
tidal.com: breakage

### ISSUE THREAD

**Issue by TommyDeCortez** [uBlockOrigin/uAssets#17495]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I create new playlist on Tidal web player then I can not add new song. When I shutdown uBlock origin I can add new song to the playlist.

### URL(s) where the issue occurs.

`www.tidal.com`

### uBO version

Latest

### Browser name and version

MS Edge - latest, Brave browser - latest

### Settings

Shut off uBlock filters - then playlist is O.K.

### Notes

When I create new playlist on Tidal web player then I can not add new song. When I shutdown uBlock origin I can add new song to the playlist. When is uBlock on i gave message: "This playlist has been modified elsewhere"
This cause uBlock filters, when is shut down I have no problem with playlist but I have audio advetisement.

**Comment by mapx-** [comment]
A subscription is required.

First of all, follow the **all the indications** bellow. If you still experience issues, we'll ask you if you are willing to send (privately) your account credentials in order to be able to further investigate your issue.

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by TommyDeCortez** [comment]
I tried everything but with no result. This cause problem: listen.tidal.com##+js(no-fetch-if, /\d\?country/) but when is shut off i have audio advertisement.

**Comment by stephenhawk8054** [comment]
Test account here (with US IP): https://github.com/uBlockOrigin/uBlock-discussions/discussions/465

The regex needs to be changed I think, but other regexes did not work last time I checked. I still don't know why.

**Comment by mapx-** [comment]
@TommyDeCortez 

could you test

```
listen.tidal.com#@#+js(no-fetch-if, /\d\?country/)
listen.tidal.com##+js(no-fetch-if, /\/tracks\/.*\d\?country/)
```

**Comment by TommyDeCortez** [comment]
> @TommyDeCortez
> 
> could you test
> 
> ```
> listen.tidal.com#@#+js(no-fetch-if, /\d\?country/)
> listen.tidal.com##+js(no-fetch-if, /\/tracks\/.*\d\?country/)
> ```

Add new song to the playlist work but I have audio advertisement.

**Comment by stephenhawk8054** [comment]
I think it might relate to service workers: unregister the workers at `chrome://serviceworker-internals/` and `about:serviceworkers`

```adb
||tidal.com^$csp=worker-src 'none'
```

?

**Comment by stephenhawk8054** [comment]
@TommyDeCortez Do these work for you?

```adb
listen.tidal.com#@#+js(no-fetch-if, /\d\?country/)
listen.tidal.com##+js(no-fetch-if, /\/users\/.*\d\?country/)
```

**Comment by TommyDeCortez** [comment]
> @TommyDeCortez Do these work for you?
> 
> ```
> listen.tidal.com#@#+js(no-fetch-if, /\d\?country/)
> listen.tidal.com##+js(no-fetch-if, /\/users\/.*\d\?country/)
> ```

It does not work.  Add to playlist works.  The audio ad remains but the player disappears when it plays.

**Comment by stephenhawk8054** [comment]
Well, last effort, can you do these steps?

1. Go to `chrome://serviceworker-internals/` and find TIDAL service worker -> Unregister it.
2. Add these filters:
3.

**Comment by stephenhawk8054** [comment]
Well, last effort, can you do these steps?

1. Go to `chrome://serviceworker-internals/` and find TIDAL service worker -> Unregister it.
2. Add these filters:

```adb
listen.tidal.com#@#+js(no-fetch-if, /\d\?country/)
listen.tidal.com##+js(no-fetch-if, /\/tracks\/.*\d\?country/)
listen.tidal.com##+js(no-fetch-if, /\/users\/.*\d\?country/)
||pushkin-v2.tidal.com/public/token/*/ws$websocket,1p
||listen.tidal.com/*/rt/connect$xhr,1p
||tidal.com^$csp=worker-src 'none'
```

3. Clear cookies and cache of TIDAL, log in and test again.

If it doesn't work, we can only remove the filter to prevent breakage, as I cannot reproduce the ads anymore.

**Comment by TommyDeCortez** [comment]
> ```
> listen.tidal.com#@#+js(no-fetch-if, /\d\?country/)
> listen.tidal.com##+js(no-fetch-if, /\/tracks\/.*\d\?country/)
> listen.tidal.com##+js(no-fetch-if, /\/users\/.*\d\?country/)
> ||pushkin-v2.tidal.com/public/token/*/ws$websocket,1p
> ||listen.tidal.com/*/rt/connect$xhr,1p
> ||tidal.com^$csp=worker-src 'none'
> ```

Looks like it's working.
Thank you very much

**Comment by stephenhawk8054** [comment]
Can you test without the last filter (the `worker-src` one)

**Comment by stephenhawk8054** [comment]
For me it works without the `$csp` filter. However the main thing is it still comes with a breakage:

![image](https://user-images.githubusercontent.com/66517106/230868471-ed9b179b-29f3-438e-8e99-56984a606b60.png)

The profile section at the top left cannot show and I cannot click on it due to `listen.tidal.com##+js(no-fetch-if, /\/users\/.*\d\?country/)` (this filter makes Tidal's server not being able to recognize user's ID to deliver the ads I think), and I'm not sure if there would be other breakages or not. At least it's a bit better than the current situation.

@mapx- I'm not sure if we should add the filters or not regarding this breakage. I think it would be more suitable for an Experimental/Extra list than main list.

**Comment by mapx-** [comment]
We should remove that breaking filter and if the other filters cause other breakages, well, for now nothing to do

**Comment by stephenhawk8054** [comment]
Hmmm... Looks like this filter works for me without any breakages:

```adb
listen.tidal.com##+js(json-prune, countryCode)
```

Can anyone else test it?

**Comment by TommyDeCortez** [comment]
> Hmmm... Looks like this filter works for me without any breakages:
> 
> ```
> listen.tidal.com##+js(json-prune, countryCode)
> ```
> 
> Can anyone else test it?
> 
> Feedbacks:
> 
> ```
> https://www.reddit.com/r/uBlockOrigin/comments/144ukk9/is_there_any_new_filters_for_tidal/jnhpg3a/
> ```

When I use this filter, the Tidal page doesn't load at all

**Comment by stephenhawk8054** [comment]
@TommyDeCortez Try this

```adb
listen.tidal.com##+js(json-prune, countryCode, tidalId)
```

**Comment by TommyDeCortez** [comment]
> @TommyDeCortez Try this
> 
> ```
> listen.tidal.com##+js(json-prune, countryCode, tidalId)
> ```

The page will load with this filter. But I have audio ads.

**Comment by stephenhawk8054** [comment]
Hmmm... I got no ads with that filter. Did you open in new tab and test again?

**Comment by TommyDeCortez** [comment]
> Hmmm... I got no ads with that filter. Did you open in new tab and test again?

I try another VPN server and now it seems that it working.
