### ISSUE TITLE
pornoid.com [NSFW][ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1767]
URL(s) where the issue occurs

`https://pornoid.com/videos/1847515/blonde-with-huge-jugs-is-one-hot-cock-rider-that-loves-it-so-much`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.18

Settings

Default

**Comment by WowDude** [comment]
Enabling `Adguard Base Filters` removes some of the ads, for the rest: `pornoid.com###c2p_small`.

**Comment by WowDude** [comment]
Still one of the ad not removed (Opera 51 64bit & uBO 1.15.18 & Win 7 SP1 64bit):

<details>
  <summary>Screenshoot</summary>

![pornoid](https://user-images.githubusercontent.com/37474031/37854108-cf471e5a-2ee9-11e8-83fd-160f6076af40.png)

</details>

**Comment by mapx-** [comment]
tested in opera 52, no such ad for me.

**Comment by WowDude** [comment]
My screen res is 1280x1024. In Opera's Inspector, in "Responsive mode" (Toogle device toolbar) when I change res to 1280x800 or 1920x1080 there is no ads...but when switch back to 1280x1024 ads appears again.

**Comment by WowDude** [comment]
So it was more about DPI than screen resolution, , STR: incerase system DPI: 
- [for Win 7](http://www.lawfirmsoftware.com/support/change_dpi_settings_windows_7.htm) medium DPI 125% (I reproduced the issue)
- [for Win XP](http://www.desksite.com/faq/dpi-settings/windowsxp.htm) large DPI 120 (I reproduced the issue)
- [for Ubuntu 16.04](https://askubuntu.com/questions/823529/how-do-you-set-scaling-for-a-high-dpi-monitor-and-low-dpi-monitor-independently) ( I didn't try on Ubuntu)

I don't know if the resolution matters, however, for sure, the issue was on 1280x1024 and smallers.

**Comment by WowDude** [comment]
@mapx- can you reproduce?

**Comment by mapx-** [comment]
I get no ads even with 1280x1024

**Comment by WowDude** [comment]
Weird, @Blutgang , @KiLL4FuNK can you reproduce?
