### ISSUE TITLE
Unilever Food Solutions

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#1893]
### URL(s) where the issue occurs

`www.ufs.com` - domains (no all have cookiewall).

### Describe the issue

Cookiewall and breaking website when cut only pop-up (blur website filter and block scroll - CSS)

```
##.js-cookie-wall
##.cookie-wall
```

### Screenshot(s)

![image](https://user-images.githubusercontent.com/35370833/38357627-762209aa-38c3-11e8-9940-985bafb01590.png)

### Versions

- Browser/version: N/A
- uBlock Origin version: N/A

### Settings

- default uBO + Cookiemonster

#### CSS bypass:

```
unileverfoodsolutions.*##body.blurred>*:style(box-shadow:none!important;filter:none!important;)
unileverfoodsolutions.*##body:style(overflow:auto!important;)
```

**Comment by krystian3w** [comment]
Hello, filters no is outdated, for me website serve `evidon` simpler (without block scroll and blur) script.

```
||c.evidon.com/sitenotice/evidon-barrier.js
```

but this is problematic script: https://github.com/ryanbr/fanboy-adblock/issues/522

@THEtomaso can you test how works on `Unilever Food Solutions`?

`http://www.ufs.com/?nr=1`

**Comment by THEtomaso** [comment]
Yes, I took a look at those sites just now, and as usual, I can confirm that "Evidon" blocking is responsible for breaking them (images, functions, etc.).
But like I've mentioned before, I've had it with all those Evidon issues..
I've added the necessary generic exceptions to my own filter, and this has turned out to be a huge relief!:
`https://github.com/DandelionSprout/adfilt/issues/7/#issuecomment-431578932`

**Comment by krystian3w** [comment]
@okiehsch  / @mapx-  / @ZaphodBeebblebrox 

Can revert css bypass, outdated and on small screen (HD Ready and Less) create unless horizontal scroll by:
 `body:style(overflow:auto!important;)`
