### ISSUE TITLE
newscon.org: detection

### ISSUE THREAD

**Issue by Hazuki-san** [uBlockOrigin/uAssets#19589]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Script was edited to bypass the current adblocker filter.

### URL(s) where the issue occurs.

`https://www.newscon.org/download/`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/27200811/87ccf1d8-c41d-4f1a-97d2-0c9896856434)

### uBO version

1.51.0

### Browser name and version

Microsoft Edge Version 116.0.1938.69 (Official build) (64-bit)

### Settings

default/stock settings, didn't do any changes.

**Comment by mapx-** [comment]
Test

`newscon.org##+js(nosiif, ads)`

**Comment by Hazuki-san** [comment]
> Test
> 
> `newscon.org##+js(nosiif, ads)`
works

**Comment by D4niloMR** [comment]
@mapx- 

`https://www.newscon.org/snippet/e2?message=wq_Cm8OxwrbDmcK1w5l5woLCl8K7wrjCrcOPwqjCqMOYw5x9Y8KhwqLCjsKY`

`newscon.org##+js(set, WAITING_TIME, 0)`

To skip the timer.

**Comment by huyszn** [comment]
The site is detecting again.

**Comment by mapx-** [comment]
provide example link

**Comment by runebalot** [comment]
> provide example link

https://www.newscon.org/?m=wrzCtcOJwrXCl8Klw5LCpsKIw4nCuMOGw4rCrsOFw5nDn8OIwprCn8KaesKOwpg=

**Comment by runebalot** [comment]
The timer seems to still be there.

https://www.newscon.org/?m=wqLCl8K6w5XCpsKkwrTCiWXCtcKOwqDDhsOxw6XCuMOHw4fCh8KpwrfCt8KOwpg=

**Comment by oberon202** [comment]
> [mapx-](https://github.com/mapx-) added a commit that referenced this issue Oct 20, 2024
@mapx-
[https://github.com/uBlockOrigin/uAssets/issues/19589#issuecomment-242…](https://github.com/uBlockOrigin/uAssets/commit/6d091f304e8dc92655bbae132733d8a4889e130b)
[6d091f3](https://github.com/uBlockOrigin/uAssets/commit/6d091f304e8dc92655bbae132733d8a4889e130b)

…5003223

<

The timer runs faster with the new code but still takes 40 seconds (instead of 400) which is still a lot considering the number of times it is displayed. ALso the window has to stay focused for the timer to run otherwise it blocks. It used to be completely gone bfore they updated it.
