### ISSUE TITLE
tomsguide.com: nuisance

### ISSUE THREAD

**Issue by ave9858** [uBlockOrigin/uAssets#19984]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tomsguide.com/`

### Category

nuisance

### Description

Cookie popup is shown after page load. Tested with default filters and with all annoyances filters on.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/7ca9ee15-6a41-4613-abe4-471b395f6c0c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 113570
 cosmetic: 189009
 scriptlet: 28862
 html: 1243
listset (total-discarded, last-updated):
 added:
  adguard-social: 21847-859, 7m
  adguard-cookies: 27779-63, 7m
  ublock-cookies-adguard: 319-0, 7m
  adguard-popup-overlays: 24556-1546, 7m
  adguard-mobile-app-banners: 4646-1062, 7m
  adguard-other-annoyances: 13627-309, 7m
  adguard-widgets: 2312-1, 7m
  fanboy-thirdparty_social: 68-0, 7m
  easylist-annoyances: 3986-116, 7m
  easylist-chat: 141-11, 7m
  fanboy-cookiemonster: 48479-3878, 7m
  ublock-cookies-easylist: 319-319, 7m
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35842-450, 8m
  ublock-badware: 7185-0, 8m
  ublock-privacy: 587-0, 8m
  ublock-unbreak: 2180-0, 8m
  ublock-quick-fixes: 156-0, 8m
  easylist: 71552-785, 8m
  easyprivacy: 33213-807, 8m
  urlhaus-1: 10020-0, 7m
  plowe-0: 3720-1, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2905 ms
 maxAssetCacheWait: 107 ms
popupPanel:
 blocked: 7
 network:
  dotmetrics.net: 1
  futurecdn.net: 1
  google-analytics.com: 1
  onesignal.com: 1
  parsely.com: 1
  permutive.app: 1
  scorecardresearch.com: 1
 extended:
  ###slice-container-newsletterForm-exitIntent
  ##div[id^="slice-container-newsletter"]
  ##div[class*="ad-unit"]
  ##.instagram-icon
  ##.pinterest-icon
  ##.dfp-leaderboard-container
  ##.newsletter-slice
  ##.newsletterForm-exitIntent
  ##.slice-container-newsletterForm
  ##.ad-unit:not(.text-ad):not(.textads)
  ##.sponsored-post
  #@#.ad-unit
  ##+js(abort-on-property-read, _sp_._networkListenerData)
```
</details>

**Comment by mapx-** [comment]
The problem is:

Aguard is whitelisting it:

    @@||cdn.privacy-mgmt.com/unified/wrappermessagingwithoutdetection.js$from=news.sky.com|owlcation.com|reelrundown.com|tomsguide.com

fanboy's list is blocking it:

 
 
 
 /wrappermessagingwithoutdetection.js$from=10kysymysta.fi|2050.de|4fansites.de|4players.de|abiristeilyt.fi|ableitungsrechner.net|abonnement.hln.be|about-drinks.com|ad-alliance.de|advnture.com|aftenbladet.no|airliners.de|aktuality.sk|akuankka.fi|alypaa.com|androidcentral.com|anime2you.de|apotheken-umschau.de|ariadneathome.nl|ariva.de|auto-motor-und-sport.de|autobild.es|autoexpress.co.uk|automobil-elektronik-kongress.de|autotrack.nl|autotrader.co.uk|autoweek.nl|autowereld.nl|autozeitung.de|axelspringer.com|azet.sk|baby-und-familie.de|badoo.com|bautipps.it|bbc.com|bbcgoodfood.com|bbheute.de|bergfex.com|berliner-kurier.de|bestcheck.de|bikeradar.com|bistro.sk|bitpipe.com|bitpipe.com.br|blick.de|bnr.nl|bordercountiesadvertizer.co.uk|borncity.com|brighttalk.com|bucksfreepress.co.uk|burda-forward.de|businessinsider.com|businessinsider.es|calculadora-de-derivadas.com|calculadora-de-integrales.com|camping.info|capital.de|caradisiac.com|caravaning.de|cardscout.de|carmagazine.co.uk|carthrottle.com|cavallo.de|celticway.co.uk|channelpartner.de|charlieintel.com|chefkoch.de|chesterstandard.co.uk|chinahandys.net|cinema.de|cio.com|cio.de|classical-music.com|classicfm.com|clever-tanken.de|closeronline.co.uk|computec.de|computerfrage.net|computerhoy.com|computerweekly.com|computerwoche.de|computerworld.com|countypress.co.uk|countytimes.co.uk|cravenherald.co.uk|crn.com|cryptoticker.io|csoonline.com|dagallemaal.be|dailyresearchplot.com|deine-tierwelt.de|deluxemusic.de|demorgen.be|denofgeek.com|derivative-calculator.net|dexerto.com|digilehdet.fi|digitalartsonline.co.uk|discoverwildlife.com|dk-online.de|donaldduck.nl|dpd.com|dpd.de|duden.de|dudleynews.co.uk|dumont.de|dunfermlinepress.com|e24.no|ecomento.de|edpc.eu|eigenhuiseninterieur.nl|eiu.com|elektroauto-news.net|elle.de|empireonline.com|entertainmentdaily.co.uk|esquire.de|essen-und-trinken.de|expertreviews.co.uk|falmouthpacket.co.uk|familie.de|faroutmagazine.co.uk|fd.nl|feelingwonen.be|filext.com|finanzen100.de|finanzfrage.net|finanznachrichten.de|finanztreff.de|findagrave.com|flair.nl|flowmagazine.nl|flugrevue.de|fourfourtwo.com|frag-mutti.de|fussballfieber.de|futisporssi.fi|futurism.com|gaelmaison.be|gamesradar.com|gardenersworld.com|gaspedaal.nl|gazetteandherald.co.uk|geo-television.de|geo.de|gladbachlive.de|globalplayer.com|goal.com|godt.no|goedgevoel.be|goom.net|greenocktelegraph.co.uk|gruenderkueche.de|guide-epargne.be|guitarworld.com|gutefrage.net|gutekueche.at|hampshirechronicle.co.uk|handelsblatt.com|hannover.de|harpersbazaar.de|helpforum.sky.com|helpster.de|herefordtimes.com|himosjuhannus.fi|hitc.com|hockeygm.fi|humo.be|idealo.at|idealo.co.uk|idealo.de|idealo.es|idealo.fr|idealo.it|iltapulu.fi|impartialreporter.com|indebuurt.nl|independer.be|instyle.de|integral-calculator.com|integral-calculator.ru|integralrechner.de|intermediair.nl|iskelma.fi|iskelmafestivaali.fi|itpro.co.uk|itpro.com|jameda.de|jamiegeller.co|jetzt.de|jobat.be|joe.be|justjared.com|justthenews.com|jysari.fi|kachelmannwetter.com|kiosk.nl|kkuriren.se|klamm.de|klara.be|kn-online.de|komando.com|krzbb.de|kuechengoetter.de|kuopiorock.fi|lancashiretelegraph.co.uk|laptopmag.com|lbc.co.uk|leaderlive.co.uk|lecker.de|leijonaporssi.fi|lemagit.fr|leonberger-kreiszeitung.de|lepoint.fr|leserreisen.mz-web.de|leukstetickets.nl|libelle.nl|liberation.fr|liigaporssi.fi|linux-magazin.de|livefortheoutdoors.com|livescience.com|livingathome.de|livios.be|ln-online.de|lossebladen.nl|lovelybooks.de|maclife.de|macwelt.de|macworld.com|malservice.aftonbladet.se|margriet.nl|marieclaire.co.uk|mcnmotorcycleshow.com|mediaimpact.de|mein-schoener-garten.de|meineorte.com|menshealth.de|mensjournal.com|meteologix.com|mijnenergie.be|minmote.no|mishtalk.com|mnm.be|monenergie.be|morewithvpro.com|mountainbike-magazin.de|moz.de|muehlacker-tagblatt.de|mumsnet.com|musicradar.com|myfitnesspal.com|myhomebook.de|n-page.de|nationalevacaturebank.nl|nehnutelnosti.sk|nelonen.fi|nelonenmedialive.fi|netdoktor.de|netmoms.de|networkworld.com|neuepresse.de|nexttv.com|nitro-tv.de|nnn.de|northwaleschronicle.co.uk|nostalgie.be|nouveau.nl|nowtv.com|nowtv.it|noz.de|nrj.be|nu.nl|oekotest.de|onvista.de|oskar.de|oudersvannu.nl|parool.nl|pcgamer.com|pcgamesn.com|pclifecyclemanagement.com|pcwelt.de|pcworld.com|pcworld.es|pent.no|phonostar.de|photovoltaikforum.com|planet3ds.de|planetds.de|planetgameboy.de|planetiphone.de|planetradio.co.uk|planetswitch.de|planetvita.de|playpilot.com|playstationportable.de|podme.com|podplay.com|politico.eu|portablegaming.de|prad.de|praxisvita.de|pricespy.co.uk|pride.com|prignitzer.de|primo.be|prinz.de|qmusic.be|qmusic.nl|qz.com|racefans.net|radio.at|radio.de|radio.dk|radio.es|radio.fr|radio.it|radio.net|radio.pl|radio.pt|radio.se|radio1.be|radio2.be|radiocity.fi|radionova.fi|radioplay.fi|radiopooki.fi|rakennuslehti.fi|realitytitbit.com|reclamefolder.nl|redensarten-index.de|reisefrage.net|rheinpfalz.de|rmj.fi|roadbike.de|rockfest.fi|romfordrecorder.co.uk|rtl-passion.de|rtlplus.de|rugbydump.com|rugbyonslaught.com|sanakirja.org|sanoma.fi|scholieren.com|schwarzwaelder-bote.de|sciencefocus.com|second-hand.it|selbermachen.de|senioren-ratgeber.de|shz.de|sir-apfelot.de|sky.de|skysports.com|snow-forecast.com|somersetcountygazette.co.uk|soundis.gr|southwalesargus.co.uk|spaargids.be|space.com|speed.io|spielaffe.de|sportbible.com|sportnews.bz|sportnieuws.nl|sportsmole.co.uk|sporza.be|startpagina.nl|stijlvol-wonen.com|story.nl|streampicker.de|stubru.be|studyflix.de|stuff.tv|stuttgarter-nachrichten.de|stuttgarter-zeitung.de|sueddeutsche.de|sueddeutscher-verlag.de|suedtirolnews.it|suomipopfestivaali.fi|suomitutka.fi|sv-veranstaltungen.de|svz.de|swmh.de|swp.de|t3.com|t3n.de|tahkojuhannus.fi|tammerfest.fi|tecchannel.de|techadvisor.com|techadvisor.fr|techhive.com|techradar.com|techstage.de|techtarget.com|techtarget.de|techtarget.fr|telegraph.co.uk|telepolis.de|telmi.it|testedich.de|teveblad.be|thatgrapejuice.net|the-decoder.com|the-decoder.de|the-sun.com|theboltonnews.co.uk|thecelticblog.com|thechelseachronicle.com|thedailymash.co.uk|thedrive.com|theloadout.com|thenational.scot|thenorthernecho.co.uk|thepeoplesperson.com|thepoke.co.uk|thescottishsun.co.uk|theserverside.com|thesun.co.uk|thesun.ie|thetab.com|thetimes.co.uk|tijdschrift.nl|toggo.de|tomsguide.com|tomshardware.com|totaaltv.nl|travelbook.de|trouw.nl|tv14.de|tvfamilie.be|tvnow.at|tvnow.de|unnuetzes.com|utopia.de|vaalikone.fi|vdi-nachrichten.com|veronicasuperguide.nl|vice.com|visit-hannover.com|viva.nl|vkmag.com|vkz.de|voice.fi|volkskrant.nl|vox.de|vrt.be|vrtinternational.com|vtm.be|vtwonen.be|vtwonen.nl|wallstreet-online.de|wanajafestival.fi|watfordobserver.co.uk|webwinkel.ad.nl|webwinkel.bndestem.nl|webwinkel.destentor.nl|webwinkel.ed.nl|webwinkel.gelderlander.nl|webwinkel.pzc.nl|webwinkel.volkskrant.nl|wetteronline.de|whathifi.com|whats-on-netflix.com|wieistmeineip.de|willy.radio|windowscentral.com|winhappy.com|wirralglobe.co.uk|wisden.com|wiwo.de|wonenlandelijkestijl.com|worcesternews.co.uk|wowtv.de|www.sky.com|www.sky.it|zozitdat.nl|zvw.de

**Comment by mapx-** [comment]
@ave9858 

add for now in your "my filters"

`||cdn.privacy-mgmt.com/unified/wrappermessagingwithoutdetection.js$domain=tomsguide.com,important`

**Comment by peace2000** [comment]
@Alex-302

Is there a reason why AG whitelists that GDPR script for `tomsguide.com` ? Usually whitelisting GDPR scripts is done because embedded content won't work, but at least videos and tweets work fine:

https://www.tomsguide.com/news/twitter-is-down-for-many-users-here-are-the-latest-updates
https://www.tomsguide.com/news/the-secret-sauce-to-stunning-summer-videos-with-filmora

Maybe that whitelist rule is not needed anymore?

**Comment by mapx-** [comment]
@ave9858 the cookie thing cannot be hidden otherwise a lot of videos would be broken.

If you still want it just add the filter I specified above

**Comment by ave9858** [comment]
> @ave9858 the cookie thing cannot be hidden otherwise a lot of videos would be broken.
> 
> If you still want it just add the filter I specified above

When I click "More Options" with the annoyance filters on, I never get another popup that allows me to select the cookie options. Disabling "AdGuard – Cookie Notices" seems to fix the issue, but I'm not sure what cookies I need to allow to have the site fully functional. What URL should I use to test if videos are broken?

**Comment by mapx-** [comment]
add this exception

`@@||cdn.privacy-mgmt.com/privacy-manager/$frame,domain=tomsguide.com`

**Comment by ave9858** [comment]
That works to access the second popup with AdGuard Cookie Notices enabled. I'll use the first filter you sent since I haven't been able to find any pages with broken videos. Thank you for your help

**Comment by mapx-** [comment]
first add
`tomsguide.com#@#.jwplayer__widthsetter`

then go to
`https://www.tomsguide.com/reviews/google-pixel-8-pro`

the video will be broken if you use
`||cdn.privacy-mgmt.com/unified/wrappermessagingwithoutdetection.js$domain=tomsguide.com,important`

**Comment by ave9858** [comment]
ty, I must have missed those videos since they are blocked by the default config. I'll keep both blocked.

**Comment by peace2000** [comment]
Added GDPR dialog fix for the Annoyance list https://github.com/uBlockOrigin/uAssets/commit/6830c1c1d4b156d115233ed2422bebc3e6327358
