### ISSUE TITLE
YouTube Detection

### ISSUE THREAD

**Issue by SolomonZweig** [uBlockOrigin/uAssets#21922]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://www.youtube.com/watch?v=tN2mmSmhGo8

### Description

The ad-blocker pop-up in the video player that appeared a few months ago has returned.

### Other extensions used

None

### Screenshot(s)

![Screenshot 2024-01-11 203751](https://github.com/uBlockOrigin/uAssets/assets/109000204/390ae5c7-2077-44ac-a1e8-0230c0e3a770)

### Configuration

uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 115686
 cosmetic: 44233
 scriptlet: 20018
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77037-12, 27m
  easyprivacy: 43408-32, 26m
  plowe-0: 3787-1167, 21m
  ublock-badware: 7784-137, 27m
  ublock-filters: 36391-129, 27m
  ublock-privacy: 962-7, 26m
  ublock-quick-fixes: 188-50, 26m
  ublock-unbreak: 2187-31, 26m
  urlhaus-1: 9905-0, 21m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 482 ms (selfie)
 maxAssetCacheWait: 209 ms
popupPanel:
 blocked: 35
 network:
  youtube.com: 1
  doubleclick.net: 5
  google.com: 29
 extended:
  ###main > #banner.ytd-merch-shelf-renderer
  ###panels > [target-id="engagement-panel-ads"]
  ###related > div#player-ads
  ###scroll-container > #items.ytd-merch-shelf-renderer
  ###ytd-player button.ytp-suggested-action-badge
  ##.ytp-chrome-top-buttons > .ytp-cards-teaser
  ##ytd-ad-slot-renderer.style-scope.ytd-item-section-renderer
  ##ytd-watch-info-text > #info-container > #info > span:has-text(…
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)

**Comment by stephenhawk8054** [comment]
Why did you tick on this?

> - [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.

**Comment by SolomonZweig** [comment]
I couldn't submit the comment without doing so.

**Comment by stephenhawk8054** [comment]
Because we don't want you to submit the new issue when there's already a thread for youtube issue.

It's the link in that checkbox. Please check it carefully:

> This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.

[YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586)

**Comment by garry-ut99** [comment]
> stephenhawk8054 : It's the link in that checkbox. Please check it carefully

I think this is what is the problem, the links are just misleading and cause users assume in the advance that the links lead just to webpages (`youtube.com`, `facebook.com`, `twitch.tv`) and to nothing more, thus they don't even check them, hence the proposition is to change it to something more explanatory, for example :

> This is NOT a YouTube, Facebook or Twitch report, these are to be reported in other place :  [here for YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586) ,  [here for Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) and [here for Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).

.

**Comment by stephenhawk8054** [comment]
@u-RraaLL I think we can change the line to that?

**Comment by garry-ut99** [comment]
> - https://github.com/uBlockOrigin/uAssets/pull/21959 : 
>
> This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_. *

This won't help much, the **links** still look like links to webpages, and not to issues, and users will not find out that the _**respective links**_ mean the **links**, and they will still think that the **links** lead to websites, and that _**respective links**_  are some other links which they don't know about. The version I proposed was just fine, I know that in my version, websites names are repeated twice, but this was necessary to make it easy to understand for novice users.


<details>
<summary>Also by the way, a technical statement :</summary>

<br>

As I don't like to be blamed for other people's off-topic (and I was blamed 2 times already),
if whoever considers the discussion here as off-topic, then I make it very clear : 
- it was not me who started it, and not me who chose this place for it, it was started here : https://github.com/uBlockOrigin/uAssets/issues/21922#issuecomment-1888284088)
- I only continue it here, because it was started here, and nobody has said to continue elsewhere so far
- hence I don't feel responsible neither for decisions/rules made by someone else, nor for a lack of decisions
- if whoever else prefers a different place for it, we can continue it in the commit or the issue can be converted to a discussion, but I'm not going to made such decision on my own, because I don't feel legitimate to change someone else's decisions/rules, nor anybody have told me so, so far
- (also moving to commit means splitting the discussion into several pieces, which might be not the best idea, given there might be more related commits coming soon, which would split it even more)

</details>
