### ISSUE TITLE
ceplik.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2205]
URL(s) where the issue occurs

`https://www.ceplik.com/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.4

Settings

Default

**Comment by garry-ut99** [comment]
Yellow ad placeholders all over the site, caused by `ghide` in "uBlock filters": [SCREENSHOOT 1](https://user-images.githubusercontent.com/72945564/214822279-e3d64750-49cb-4124-aea3-3f624bf86e4d.png), [SCREENSHOOT 2](https://user-images.githubusercontent.com/72945564/214822288-c8ad3edd-06dc-4849-af42-fd7e6aec9eda.png)
