### ISSUE TITLE
cnn.com home page cosmetic touch ups

### ISSUE THREAD

**Issue by geoffdutton** [uBlockOrigin/uAssets#2227]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`cnn.com`

### Describe the issue

In one of the tiles, there is a 'Paid Partner Content' with a few native links.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/1251360/39785341-6498b14c-52e1-11e8-869e-2a34feb9ddae.png)

### Versions

- Browser/version: Firefox 59.0.2
- uBlock Origin version: 1.16.4

### Settings

- Default filters

### Notes

I'm submitting a PR for the fixes. It's just some cosmetic selectors.

**Comment by mapx-** [comment]
it's about
```
cnn.com##h2[data-analytics*="Paid Partner"]
cnn.com##li > article[data-vr-contentbox*="ck.lendingtree.com"]
cnn.com##li > article[data-vr-contentbox*="comparecards.com"]
```

so, you should report to easylist repository (no uBo specific filter)
@ryanbr

**Comment by geoffdutton** [comment]
@mapx- Sorry for the misunderstanding... how should I determine whether to contribute to EasyList vs uAssets?

**Comment by okiehsch** [comment]
As a rule of thumb if the issue can be fixed by a simple cosmetic or static filter it is probably best to report to EasyList.
If [extended syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#extended-syntax) is needed it is always best to report to uAssets.

One notable excepton is if you have an anti-adblock issue you should always report to uAssets, because EasyList will not circumvent them.

**Comment by geoffdutton** [comment]
Got it, thanks!

**Comment by mapx-** [comment]
adblock (AB), adblock plus (ABP) already have this weapon (ABP I'm sure, AB is using the ABP internal engine).

for example (from easylist)
`quora.com#?#.question_page_content:-abp-has(div:-abp-contains(promoted))`

`:-abp-has => :has`
`:-abp-contains =< has-text`
