### ISSUE TITLE
ashemaletube.com [ADS][NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2282]
URL(s) where the issue occurs

`https://www.ashemaletube.com/`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.4

Settings

Default

**Comment by KiLL4FuNK** [comment]
ADS VIDEO PLAY ANTI ADBLOCK

`https://www.ashemaletube.com/videos/515718/horny-chubby-sweet-tgirl/`

**Comment by mapx-** [comment]
test
```
@@||ashemaletube.com^$ghide
||cc.ashemaletube.com/*/header-black.jpg$image
ashemaletube.com##body:style(background: none !important; overflow: auto !important;)
ashemaletube.com##+js(aopr, open)
```

**Comment by ledemon** [comment]
thumbnail rotation with "ublock filters" activated are broken (not rotate)

**Comment by mapx-** [comment]
Where are those thumbnails ? home page ? other pages ? screenshot ?

**Comment by ledemon** [comment]
homepage, search result page, every thumbnail video

**Comment by huyszn** [comment]
I occasionally get a preroll ad whenever I play a video **nsfw**  (https://github.com/uBlockOrigin/uAssets/assets/46979193/31158b68-cf1a-4807-99f5-4184b6374673). I don’t know how to trigger this preroll ad every time because I had to play many videos in order for it to appear again. I notice that `prerollAd` sometimes contains `vastURL: 'https://cc.ashemaletube.com/ast/b/gamingadult-ast.xml'` which includes the exact preroll ad that goes through. uBO seems to block the other preroll ads but not this one.

**Comment by huyszn** [comment]
The new filter blocks video previews when you hover over thumbnails. Before and when uBO is turned off, video previews work when I hover over thumbnails.
