### ISSUE TITLE
reclameaqui.com.br: breakage

### ISSUE THREAD

**Issue by CamilaLorenzetti** [uBlockOrigin/uAssets#23076]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.reclameaqui.com.br/empresa/santa-casa-copacabana-funeraria/`

### Category

breakage

### Description

Broken layout when uBlock Origin is enabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://github.com/uBlockOrigin/uAssets/assets/151783497/385de32d-f815-4f9e-b409-b6856a433b5f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 127519
 cosmetic: 45858
 scriptlet: 18988
 html: 1723
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37547-134, 9m
  ublock-badware: 7991-15, 4m Δ
  ublock-privacy: 776-0, 4m Δ
  ublock-unbreak: 2304-0, 10m
  ublock-quick-fixes: 251-0, 10m
  easylist: 84038-755, 4m Δ
  easyprivacy: 50409-866, 10m
  urlhaus-1: 8930-0, 10m
  plowe-0: 3763-0, 10m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 190 ms (selfie)
 maxAssetCacheWait: 87 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  reclameaqui.com.br: 1
  amazon-adsystem.com: 1
  doubleclick.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 5
  id5-sync.com: 1
  navdmp.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by Freduser9** [comment]
Breakage: The questionnaires are not loading. Click on the questions

    https://www.reclameaqui.com.br/empresa/hiper-cap-brasil/

<details><summary>Screen</summary>

<img width="623" height="536" alt="Image" src="https://github.com/user-attachments/assets/62b738f0-7d3c-496f-b16c-26612cff9eb5" />
</details>

This filter helps to solve

```adb
@@||googletagmanager.com/gtag/js$script,domain=reclameaqui.com.br
```

**Comment by stephenhawk8054** [comment]
I don't understand. How should the site display?

**Comment by Freduser9** [comment]
When you scroll down the page, this box with the questions appears.

uBO disabled: Clicking on the questions loads the page to see the answers.

uBO enabled: Clicking on the questions does nothing.

<details><summary>Screen</summary>

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/3deb6a7c-dd2a-476c-8c00-d8591688acae" />

</details>

**Comment by stephenhawk8054** [comment]
@gorhill The issue is caused by their tracking `click` events on some `a` elements (which is why blocking `googletagmanager` breaks it):

<details>

<img width="2520" height="1607" alt="Image" src="https://github.com/user-attachments/assets/b16ad1d0-6612-4cbd-a8a7-75bf2b9f1437" />

</details>

React elements are really annoying. I can't remove `click` event on the `a[href]` elements using `aeld`.

If I type this in the console, it works:

```js
document.querySelectorAll("#faq-component-bp a").forEach(element=>{
  Object.keys(element).forEach(key=>{
    if (key.startsWith("__reactProps")){
      element[key]["onClick"] = undefined;
    }
  })
})
```

Could there be any scriptlets dedicated for React elements?

---

The site needs VPN to Brazil btw.

**Comment by Freduser9** [comment]
@stephenhawk8054 Sorry, could you tell me which filter you tried to use to solve this problem? Is this a temporary solution using this filter? `@@||googletagmanager.com/gtag/js$script,domain=reclameaqui.com.br`

**Comment by gorhill** [comment]
@stephenhawk8054 Sorry I missed following up on this one, I will look into it when time allows.

**Comment by stephenhawk8054** [comment]
Ok, I'll use `rpnt` in the meantime (for some reasons, using event `load` or `setTimeout` with delay 1000 and 2000 doesn't work for me so I have to use delay 3000)

```js
setTimeout(()=>{
  document.querySelectorAll("a[href]").forEach(element=>{
    Object.keys(element).forEach(key=>{
      if (key.startsWith("__reactProps")){
        if (typeof element[key]["onClick"] === "function" && element[key]["onClick"].toString().includes("preventDefault")) {
          element[key]["onClick"] = undefined;
        }
      }
    })
  })
}, 3000);
```

My idea is disabling the click event if matching text `preventDefault`.

**Comment by gorhill** [comment]
Would a scriplet which wholly remove `__reactProps...` work? I did try on the first question and the link still worked. I could add a generic `remove-element-property` which would take a selector and a pattern for the property(ies) to remove (or reset if they are inherited instance properties) -- something like:

    reclameaqui.com.br##+js(remove-element-property, #faq-component-bp > a[href]:has(.faq-title), /^__reactProps/)

**Comment by stephenhawk8054** [comment]
I guess in this case it's fine. Removing whole `__reactProps` might cause issues for sites that embed more functions inside but I think we can wait for other reports.

**Comment by gorhill** [comment]
In version 1.71.1b5, you can now create filters such as:

    reclameaqui.com.br##+js(edit-element-object, #faq-component-bp > a[href]:has(.faq-title), v2:$[?$.onclick=/preventDefault/].$./^__reactProps/.onClick, 10000)

I didn't try the filter since I am not able to find an element matching `#faq-component-bp` at the URL in opening comment.

Some explanation regarding the json path: In latest commits, I have been working on ensuring that the jsonpath code in uBO is conform with official [https://www.rfc-editor.org/info/rfc9535/](rfc9535) -- the idea is that this way the documentation, and also available online tools (i.e. <https://jsonpath.com/>) can be used to craft working jsonpaths for uBO/uBOL.

However the changes broke compatibility with how the old code was compiling/interpreting jsonpaths, so to use the better conforming syntax, we need to prefix with `v2:`. Long term I would like to drop the old syntax compatibility sunct that eventually the prefix can be dropped.

One mistake I made in the legacy syntax was to think that expressions (`[?...]`) were just tests, while they really are lookup operations for matching properties in official spec.

The official spec doesn't allow to test for the presence of properties in one path in order to lookup properties in a another path. To address this while keeping conformance as best as possible, I added an extension to the syntax: the ability to chain jsonpath queries through reusing the root element specifier `$` anywhere in the query. This is used in the above query.

Of course regex-based property lookup is not also part of the spec, so this is another extension. Regex-based selectors can be used wherever a normal bracket notation or dot notation identifier can be used.

The delay parameter in the above filter (10000) is a guess value of how long the filter should try to do its work, typically react-based pages are doing a lot of work before the conditions become present for the filter to be applied.

One thing that would be good is to start converting legacy syntax to the new syntax using `!#if ext_devbuild` blocks to ensure the new syntax is really well tested so that I don't end up publishing a new release with unforeseen defects.

**Comment by Freduser9** [comment]
`https://www.reclameaqui.com.br/`

Ad space, more appears as you scroll down the page
<details><summary>Screen</summary>

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/eb274288-e0bf-4076-9103-e3849b56ffbd" />
</details>

### Country
Brazil

### Configuration
<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.73.0
Firefox: 154
filterset (summary):
 network: 182909
 cosmetic: 48568
 scriptlet: 35396
 html: 3779
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 53946-72, 1m
  ublock-badware: 10194-17, 1m
  ublock-privacy: 4121-2, 1m
  ublock-unbreak: 2865-1, 1m
  ublock-quick-fixes: 503-13, 1m
  easylist: 86284-139, 1m
  easyprivacy: 56398-43, 1m
  urlhaus-1: 47235-11, 1m
  plowe-0: 3516-1035, 1m
  spa-1: 7143-88, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5196 ms
 maxAssetCacheWait: 534 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  reclameaqui.com.br: 8
  cloudflareinsights.com: 2
  doubleclick.net: 1
  id5-sync.com: 1
 extended:
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#div[id^="div-gpt-"]
  #@#[id^="div-gpt-ad"]
  ##+js(trusted-replace-node-text, script, !function, 'setTimeout(…
  ##+js(prevent-clipboard-write, /^mshta |^msiexec |^(bash <<<|cur…

```

**Comment by gorhill** [comment]
This works for me:

    reclameaqui.com.br##.hidden.lg\:block:has([component-export="GoogleBannerTooltip"])
    reclameaqui.com.br##[component-url*="FixedAdBannerContainer"]

**Comment by playonevideo** [comment]
@Freduser9 leftovers/ads from Portuguese sites should be reported to AG in the future:
https://reports.adguard.com/en/new_issue.html

**Comment by Freduser9** [comment]
@playonevideo Oh, okay, sorry. Could you tell me the difference between reporting to EasyList and to AdGuard?

**Comment by playonevideo** [comment]
On EasyList it takes a lot longer when it comes to ad leftovers and such to fix them, but AdGuard is a company and they address the problems with Portuguese sites.

EasyList generally fixes ads on English-language sites.

**Comment by gorhill** [comment]
> Could you tell me the difference between reporting to EasyList and to AdGuard?

The Portuguese regional list used by uBO/uBOL is "AdGuard Spanish/Portuguese", it's not maintained by EasyList.

**Comment by playonevideo** [comment]
A question: why there is also EasyList Spanish as well? Looks like there are two lists for Spanish websites available to use.

Sorry if it's off-topic.
