### ISSUE TITLE
Filter for wikipedia nag?

### ISSUE THREAD

**Issue by paulri** [uBlockOrigin/uAssets#232]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[en.wikipedia.org]`

### Describe the issue

When I browse a wikipedia page, I often get the new nag that has started in the last month or so, as can be seen in the screenshot linked to below.

I have tried to use ublock Origin to block the element through the context menu; I have done this several times. Each time, Ublock prevents the nag from appearing when I reload the page, but the next time I visit wikipedia, the nag appears.

### Screenshot(s)

Screenshot here: http://imgur.com/a/yYQQB

### Versions

Pale Moon 27.0.2
- uBlock Origin version: 1.10.2

### Settings

- [I am not sure about any changes of mine, but I only have 2 filter sets running: Easy List and malwaredomains.com]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by IDKwhattoputhere** [comment]
Fanboy’s Annoyance List‎ should block this. The filters I see being applied are these:
`wikipedia.org###centralNotice`
`wikipedia.org###siteNotice`

**Comment by Hrxn** [comment]
FYI:
![pic1](https://cloud.githubusercontent.com/assets/12064918/21257641/8345d500-c379-11e6-9a7a-57f22ede9267.jpg)

`div#centralNotice` might be a bit too unspecific or too generic, maybe. I don't know how that has been used in the past, but if they want to make an announcement about some really important stuff, you won't see it with that element being blocked. 😄 

In this case you can get rid of that thing shown in your screenshot by just blocking `div#WMDE_Banner`.

But keep in mind that they use some script in their pages to determine your location (IP-address based) and show different nag banners accordingly.

So I assume the `id` won't be `WMDE_Banner` in your case, mabe `WMUK_Banner` etc. I think you get the idea.

But, the really important thing is:

You can use the integrated Element picker to find the right target and block it with just one click, as documented here: 
https://github.com/gorhill/uBlock/wiki/Element-picker

**Comment by paulri** [comment]
Hrxn, thanks, but I've tried using uBlock's element picker on more than one occasion, and then previewed it so that the nag didn't show---but sure enough, I saw it again. So I think I will use the Annoyance filter.

**Comment by gorhill** [comment]
> sure enough, I saw it again

[The removed element reappears when you reload the page?](https://github.com/gorhill/uBlock/wiki/Element-picker#the-removed-element-reappears-when-you-reload-the-page)

**Comment by IDKwhattoputhere** [comment]
Most of the time there are multiple entries in the element picker that you can try. One of them should work. Or maybe you have deselected "My Filters" in the filter list pane? Would be silly but happened to me before.

**Comment by gorhill** [comment]
> Would be silly but happened to me before.

[Me too](https://github.com/chrisaljoudi/uBlock/issues/616#issuecomment-71668366).

**Comment by uBlock-user** [comment]
Just use `wikipedia.org###siteNotice` that takes care of it on all domains. Once added, the nag never appeared again.

**Comment by Hrxn** [comment]
Well, I have used the Element picker, as described, and that nag banner never appeared again so far.

But keep in mind that the filter which gets created this way is domain-specific (including sub-domains etc.) of course.

I.e. `en.wikipedia.org......` for example, but you can just edit this line, or add another line just like this and change the language prefix. `*.wikipedia.org...` should work as well, in theory.

But I somehow doubt that anyone really uses all language versions of Wikipedia in existence 😄

**Comment by gorhill** [comment]
> `*.wikipedia.org`... should work as well, in theory

No.

`wikipedia.org` would.

**Comment by uBlock-user** [comment]
Cosmetic filtering on the main domain, applies to all sub-domains if any.

**Comment by Hrxn** [comment]
You guys are right about the syntax, obviously. Sub-domains are included implicitly.
I was to lazy to check 😉 

Regardless, my initial point was that the filter created by the Element picker is for the full specific domain (as it should).
I.e. this one in my case:
`en.wikipedia.org###WMDE_Banner`

Now you can either add
`fr.wikipedia.org###WMDE_Banner`
`de.wikipedia.org###WMDE_Banner`
(etc. pp.)
or change it to
` wikipedia.org###WMDE_Banner`

No need to activate the full Fanboy's Annoyance list 😄 
_(Point about the element id still stands nonetheless)_`
<hr>

Anyway, this little anecdote here
> [..] Or maybe you have deselected "My Filters" in the filter list pane? Would be silly but happened to me before.

had me an idea. Because, if my memory doesn't fail me, we had seen similar issues before, where users complained about problems after "accidentally" disabling cosmetic filtering from the settings pane or the filter list overview, for example. 
So, what do you think about some small indicator for the popup UI?

![](https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/popup-1.png)

Just an additional icon, or another kind of indicator, at the bottom, for example, that is shown or highlighted whenever an unusual setting is active, like the aforementioned 'My filter' switch or another change from the default settings. Benefit is, it would be directly obvious from one simple glance where the issue might be. 
Anyway, just a silly little suggestion..
