### ISSUE TITLE
modrinth.com: ads

### ISSUE THREAD

**Issue by Zephiii** [uBlockOrigin/uAssets#24130]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://modrinth.com/mod/more-furnace-variants-lieonlion/version/1.0.2+1.20.4-Fabric`

### Category

ads

### Description

Numerous mods hosted on the site have ads for server hosting companies injected into the descriptions by the mod authors. It's difficult to reliably block these.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="601" alt="Screenshot 2024-06-17 at 00 18 36" src="https://github.com/uBlockOrigin/uAssets/assets/93544652/8858fb63-7fdb-42d0-a11f-0ef9c2a379b4">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 117
filterset (summary):
 network: 140090
 cosmetic: 73336
 scriptlet: 22396
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30084-35, now
 default:
  user-filters: 90-0, never
  easylist: 86897-572, now
  easyprivacy: 51057-639, now
  plowe-0: 3552-0, now
  ublock-badware: 9229-0, now
  ublock-filters: 38531-278, now
  ublock-privacy: 929-0, now
  ublock-quick-fixes: 97-0, now
  ublock-unbreak: 2339-0, now
  urlhaus-1: 14695-0, now
filterset (user): [array of 92 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 477 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 61
 network:
  doubleclick.net: 18
  google.com: 21
  youtube.com: 22
 extended:
  ##.GBBNWLJVGRHFLYVGSZKSSKNTHFYXHMBD
  ##a[rel*="sponsored"]:upward(.normal-page__content > div)
```
</details>

**Comment by dportvine** [comment]
> It's difficult to reliably block these.

```adblock
modrinth.com##.markdown-body > p > [href][rel$="ugc"]:has(img[src*="/images/banners/"])
||raw.githubusercontent.com/*/images/banners/*banner$image

**Comment by Yuki2718** [comment]
Other patterns:
```
https://modrinth.com/mod/not-enough-animations
https://modrinth.com/mod/entitytexturefeatures
https://modrinth.com/mod/modernfix
https://modrinth.com/mod/moreculling
```

I prefer fixing in our lists, EL doesn't use `nth-of-type`.

**Comment by RemagOfficial** [comment]
these ads or whatever you like to call them are one of the very few ways for mod and modpack developers to actually earn something for making their content, as a small developer myself I'd rather not have my literal only good income source from my projects to just be hidden because some guy dislikes a particular Minecraft server host

**Comment by Bennyboy1695** [comment]
Honestly not a fan of these being blocked. Not only would i personally not consider them an ad because they do nothing unless you are already planning on getting a server. But the person advertising it doesn't even make money of you clicking it like evey other ad does.
Also the way this was blocked feels so targeted. This guy got mad on that exact mod makers page about the banner and then came and got it blocked.

**Comment by tr7zw** [comment]
As the mod author of one of the called-out pages (``https://modrinth.com/mod/not-enough-animations``) and a longtime uBlock user... Don't do this. The likelihood that this just breaks mod pages because the filter catches some normal banner/infographic as an "ad" is not worth the effort. These images are also not linked from some ad network, so there isn't even a privacy concern.

**Comment by hypherionmc** [comment]
These companies go out of their way to provide free resources to developers, who need it. Our banners are NOT intrusive, and nobody is forcing you to click on them.

Us showing support for the companies that back is, is only fair. This is also not an ad, but rather a coupon for the user who chooses to click on it

**Comment by Dysth** [comment]
As repeated above, this is disastrous for the modding community and will have long term negative effects. This is the only way mod authors can be paid for their work outside of shoving Patreon links in your face. If they can't get it this way, they'll be injecting it into their mods directly soon enough in the form of text-based announcements or hogging up a server slot because a couple users are upset over an image with a link. They are not injected with any creepy tracking- it's literally an image with an affiliate link ie bisect.com/modauthernamehere

**Comment by Fluboxer** [comment]
If this image does not interrupt using mod page then it should not be blocked

I do believe that if you shove it in front of everything and ad is first thing I see on your mod page then you do deserve to be adblocked tho. Put it at the end of description like civilized people

**Comment by qtlunya** [comment]
It's a bit crazy that you're considering stopping using an ad blocker because it blocks ads.

If it's at the end, I would say it's acceptable. But some of these mods literally have banners inserted in the middle of their descriptions. For a lot of people this is unwanted cruft as we have no plans to buy a server anyway.

What next, are you going to demand that uBlock Origin stop blocking YouTube ads because "think of the creators"? People who are interested in such promotions can simply whitelist Modrinth in their ad blockers.

**Comment by hypherionmc** [comment]
The main problem with this is not just that Ublock is blocking the "ad", it's literally blocking ANY image you put at the bottom of your description, so if there was anything other than an ad there, it would be removed as well.


That being said, yes I agree that some authors go WAY overboard on their banners. I have personally seen a few pages that contain multiple sponsor banners

**Comment by MundM2007** [comment]
Adding to this, it's also not really needed. Most people use custom mc launchers to download and Install mods and modpacks. These also aren't blocked.
Also there at the entire bottom of the page where it's the last thing you see. Most don't even scroll that far I would say. 
This also destroys mod and modpack pages completely as there other Bbnners aswell as stated above.
As others has stated this is an Importamt source for income, and without it development would probably be way slower for mods and modpacks. And as an example makes up around 85% of what I make as a modpack dev.

**Comment by MundM2007** [comment]
> The main problem with this is not just that Ublock is blocking the "ad", it's literally blocking ANY image you put at the bottom of your description, so if there was anything other than an ad there, it would be removed as well.

Also there are Projects that Just use a single Image for Thier entire description Just completely removing it.

**Comment by FxMorin** [comment]
Im the developer of MoreCulling, which was also mentioned. Personally nobody has ever used my referral, and honestly I don't mind if people want to remove the ads themselves. 
However having this just be the default, which now makes it so I can't even see my own banner. Is just weird and feels pretty targeted.

**Comment by qtlunya** [comment]
Where is the source for this breaking other images? The proposed addition might have, but the [actual rule](https://github.com/uBlockOrigin/uAssets/commit/088808a90ce6ab24724664879dde81dc96d82668) that was added to uAssets is targeting a specific banner.

**Comment by hypherionmc** [comment]
As a test:

With ublock enabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/63595580/3b3819a1-beaa-4e2c-9088-07b7cb8db8f8)

Without block:
![image](https://github.com/uBlockOrigin/uAssets/assets/63595580/f7b16d3b-c4bc-427d-8fc6-33fdbac6220d)

**Comment by CodexAdrian** [comment]
> It's a bit crazy that you're considering stopping using an ad blocker because it blocks ads.
> 
> If it's at the end, I would say it's acceptable. But some of these mods literally have banners inserted in the middle of their descriptions. For a lot of people this is unwanted cruft as we have no plans to buy a server anyway.
> 
> What next, are you going to demand that uBlock Origin stop blocking YouTube ads because "think of the creators"? People who are interested in such promotions can simply whitelist Modrinth in their ad blockers.

Whitelisting is realistically not something most people using ad blocker would think to do. Besides that, I would never expect ublock to block sponsored segments in the middle of a video, just like I would not expect it to remove banners placed there by an individual creator. I wouldnt even think to check whether or not ublock is blocking individual creator banners. This issue was created by someone who has been targeting multiple creators demanding they remove their banners in even the most reasonable cases of just having the banner at the bottom. Please consider rolling back this change

**Comment by Fluboxer** [comment]
Kinda clueless question

If ublock has power to block most bottom image AND it has power to block any image with link in it (I believe it can block specific links only too) then why not just do it like this?

Creators keep their money, but only if they do it proper way instead of shoving it in middle of useful information 


> If this image does not interrupt using mod page then it should not be blocked
> 
> I do believe that if you shove it in front of everything and ad is first thing I see on your mod page then you do deserve to be adblocked tho. Put it at the end of description like civilized people

**Comment by Bennyboy1695** [comment]
> Whitelisting is realistically not something most people using ad blocker would think to do. 
This part is so true. I didn't even realize that these banners were being blocked until i saw it mentioned in a discord channel went and checked a page i knew had one and it was gone. If someone doesn't know something is missing how are they even meant to whitelist it.
Also theres so many server that sponsor mods this exact same way and they aren't being blocked. Why is bisect being targeted over other server hosting company. Even more so when most of these other servers really shove it down your throat whereas bisect literally just ask partners to put that single banner to keep their partnership

**Comment by FxMorin** [comment]
> Also theres so many server that sponsor mods this exact same way and they aren't being blocked. Why is bisect being targeted over other server hosting company. Even more so when most of these other servers really shove it down your throat whereas bisect literally just ask partners to put that single banner to keep their partnership

Actually Kinetic hosting is also being affected, check the [moreculling](https://modrinth.com/mod/moreculling) page

**Comment by FxMorin** [comment]
Good luck blocking my banner: [https://modrinth.com/mod/moreculling](https://modrinth.com/mod/moreculling)

**Comment by tr7zw** [comment]
> Blocking "ads" in user content is in general a horrible idea.

Because if we start with that, what about all the Forums, what about people "advertising" for JProfile/YourKit/IDEA IntelliJ etc etc etc in the GitHub readme of their projects? (For example here https://github.com/PaperMC/Paper ). Blocking in user content is a bad idea and uBlockOrigin shouldn't waste time with that.

**Comment by kreezxil** [comment]
I can't help but think of this scenario:
```
[thisguy and his mates are walking down the street]

thisguy: no what I hate more than anything?

hismates: what? *cringe*

thisguy: ads, they're everywhere! like here on this restaurant wanting us to come in and try a burger for $3 off today only. Gah, I"m not going in there now, because they're tryna tempt me. And there, that jewelry store, no way man. I don't care if an engagement ring is 20% off in the month of June. They advertised and now I'm not going in there.

[somedude behind them]

somedude: you do realize you're advertising your hate for ads to everyone
```

**Comment by lupiiiin** [comment]
It is very sad that you made this request, for many of us, promotional banners are our MAIN source of income. Without them, we simply would not be able to dedicate the time we currently do.

**Comment by omo50** [comment]
As a modpack developer, blocking things like this *really* hurts any ability for me or many others to make a form of revenue for hours and hours of work.

As a small developer who really doesn't make much anyway, I'd like to have my source of income not killed just cause somebody doesn't like the banners.

**Comment by tr7zw** [comment]
https://github.com/uBlockOrigin/uAssets/commit/088808a90ce6ab24724664879dde81dc96d82668#diff-7e8bc78cc2c2639fe0ddbd1757385b890c8518005342180ca4ce212422b2da06R2116

This is a hardcoded link to my domain via the modrinth proxy... To drive the point home, I just added an extra / into the url, and now its showing again. Could also move the image to GitHub/any other image hoster to break this. Filtering user content is a bad idea and a waste of time.

**Comment by Lenuilu** [comment]
I believe these links should not be blocked using an ad blocker as they are the main source of revenue for small creators, these affiliate links are not built in ad widgets. They are put in descriptions as they are usually the main source of revenue for these small creators. I feel its a big nono to block ads inside of a description that isnt hardcoded into the website

**Comment by FxMorin** [comment]
^ This is our petition

**Comment by P10Ms** [comment]
> Good luck blocking my banner: https://modrinth.com/mod/moreculling

you're a legend

**Comment by nanopone** [comment]
blocking images that people put in their mod description is not ubo's job and the implementation is bound to fail. if the user wants to add their own filters, they can, but blanket removing images at the bottom of mod descriptions by default is insane. this is akin to deleting the first line of a youtube video description, because people "sometimes put ads there". if an extension like a sponsorblock were to crowdsource examples of *actual* sponsor banners to remove, that's a different story.

this is user generated content, something that ubo doesn't usually block because it can't reliably do it.

**Comment by sudoBash418** [comment]
> Good luck blocking my banner: https://modrinth.com/mod/moreculling

```
modrinth.com##a[href^="https://client.kinetichosting.net"]
```
(ofc it can just be bypassed using a link shortener, making the experience worse for everyone involved)

As a longtime uBlock Origin user, I agree that blocking "user-generated" content in this manner (by default) is not a good idea, and breaks the expectations of end-users.
These rules have already broken pages (blocking non-advertisement images), and have little-to-no privacy impact.

If there is significant demand for rules blocking user-generated content, I believe they should go in a non-default ruleset.

**Comment by lexd0g** [comment]
while i agree this is a poor implementation that should be resolved. i do think uBO should find another way to block these ads. going by the readme on this repository, uAssets follows the [same guidelines as EasyList](https://easylist.to/pages/policy.html), and i don't see anything that specifies a distinction between ads added by the website or by third parties (please correct me if i'm wrong).

i disable my adblocker on modrinth as i appreciate the unobtrusiveness and revenue sharing. but trying to block ads whether or not they're obtrusive or not is how you end up with the shitshow that is AdBlock Plus' Acceptable Ads program, the choice should be up to the user.

**Comment by Lenuilu** [comment]
> while i agree this is a poor implementation that should be resolved. i do think uBO should find another way to block these ads. going by the readme on this repository, uAssets follows the [same guidelines as EasyList](https://easylist.to/pages/policy.html), and i don't see anything that specifies a distinction between ads added by the website or by third parties (please correct me if i'm wrong).
> 
> i disable my adblocker on modrinth as i appreciate the unobtrusiveness and revenue sharing. but trying to block ads whether or not they're obtrusive or not is how you end up with the shitshow that is AdBlock Plus' Acceptable Ads program, the choice should be up to the user.

The links and images are put up by the user, and user generated content should not be blocked by an adblocker. That's where I stand on this issue

**Comment by tr7zw** [comment]
> while i agree this is a poor implementation that should be resolved. i do think uBO should find another way to block these ads. 

There is no pattern to what is an "ad" and what isn't. Just blocking images with links is also not an option. This just doesn't work. You can spend hundreds of hours manually adding filters, just for them to break in a day when the person notices and just changes the URLs. Doesn't help that this current implementation blocks people's Discord/Patreon/Kofi buttons on pages that don't even contain an "ad".

**Comment by sudoBash418** [comment]
> while i agree this is a poor implementation that should be resolved. i do think uBO should find another way to block these ads.

I'm not sure a good technical solution exists; generic rules are likely to break non-advertisement content, and specific rules are going to be difficult to keep up-to-date, considering the >10000 projects hosted on Modrinth.

Additionally, there is a very real risk that projects or developers are specifically targeted as a form of harassment (parts of the Minecraft community can be... less than excellent :/).

> [...] the choice should be up to the user.

Agreed. The question is, should blocking user-generated content be enabled or disabled *by default*?

Note that, at least on Modrinth, simply blocking all 3rd-party resources gives the user the choice to block all user-generated images (the site itself as well as user-generated text loads fine).
