### ISSUE TITLE
uBO skips specific filter cause ads not blocked

### ISSUE THREAD

**Issue by procesx** [uBlockOrigin/uAssets#246]
### URL(s) where the issue occurs

`bbs.imoutolove.me`
`bbs.north-plus.net`
`bbs.soul-plus.net`
`www.soul-plus.net`

### Describe the issue

uBO does not apply the filter from EasyList China and 3 ad banners are still at the top of web page.

`/images/men$domain=106.185.27.133|imoutolove.me|north-plus.net|soul-plus.net|soul-plus.org`

### Versions

- Browser/version: Firefox 45.6.0
- uBlock Origin version: 1.10.4

### Settings

- Default settings with EasyList China

### Notes

ABP can apply the filter.

**Comment by gorhill** [comment]
By design. A trailing wildcard must be used to indicate that the trailing keyword should not be used as a token:

    /images/men*$domain=106.185.27.133|imoutolove.me|north-plus.net|soul-plus.net|soul-plus.org

See discussion regarding leading/trailing wildcards in uBO: <https://github.com/gorhill/uBlock/issues/1065#issuecomment-197350759>.

best would be for author of EasyList China to use trailing wildcard above, this will create a filter which works for both uBO and ABP.

**Comment by procesx** [comment]
Thanks. The filter has been modified.
[M:http://north-plus.net/index.php](https://hg.adblockplus.org/easylistchina/rev/8cde55af28ae)
