### ISSUE TITLE
Phishing domains

### ISSUE THREAD

**Issue by cOnRiTCh** [uBlockOrigin/uAssets#24604]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
onenightchicko.com
singleflirt.com
casualdating1.com
info-flirtme.com
info-milfroom.com
```

### Description

These domains are phishing and scams, pretending to be dating sites.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by CoolestGuy94** [comment]
This should be solved by anti-viruses and their browser extensions, not by uBlock Origin. :-)

**Comment by CoolestGuy94** [comment]
> uBO has a [badware list](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt) for this very reason

Sorry, forgot this list existed. Still, I don't find anything _phishy_ about those websites.

**Comment by stephenhawk8054** [comment]
Phishing domains need to be based on what exact legitimate websites / entities they are based on. PLEASE report exactly what those legitimate entities are as well.

If not, PLEASE give exact articles or reports about these sites so we can make decisions based on that. How many times should I repeat this to you?

We used to block a "fake dating site" reported by a user without any other reports about this. Then we received a serious complaint from the website owner, and we indeed didn't have any evidence to block it. uBO dev is the one that will have to face many complaints and responsibilities about these. Reporters just like to mass-report without caring about any responsibilities.

**Comment by stephenhawk8054** [comment]
Both of the 2 reports above are about scamming. Currently we don't address scamming as said here:

https://github.com/uBlockOrigin/uAssets/issues/24503#issuecomment-2235195318

> It's just that 95% of all phishing websites, don't have an article or a report, and are very hard to provide evidence.

Please note that, phishing and scamming are different. Phishing is based on what legitimate entities they want users to believe that they are. And sometimes it's easier to detect without the need for any hard evidences about it (for example crypto currencies claiming they are from Tesla).

Scamming, in many cases, doesn't need to base on any legitimate entities, and therefore it's a gray area that uBO can easily receive serious issues if blocking incorrectly. Shutting down the project can also be a possibility because of this. Just imagine you are defending the decisions yourself in front of the website owners, instead of letting uBO team do it for you.

> I could not find anything for the 3rd and 4th ones, but [the domain from my other post](https://github.com/uBlockOrigin/uAssets/issues/24602) redirects to them sometimes.

Then please report EXACTLY what links redirect to it in that thread. Remind that we ALWAYS need to reproduce the issue. Don't assume we can read minds and know how to reproduce the issue magically.

**Comment by stephenhawk8054** [comment]
> a desire to contribute to a cleaner and safer web

Yes, we understand and we also want it too. It's just that since it's a public project, blocking a whole website in Badware list is a serious decision that will deploy to milliions of uBO users. Incorrect blocking in that list is not what we can 100% assure and we won't expect that from any volunteers, contributors or reporters, but the better the report process is, less false positives chance will happen. Thanks for understanding.

---

You can continue in the previous issue thread if there are domains related to that.
