### ISSUE TITLE
anti-adblock[2018/6/25]

### ISSUE THREAD

**Issue by weijen6** [uBlockOrigin/uAssets#2659]
chrome : 67.0.3396.87 x64
uBlock Origin v1.16.10

```
https://unlockvungtau.com/
http://www.gsm-solution.com/
https://mygoroot.com/
https://www.filehorse.com/download-kingo-android-root/
http://cloud.fw27.xyz

```

**Comment by garry-ut99** [comment]
Ad placeholders caused by `ghide` from "uBlock Filters":
Example subpage `https://www.gsm-solution.com/2021/07/frp-bypass-helper-to-open-setting.html` : [SCREENSHOOT 1](https://user-images.githubusercontent.com/72945564/216469447-e8d5995c-ac2f-40d0-a7df-11404f4d781f.png)
Main page: `https://www.gsm-solution.com/` : [SCREENSHOOT 2](https://user-images.githubusercontent.com/72945564/216469441-8b85c6f4-b904-41ef-a78a-959fcd3c68d3.png)
