### ISSUE TITLE
codeproject.com, html.net

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#271]
### URL(s) where the issue occurs

`https://www.codeproject.com`
`http://html.net`

### Describe the issue

Both websites pull a huge amount of requests, including some ads via
`http://dm.html.net/dm` and 	`https://dm.codeproject.com/dm`
### Screenshot(s)

![code](https://cloud.githubusercontent.com/assets/16838044/22169455/7ede6880-df74-11e6-8295-cb23f5c50b1c.PNG)

### Versions

- Browser/version: Chrome 55
- uBlock Origin version: 1.10.4

### Settings

- default

### Notes

Simply blocking `http://dm.html.net/dm` results in a redirect to `http://html.net/contentcontrol.html`
Adding
`codeproject.com,html.net##script:inject(abort-on-property-write.js, _sp_)`
solves the issue.

**Comment by okiehsch** [comment]
`familyhandyman.com`, `headlinepolitics.com` and `wwd.com` have the same issue and fix.

**Comment by uBlock-user** [comment]
similar anti adblock found on `nj.com`, `nola.com`, `demorgen.be`

**Comment by gwarser** [comment]
Is this still working properly? [Brave Browser test](https://brave.com/memory-savings-in-brave/) mentions memory problems caused by uBO not blocking tracking subframes. `sfgate.com` and `boston.com` seems to be Instart, `nypost.com` looks like this issue.

Question on reddit: https://old.reddit.com/r/uBlockOrigin/comments/bk4dm8/block_tracker_within_subframe/
