### ISSUE TITLE
googletagservices script error on doodle.com

### ISSUE THREAD

**Issue by ghostwords** [uBlockOrigin/uAssets#277]
### URL(s) where the issue occurs

`http://doodle.com/create`

### Describe the issue

Fill out the title, name and e-mail fields (can put in anything that validates), click Next. The form fails to proceed due to the following exception: `Uncaught TypeError: Cannot read property 'getSlotElementId' of undefined(…)`.

### Versions

- Browser/version: Chrome Version 54.0.2840.100 (64-bit)
- uBlock Origin version: 1.10.4

### Notes

Looks like the [`googletagservices.com/gpt.js` scriptlet](https://github.com/uBlockOrigin/uAssets/blob/257f936a0f01ad824dd7cb34dce215f60e34161a/filters/resources.txt#L319-L444) needs something like the following:
```javascript
      gpt.slot_manager_instance = {
        find: function() { return new Slot(); }
      };
```
However, at first glance, I didn't see any GPT documentation on this functionality.

**Comment by gorhill** [comment]
I find a reference to `slot_manager_instance` in the script loaded from `//securepubads.g.doubleclick.net/gpt/pubads_impl_108.js` when `//www.googletagservices.com/tag/js/gpt.js` is not blocked.

However `pubads_impl_108.js` is blocked by uBO, and yet the `slot_manager_instance` issue does not occur if not blocking `gpt.js`. I believe this is because the site's code rely on `window.googletag.pubadsReady` to decide the code path. This property is set to `true` by the surrogate script. Probably would fix the issue if it was set to `false`.

Not sure at this point whether the better fix is to add `gpt.slot_manager_instance` or to set `window.googletag.pubadsReady` to `false`.
