### ISSUE TITLE
imaginetricks.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2778]
URL(s) where the issue occurs

`https://www.imaginetricks.com/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.12

Settings

Default

**Comment by garry-ut99** [comment]
Ad placeholders caused by `ghide` from "uBlock filters".
Example subpage: `https://www.imaginetricks.com/android-emulator-for-pc-windows-1087vistaxp-and-mac/`
Example ad placeholder (here full [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/216777750-41d5ce07-c879-473b-8860-57245eeb5a69.png) shootage)
![example](https://user-images.githubusercontent.com/72945564/216777540-aa6a3470-5d62-4882-9c52-9adf94f964ed.png)
