### ISSUE TITLE
Add Adguard Simplified domain names filter in 3rd-party lists

### ISSUE THREAD

**Issue by ddraws** [uBlockOrigin/uAssets#279]
Please consider adding Adguard "Simplified domain names filter" to the Multipurpose section of uBO's 3rd-party filters.

Description of the filter list "Filter composed from several other filters (English filter, Social media filter, Spyware filter, Mobile ads filter, EasyList and EasyPrivacy) and simplified specifically to be better compatible with DNS-level ad blocking."

Support URL is most likely `https://github.com/AdguardTeam/AdguardDNS`.

Links -
```
https://raw.githubusercontent.com/AdguardTeam/AdguardDNS/master/Filters/filter.txt
https://filters.adtidy.org/extension/chromium/filters/15.txt```

**Comment by gorhill** [comment]
i do not understand the purpose of these two exception filters:

    @@||cedexis.net^
    @@||licdn.com^

The first one cancels the block filter `||cedexis.net^` present in the same file, so what is the point of having the block filter in the first place?

The second one is an exception filter which should not be needed since nowhere in the file `licdn.com` is declared.

In short these two unneeded exception filters could interfere with block filters in other filter lists.

**Comment by Snapy** [comment]
@gorhill The file is built automatically using domain names from several filer lists. They are leftovers from when the process was changed some time ago to not include domain which require exceptions. So it's a bug that needs to be reported (@ameshkov).

**Comment by collinbarrett** [comment]
I don't mean to hijack this Issue, but I just wanted to let @ddraws know that I do have that list indexed on FilterLists on the [Combo](https://filterlists.com/combo/) page. If folks want to try adding it manually during testing, that could make it easier.

**Comment by ameshkov** [comment]
Hi, guys! We generally do not recommend using this filter in regular ad blockers like Adguard or uBlock or whatever. It is optimized for DNS-level ad blocking and is too "rough". Moreover, the filter is compiled from regular filters (Adguard English filter, EasyList, EasyPrivacy, etc), you can have better results just by using those filters.

@gorhill 
> I do not understand the purpose of these two exception filters:

As I recall, they are necessary to fix the linkedin app. However, in this particular case, it'd be better to simply remove corresponding rules from the DNS filter instead of having an explicit exception rule: https://github.com/AdguardTeam/AdguardDNS/issues/124

Btw, having those "wide" exceptions rules is one of the reasons why we don't recommend using this filter in regular ad blockers.

**Comment by gorhill** [comment]
@ameshkov Thanks for the feedback.

> Moreover, the filter is compiled from regular filters (Adguard English filter, EasyList, EasyPrivacy, etc), you can have better results just by using those filters.

Consequently, closing this issue as "declined".
