### ISSUE TITLE
Washington Post paywall

### ISSUE THREAD

**Issue by avengah** [uBlockOrigin/uAssets#2792]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

Any wapo url apart from the homepage, e.g. `https://www.washingtonpost.com/world/china-fires-back-at-us-tariffs-vows-to-defend-its-core-interests/2018/07/06/f42fc812-8091-11e8-a63f-7b5d2aba7ac5_story.html`, after you've viewed 5 pages.

### Describe the issue

A paywall box appears on the screen, and the URL in the address bar is changed to the homepage. Zapping the element doesn't work, as the article has been truncated. If you hit ESC at the right time (just before the address changes), you can stop the paywall activating without having to use an incognito window.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/285430/42380957-88359128-8127-11e8-8367-467a4be36df5.png)

### Versions

- Browser/version:

Google Chrome | 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | a337fbf3c2ab8ebc6b64b0bfdce73a20e2e2252b-refs/branch-heads/3396@{#790}

- uBlock Origin version: Nano Adblocker 1.0.0.55, Nano Defender 15.0.0.5

### Settings

- None

### Notes

Using an incognito window is annoying because you have to go through the GDPR warning again, and it only lasts for 5 pages before you need to close the window and start again. Hitting ESC before the address changes will stop the paywall and allow you to read the article, but the timing is very tight and comments can't be read on the article. I wonder if it's possible to have the paywall script stopped as a matter of course in Nano Defender? Thanks.

EDIT: I found this: https://greasyfork.org/en/scripts/38567-washington-post-paywall-bypass - it works as a temporary stopgap but it means I need TamperMonkey running. I guess I'm hoping for this to be implemented in Nano directly so I don't need to also have TamperMonkey for one script.

**Comment by zaphodbeebblebrox** [comment]
uBlock does not attempt to circumvent paywalls. If you report it to nanoAdblocker/NanoFilters, you might get it fixed.

**Comment by jspenguin2017** [comment]
My current policy is if the "paywall" breaks when JavaScript and/or cookies are disabled, then it *might* be removed in the annoyance filter. 

I don't think client side JavaScript can be used to implement DRM systems because JavaScript is open source by nature. That is why there are Widevine, PlayReady, etc. But OK, some people may argue that heavily obfuscated JavaScript can be considered "binary". Let's just say you can implement DRM in JavaScript, for it to be a valid DRM, it should not be bypassable by accident. Some people can have JavaScript and/or cookies disabled by default, and that would break the paywall. For this reason, I sometimes remove those fake paywalls as annoyance. 

For uAssets it's obviously up to gorhill, but those fake paywalls are not DRM, and you can remove them just like ads.

**Comment by okiehsch** [comment]
@avengah see https://github.com/uBlockOrigin/uAssets/issues/2317#issuecomment-391851786 and the following discussion.
FYI adding `washingtonpost.com##script:inject(abort-on-property-read.js, WpPwapi2)`
to your filter list should work

**Comment by avengah** [comment]
Thanks! Yeah, I wasn't entirely sure this was the right program or category but no matter; thanks for the help!
