### ISSUE TITLE
currencio.co

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#2810]
![2018-07-10-eth to usd converter _ ethereum price in usd currencio](https://user-images.githubusercontent.com/5884000/42491858-da091226-8416-11e8-84a4-e1c084c0bb6e.png)
`https://currencio.co/eth/usd/`

AD

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.12
 ND 14.58
 Chr 67.0.3396.87
</details>

**Comment by mapx-** [comment]
add
`currencio.co##[href*="/clk"]`

Simple ads (blockable quickly using the element picker) have to be reported at easylist repository

**Comment by smed79** [comment]
@mapx- what does mean simple ads ? because the ads here is loaded from a [third party revolving adservers](https://forums.lanik.us/viewtopic.php?f=62&t=40036).

@KonoromiHimaries add
```
/bnr/?wkey=$script
```

**Comment by okiehsch** [comment]
It means if an issue can be fixed without using extended syntax, i.e. `script:inject`, `redirect` or [procedural cosmetic](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters) filters and the issue is not about

- anti-adblock 
- site breakage

The issue will, as a rule of thumb, not be fixed by `uAssets`, because fixing it in `EasyList` is possible and preferable.
