### ISSUE TITLE
titsbox.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2812]
URL(s) where the issue occurs

`http://titsbox.com/video/JNvoAQja/`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.12

Settings

Default

**Comment by kulfoon** [comment]
### URL(s) where the issue occurs
`https://titsbox.com/` (main page)

### Describe the issue

Broken page, videos/thumbnails not showing up, due to this rule `titsbox.com##+js(popads-dummy` from uBlock filters, disabling the rule fixes the issue.)

### Screenshoots

Before disabling the rule:
![1](https://user-images.githubusercontent.com/43844449/63330091-7da19280-c333-11e9-8ac9-cf19d543f4ac.gif)

After disabling the rule:
`https://user-images.githubusercontent.com/43844449/63330092-7da19280-c333-11e9-8b2a-56231b5a1213.gif`


### Versions

- Browser/version: Firefox 68.0.2 / Opera 62
- uBlock Origin version: 1.21.7b10

### Settings

- Default
