### ISSUE TITLE
CPU-World Anti-Adblock

### ISSUE THREAD

**Issue by TheEnhas** [uBlockOrigin/uAssets#282]
### URL(s) where the issue occurs

http://www.cpu-world.com/index.html

### Describe the issue

After loading a few pages, every page afterwards will be blocked by a message telling you to disable your ad blocker.

### Screenshot(s)

![cwab](https://cloud.githubusercontent.com/assets/25448414/22452237/8843c382-e74b-11e6-8bd6-da251ba8fd77.png)

### Versions

- Browser/version: Google Chrome 56.0.2924.76 beta (64-bit)
- uBlock Origin version: 1.10.7.102

### Settings

- I have most of the 3rd party filters enabled, but I also tested with just the default settings and the results were the same in both instances both for getting the anti-adblock popup and for blocking it.

### Notes

Fixed by adding the following:

cpu-world.com##.adsbygoogle
cpu-world.com##script:inject(setTimeout-defuser)

**Comment by uBlock-user** [comment]
Force update your filters, already patched by Easylist with `@@||cpu-world.com^$generichide`

**Comment by uBlock-user** [comment]
`cpu-world.com##script:inject(setTimeout-defuser)` works fine enough, no need for another filter.

**Comment by uBlock-user** [comment]
It's acting up again - http://www.cpu-world.com/CPUs/Bulldozer/AMD-R-Series%20RX-421BD.html

![](https://i.gyazo.com/e853bbb468c9016c4639f337b6951197.png)

Blocking statistical data with "Waiting for ads to load"

**Comment by Gho24** [comment]
The owner of this site seems to have updated his detection methods, because I have uBlock Origin fully updated (and works fine on every other website) but this now appears again:

(EDIT: as the message explains, you can navigate the site for a few hours without any ads, but eventually this will trigger)

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/25fa778b-dbac-4b8e-a557-d9f6f31a5c5b" />

**Comment by Gho24** [comment]
I tried clearing cookies, and blocking them, and now the message changed to this:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/75b11d04-d8b8-4430-ba16-ec0106742e0c" />

**Comment by gorhill** [comment]
Unable to reproduce using uBO with default settings/lists and no other extension. Provide the specific URL of the page shown in your screenshot, and troubleshooting information: Go to the webpage with the issue > Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)

**Comment by Gho24** [comment]
I also have default settings, and no other extension.

The specific URL is: https://www.cpu-world.com/sspec/

But it's irrelevant because the issue is on every single page of the site.

As I explained, it's not about how many pages you visit in succession (or how often you refresh the same page), but time limited. You have to navigate the site for an hour or two (not sure), until the site says "that's enough".

In the meanwhile, I found a temporary workaround. In Firefox, if you set cookies to "session only" (and you clear cookies from that site first), the site will think you're a new user and let you browse normally for a few more hours. You can't block cookies at all, or it will trigger the message in the second screenshot above.

The point is, the site detects UBO - that's 100% a fact.

The question becomes, can anyone do anything to bypass that detection, without having to mess around with cookie settings every few hours?

Thank you.

PS: I don't have a Reddit account, as I was banned from it a few years ago, so I can't report anything in there, nor can I make new accounts.

**Comment by gorhill** [comment]
> The specific URL is: https://www.cpu-world.com/sspec/
> 
> But it's irrelevant because the issue is on every single page of the site.

It's never irrelevant, we ask for good reasons -- **do not** argue this.  The most important goal of any reported issue is to provide all the details for us to reproduce without having to spend a single second guessing anything. If we can't immediately reproduce, we then want to eliminate all possible steps that are not **exactly** as reproduced on your side.

The bottomline is simple: we can't reproduce, nothing will happen, we won't invest our precious time on trying to reproduce endlessly. We can reproduce, then we can investigate a fix.

> and troubleshooting information:

I still can't reproduce, and you fail to provide the requested information, so the issue will not move forward.

**Comment by stephenhawk8054** [comment]
> The point is, the site detects UBO - that's 100% a fact.

The point is not about fact or not. We don't care about that.

The point is if we can't reproduce, we can't investigate anything. How can we investigate further when the site looks like this to us:

<details>

<img width="2520" height="1607" alt="Image" src="https://github.com/user-attachments/assets/1aec795e-3a1f-4324-9e23-e7203ebccc82" />

</details>
