### ISSUE TITLE
Generic filter to inject noop function by name?

### ISSUE THREAD

**Issue by kasper93** [uBlockOrigin/uAssets#300]
Hi,

Would you mind adding generic filter to resources.txt which would inject noop function? This is common usecase to replace js functions.

Syntax could be:
`example.com##script:inject(noopfn.js, gtm4wp_track_downloads)`

I need this for this site https://naekranie.pl/recenzje/arrow-sezon-5-odcinek-14-recenzja because gallery doesn't load if `gtm4wp_track_downloads` is not defined. (was blocked before by easyprivacy). Defining it to noop fixes the issue. 

If generic idea is not acceptable could you add at least defuser for `gtm4wp_track_downloads` which would define it as noopfn. 

Here is direct link to blocked resource `https://naekranie.pl/wp-content/plugins/duracelltomi-google-tag-manager/js/gtm4wp-download-tracker.js`

Thanks,
Kacper

**Comment by gorhill** [comment]
The blocked resource is 1st-party to the site. If I create an exception filter for this resource, the 3rd-party exposure does not go up (as witnessed by uBO-Scope). Hence I really do not see the need to create such a scriptlet just to avoid the loading of this (small) 1st-party script.

This is the solution as far as I am concerned, and if the exception is added to EasyPrivacy (since it's the one breaking the site with the filter `-google-tag-manager/$script`), then it would benefit all users of EasyPrivacy. This needs to be reported to EasyPrivacy maintainers (suggested solution: `@@||naekranie.pl/wp-content/plugins/duracelltomi-google-tag-manager/js/gtm4wp-download-tracker.js$script,~third-party`)

**Comment by kasper93** [comment]
Ok. It seem to be indeed dead code, because after all this site doesn't really have files to be tracked :)
