### ISSUE TITLE
shortit.pw [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3130]
URL(s) where the issue occurs

`https://shortit.pw/Yjxt8O`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 68 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by mapx-** [comment]
@okiehsch @uBlock-user  can you reproduce it ?

**Comment by uBlock-user** [comment]
> if you leave the page for a bit long time

Define long time in this context

> can you reproduce it ?

No.

**Comment by stephenhawk8054** [comment]
Oh sorry, looks like it's not stopping the countdown, but the countdown becomes very slow. So there are 2 situations I can see:

- Open new software (for example file explorer), but the tab at background is still open:
Video:
`https://streamable.com/oc2iqx`
It took about 1 minute to count down from 20s to 10s

- Open new tab, but I don't know how long it would take to reset to 00. After that, I continue solving the captcha but it doesn't accept:
Video:
`https://streamable.com/0njw7i`

I guessed it's because of this inline script:

<details><summary>Script</summary>

```js
var valid;
$(window).blur(function() {
  valid = 0;
});
$(window).focus(function() {
  valid = 1;
});
$(document).on('click', '#btn1', function() {
  $('#btn1').addClass('disabled invisible');
  $('#btn1').removeClass('pulse');
  $('#btn2').removeClass('invisible');
  $('#btn2').addClass('visible pulse');
  return false;
});
window.onload = function() {
  setTimeout(function() {
    var tst = new Date().getTime() + 20000;
    var x = setInterval(function() {
      $('#btn2').addClass('disabled');
      $("#btn2").prop('disabled', true);
      if (valid == 0) tst = tst + 100;
      var now = new Date().getTime();

      var distance = tst - now;

      var seconds = Math.floor(distance / 1000);

      document.getElementById('tleft').innerHTML = seconds.toLocaleString('en-US', {
        minimumIntegerDigits: 2,
        useGrouping: false
      });

      if (distance < 0) {
        clearInterval(x);
        document.getElementById('tleft').innerHTML = '00';
        $('#btn2').removeClass('disabled');
        $('#btn2').prop('disabled', false);
        document.cookie = "PfU6C3v=1; expires='.date('D, d m Y H:i:s',time()+120).' UTC; path=/";
      }
    }, 100);
  }, 1500);
}
``` 

</details>
