### ISSUE TITLE
uBlock not using AAK Filters

### ISSUE THREAD

**Issue by wealstarr** [uBlockOrigin/uAssets#327]
I've had AAk filters enabled in the 3rd party filters and displays "using 2104 of 2179 filters" but it never works, each and every site detects ublock and warns me, when I went to the developers site reek.github.io and tested it resolved that I'm not using AAk filters so I subscribed it from there.
Now I've one more entry of AAK filters under custom which says "using 0 of 2179 filters" it's checked and I've updated the entire thing couple of times but uBlock doesn't appear to be using any AAK filters.
How can I sort this out, any help will be greatly appreciated.

uBlock version-1.10.5.5
Browser- Opera
Settings- Default+AAK filters

**Comment by gorhill** [comment]
> each and every site detects ublock and warns me

Impossible to provide any help without specifics.

> went to the developers site reek.github.io and tested it resolved that I'm not using AAk filters so I subscribed it from there. Now I've one more entry of AAK filters under custom which says "using 0 of 2179 filters"

`reek.github.io` is 404.

**Comment by wealstarr** [comment]
Thank you for the response gorhill and I apologies for providing insufficient information, here we go again:
> This means the filters are loaded and used. This makes your issue invalid.
Okay so that means it's something else

Can you please tell me where to place the filters.txt I grabbed from the developers page if possible ? I looked into the extension's directory as well as the Browser's profile folder, couden't find where to place the filters.

**Comment by gorhill** [comment]
Here is my suggestion so that you avoid wasting your time investigating a non-existent issue: provide specifics of there you experience an issue: provide an exact web site URL where you experience the issue, and somebody will come up with a solution.

It seems you assume that if you use Reek's filters, you will always be 100% free of all those anti-blockers everywhere and at all time. This is not true. Web sites changes all the time, and Reek's was updated months ago last time, so your issue is just that new filters must be crafted to solve new filter issues. But this can be done only if you provide all the details about where is the issue, i.e. a URL and a description of what is to be solved at that specific URL.

**Comment by wealstarr** [comment]
> Web sites change all the time, and Reek's was last updated months ago, so your issue is just that new filters must be crafted to solve new filter issues.

oh! makes sense, thanks for clarifying. The list of the sites will be long, I'll see what to do with it. 
gorhill^^
