### ISSUE TITLE
girlsgogames.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3594]
URL(s) where the issue occurs

`http://www.girlsgogames.com/game/bubble-town`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.18

Settings

Default

**Comment by garry-ut99** [comment]
Breakage, games won't load, caused by "uBlock filters – Unbreak": `gamedistribution.com##+js(no-fetch-if, /^/)`, example game subpage: `https://www.girlsgogames.com/game/stickman-draw-the-bridge`
[SCREENSHOOT - broken](https://user-images.githubusercontent.com/72945564/216462671-3f7d5fa2-a264-4311-821d-a79f3e0bc0cd.png)
[SCREENSHOOT - working](https://user-images.githubusercontent.com/72945564/216462663-4c82a01e-b711-4762-b6f1-b8c39ddfbaf0.png)
