### ISSUE TITLE
veezie.st [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3607]
URL(s) where the issue occurs

`http://veezie.st/scarica/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.18

Settings

Default

**Comment by garry-ut99** [comment]
`https://veezie.st/2021/07/21/after-3-tutto-quello-che-sappiamo-finora/`
`https://veezie.st/`

Ad placeholders due to `ghide` in uBlock Filters: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219492069-310416b2-5be8-4a09-8fe7-e446f136da4a.png)
No AA for me with `ghide` off, but still AA in the source code, 
thus if not remove `ghide` then maybe example `veezie.st##.adsbygoogle`
