### ISSUE TITLE
cooking.nytimes.com

### ISSUE THREAD

**Issue by pepablock** [uBlockOrigin/uAssets#3708]
### List the website(s) you're having issues:

`https://cooking.nytimes.com/recipes/1018016-pot-roast`

### What happens?

cant print recipes (blank page) and log in button doesnt work.

### List Subscriptions you're using:

default
Adguard’s Annoyance
Fanboy’s Cookiemonster List​

### Your settings

- OS/version: **MacOS High Sierra 10.13.6**
- Browser/version: **Firefox 62.0.3 (64-bit)**
- Adblock Extension/version: **uBlock Origin 1.17.0**

**Comment by THEtomaso** [comment]
Just be careful not to block the cookie popup.
If there are any videos at those cooking pages, people might not be able to watch them, unless the cookie consent has been accepted!
Other forms of breakage might also occur.

I've reported this issue to ryanbr here:
https://github.com/ryanbr/fanboy-adblock/issues/483/
He added an exception rule for this domain a couple of days ago.
..but unfortunately, there's still one problem rule in his filters which hasn't been dealt with yet!

PS:
Like with so many other examples of these GDPR issues, this one also seems to be location dependent.

**Comment by krystian3w** [comment]
Can you find Recipe with video which does not work without logging in `cooking.nytimes.com`?

---


It's a pity, in part, that the AdGuard rule does not work the same way in uBlock Origin - you would not need any scripts (rather, analysis of what is not possible, uBlock Origin will not reveal a pop-up with changed content).

**Comment by THEtomaso** [comment]
I blocked all the modals, to get to what lies beneath..
Even when the cookie consent is blocked, I'm happy to report that all of the videos that I found seems to play just fine! :)
But of course, you can never be sure when it comes to this stuff, as there might be regional differences involved.

**Comment by pepablock** [comment]
It was working flawlessly, but for some reason the filters for this specific page/recipe aren't working.
`https://cooking.nytimes.com/recipes/1787-new-orleans-barbecue-shrimp`

**Comment by krystian3w** [comment]
In my case this it works  (on `1787-new-orleans-barbecue-shrimp`) further in AdGuard, maybe it did not "warm up" so that the filter could hide the element.

For me when switched to AdGuard, I had only unlocked scrolling and no digits blocked elements on the addon icon, and after moment / now I have the number "2 " blocked elements and the pop-up disappears and the login pop-up works/show after click in link.

uBlock Origin probably too much heavy hide the item - in comparison to AdGuard, when its uninstallation suddenly discovers ads on websites hidden by cosmetic filtering.

---

 
I'm already skipping the question that only the rule from ": if-not()" can work in uBO, without trying to use the CSS selector and JS selector ":not (:has())" (rather soon we will not see "has" from CSS4).

**Comment by krystian3w** [comment]
```css
cooking.nytimes.com##.nytc---modal-window---isShown:not(:has(.nytc---largepicturemodal---contentBody > .nytc---x---x.nytc---largepicturemodal---xBtn[role="button"]))
```

Should works on uBO `1.17.5b8` and newest.

Or the filter will wait for the popularity of release 1.17.6 and newer - optionally for your own use.


`:not(:has())` this construction should prevent cutting in older "uBO" (eg 1.17.4).

**Comment by krystian3w** [comment]
#14839

#816

#3708
