### ISSUE TITLE
videopoker.com

### ISSUE THREAD

**Issue by MarkofT** [uBlockOrigin/uAssets#3987]
### URL(s) where the issue occurs

`https://www.videopoker.com/play/?game=120&title=Super%20Draw%206%20Card%20Poker`

### Describe the issue

Running Nano Adblocker and Nano Defender on Chrome for PC. The site loads it's own quick ad video but then seems to figure out that the banner ads didn't load and presents a hard block asking you to enable ads or subscribe.

### Screenshot(s)

I can get you one if you want, but it's pretty self explanatory. You will need a free account on the site.

### Versions

- Browser/version: Version 70.0.3538.77 (Official Build) (64-bit)
- Nano Adblocker version: 1.0.0.74

### Settings

- None

### Notes

Thanks for the help!

**Comment by okiehsch** [comment]
I can't reproduce.
@ZaphodBeebblebrox use the basic option, no credit card needed.
![image](https://user-images.githubusercontent.com/16838044/47756894-2519df80-dca4-11e8-8ec5-011512cb736e.png)

**Comment by ZaphodBeebblebrox** [comment]
I use it, but it then brings me to the screen below, where both options require a credit card.
![image](https://user-images.githubusercontent.com/22801430/47756937-6bf2df80-dc7a-11e8-815d-3fa4df9f79af.png)

**Comment by ZaphodBeebblebrox** [comment]
Yep, I get nothing as well. I see js that looks like it detects adblock, but get nothing.

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/34

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/47757254-16fb9d00-dc6b-11e8-8ee9-3532a31802b9.png)

**Comment by kulfoon** [comment]
I also can't reproduce.

**Comment by MarkofT** [comment]
> It won't let me make an account without giving it a credit card. Can you test if the filter `videopoker.com##+js(abort-on-property-write.js, checkAds)` works?

Not sure why you were having trouble making a free account, nor why no one else could duplicate the issue, but the filter worked perfectly. Thank you very much.

**Comment by kulfoon** [comment]
Maybe because everybody who couldn't reproduce (including me) were using:

[TRY IT NOW/ PLAY FOR FREE](https://www.videopoker.com/play/?game=4&title=Super%20Times%20Pay%20Poker&mobtry=1&tryit=1&trysrc=foottab) button:

<details>
  <summary>Screenshoot</summary>

![ss1](https://user-images.githubusercontent.com/43844449/47789788-d6a52900-dd15-11e8-9e44-9444afeeaf2f.png)

</details>
.

Instead of:

 [JOIN](https://www.videopoker.com/join/benefits/) button:

<details>
  <summary>Screenshoot</summary>

![ss1](https://user-images.githubusercontent.com/43844449/47790175-c9d50500-dd16-11e8-847b-5a517624ced3.png)

</details>
.

and then [TRY IT FOR FREE](https://www.videopoker.com/join/?membership=gold) free account button:

<details>
  <summary>Screenshoot</summary>

![ss2](https://user-images.githubusercontent.com/43844449/47790144-b5910800-dd16-11e8-866c-eb8fdefe2a28.png)

![ss3](https://user-images.githubusercontent.com/43844449/47790147-b75acb80-dd16-11e8-8ca7-f1ad930f7359.png)

</details>
.

Does this makes any difference? As on the last screenshoot they say:

> Thanks for Joining!
> 
> As a GOLD Member you:
>  - Won't see ads
> ...
>
