### ISSUE TITLE
Ads on TrueTrophies.com

### ISSUE THREAD

**Issue by LegendaryOverlord** [uBlockOrigin/uAssets#4070]
### URL(s) where the issue occurs: 

`https://www.truetrophies.com/`

### Describe the issue:

I'm seeing ads along the top and on the right.

### Screenshot(s):

https://imgur.com/daI3IuS

### Versions

- Browser/version: Chromium 70.0.3538.77
- uBlock Origin version: 1.17.0

### Settings:

I've only enabled a few of the lists that were disabled by default.

**Comment by ZaphodBeebblebrox** [comment]
Appears to be a race condition, can reproduce inconstantly on chrome.

**Comment by okiehsch** [comment]
There is no way to disable the offending part of the inline-script in Chrome because of the race condition, so we need two fixes for Chrome and Firefox.
With Firefox the fix is simple
`example.com##^script:has-text(axtd)`
can replace the existiong filter for all domains, with Chrome we will have to disrupt the chan of requests that causes the ad-reinsertion.
