### ISSUE TITLE
valueresearchonline.com | Annoyances | Splash screen page and sticky footer

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4143]
### URL(s) where the issue occurs

`https://www.valueresearchonline.com`

### Describe the issue

1. A splash screen `https://www.valueresearchonline.com/ads/splash.asp` stays for a few seconds before redirecting to the actual homepage. This doesn't happen every time. I think it checks for a cookie before triggering this splash screen. An easier way to reproduce the issue is to open the site in private browsing mode.

2. There's a sticky `valueresearchonline.com###fixed_footer` footer at the bottom of every page.

### Versions

- Browser/version: Firefox 63.0.3
- uBlock Origin version: 1.17.2

### Settings

Annoyances filter

**Comment by okiehsch** [comment]
You would have to set the 
![image](https://user-images.githubusercontent.com/16838044/48664582-118eb700-eaa1-11e8-90b6-a480453c4228.png)

We can't set cookies, so I don't see a way to avoid this annoyance.

**Comment by okiehsch** [comment]
For `valueresearchonline.com###fixed_footer` report to `EasyLIst/Annoyance List`

https://github.com/uBlockOrigin/uAssets/blob/master/README.md
If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

- anti-adblock
- ad-reinsertion
- popups/popunders
- site breakage
will always be fixed in uAssets even if they don't require extended syntax.

**Comment by in4u** [comment]
>We can't set cookies, so I don't see a way to avoid this annoyance.

Well, that's a bummer.

>report to EasyLIst/Annoyance List ... because fixing it in EasyList if possible is preferable.

Can you please point me towards Easylist/Annoyance list? Is it the same as Fanboy's Annoyance list? I have tried using the latter in past but it has far too many generic rules which would require me to go about whitelisting at least a few dozen rules just for getting one thing blocked! If that is indeed the suggested list, I'd rather move this issue to Adguard's Annoyance list.

**Comment by okiehsch** [comment]
Sorry, I meant Fanboy‘s Annoyance list.
You can of course report to AdGuard, it was just a suggestion ;)

**Comment by smed79** [comment]
@ryanbr fyi
