### ISSUE TITLE
crackle.com

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#419]
When you go to crackle.com with uBlock Origin enabled, the website displays a page that says "Initialization Failure Retry" and doesn't display the normal website, but if you disable uBlock Origin then the website works normally.

**Comment by okiehsch** [comment]
update your `uBlock filters – Unbreak` list.

**Comment by js017** [comment]
I already updated all the filters including "uBlock filters - Unbreak" but crackle.com still doesn't work. Also, do you know why "Adblock Protector List" says "A network error prevented the resource from being updated." when trying to update it?

**Comment by js017** [comment]
Why did you close this issue? How can I contact you?

**Comment by okiehsch** [comment]
I meant you should update `uBlock filters – Unbreak` now , because I just added a fix, it works on my end with Chrome and Firefox.

**Comment by gorhill** [comment]
> do you know why "Adblock Protector List" says "A network error prevented the resource from being updated." when trying to update it?

Because the project changed name/location. I fixed to the new name/location: <https://github.com/gorhill/uBlock/commit/0ae695f8b1ac595e536a9a69dda86240e21d37dc>.

However that one file is not updated often, this will take a while before everybody has the fix. Workaround: import `https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtectorList.txt` as a custom filter list until the stock one works fine.
