### ISSUE TITLE
thepiratebay.rocks

### ISSUE THREAD

**Issue by salam2009** [uBlockOrigin/uAssets#4333]
### URL(s) where the issue occurs

`thepiratebay.rocks`

### Describe the issue

Unblocked ad(s).

### Screenshot(s)

No need.

### Versions

- Browser/version: FF 64
- uBlock Origin version: 1.17.4

### Settings

Default.

### Notes

This is one of the best TPB proxies I've used for a while, but it pops up annoying ads whenever the user clicks anywhere on the page. They might change their TLD in the future for security reasons. Thanks so much for your help!

**Comment by salam2009** [comment]
@mapx- 
`thepiratebay.rocks` is now `thepiratebay.zone`, and it started to open a blank page whenever the user clicks on the page.

**Comment by salam2009** [comment]
@mapx-
`thepiratebay.zone` has started to show popads. Thanks for the filter in advance!

**Comment by bogachenko** [comment]
_Too lazy to create my issue, I am writing here._
The captcha for `thepiratebay.org` is broken, due to the "help" of several third-party authors, @Yuki2718 can you create a rule for the `uBlock filters – Unbreak`

The script `https://thepiratebay.org/cdn-cgi/challenge-platform/h/b/orchestrate/captcha/v1?ray=643ce2c23f9c4174` that is needed to display `hcaptcha.com` is blocked.

The culprits:
1. Fanboy's Enhanced Tracking List - `||thepiratebay.org^$script`
2. EasyList  - `||thepiratebay.$script,domain=pirateproxy.live|thehiddenbay.com|thepiratebay.org`
3. NoCoin Filter List - `*$script,domain=thepiratebay.org`


**In order to trigger the captcha check, use a public proxy, I used the TOR.**

**Comment by bogachenko** [comment]
@mapx- and what is it you added? The rest of the filters will be triggered in the same way. How about something like 
`@@||thepiratebay.org/*/captcha/$script`

**Comment by mapx-** [comment]
usually we counter only the official lists issues

**Comment by mapx-** [comment]
however @ryanbr  for `Fanboy's Enhanced Tracking List`

**Comment by uBlock-user** [comment]
@bogachenko only breakage caused by default lists will be addressed here.

**Comment by bogachenko** [comment]
Yes yes yes I can read the filter description. IDK that Fanboy's Enhanced Tracking List was deleted, the `assets/assets.json` file changes faster than the hair color of an eighth-grader girl.

**Comment by uBlock-user** [comment]
> IDK that Fanboy's Enhanced Tracking List

Deleted or not, it was never enabled by default that take precendence over presense.

**Comment by uBlock-user** [comment]
> IDK that Fanboy's Enhanced Tracking List

Deleted or not, it was never enabled by default that take precedence over presence.
