### ISSUE TITLE
vorname.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4347]
URL(s) where the issue occurs

`https://www.vorname.com/name,Aurica.html`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 70 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.17.4

Settings

Default

**Comment by garry-ut99** [comment]
`https://www.vorname.com/`
`https://www.vorname.com/das-ist-der-nachwuchs-der-stars.html`

Ad placeholders due to `ghide` in uBlock Filters: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219496701-959362f9-69a8-4b5f-b18d-6321f5e85f99.png)
No AA for me with `ghide` off, but still AA in the source code,
thus if not removing `ghide` then maybe example: 
`vorname.com##.page__top-ad-wrapper, [class*="superbanner_"]`
