### ISSUE TITLE
buyitonline.store (clicksfly.com) countdown timer

### ISSUE THREAD

**Issue by diab0lik** [uBlockOrigin/uAssets#4495]
### URL(s) where the issue occurs

`[https://buyitonline.store/WFvEl9]`

### Describe the issue

[After captcha there is a timer can it be made to count down faster?.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [Chrome  71.0.3578.98]
- uBlock Origin version: [uBlock Origin v1.17.4]

### Settings

- [default]

### Notes

[tried to add these to custom filter but didnt work buyitonline.store##+js(nano-setInterval-booster.js, , 100)
buyitonline.store##+js(nano-setTimeout-booster.js)]

**Comment by okiehsch** [comment]
No, the site validates the timer on the server side and if that is the case nothing can be done.

**Comment by okiehsch** [comment]
You can see for yourself, you can boost the timer on your side by adding 
`buyitonline.store##+js(nano-setInterval-booster.js)`
that will make the timer "count down faster" but will result in a bad request because of the server side implementation.
![image](https://user-images.githubusercontent.com/16838044/50576283-0dc7b180-0e0f-11e9-90c1-380a925220d1.png)

**Comment by diab0lik** [comment]
ok thanks is there a way to make the page stay in focus so the timer keeps counting down?

**Comment by okiehsch** [comment]
I don't think there is a way the onfocus/onblur event is tied in with the timer, so aboritng it will break the functionality altogether.
