### ISSUE TITLE
Filter sites can be upgraded

### ISSUE THREAD

**Issue by grenzor** [uBlockOrigin/uAssets#45]
Domains winhelp2002.mvps.org and malwaredomainlist.com have HTTPs available to be used now (however for mvps looks like the filter list only works in http?).

**Comment by lewisje** [comment]
Also, Peter Lowe's list is now available over HTTPS.

**Comment by IDKwhattoputhere** [comment]
Empty filter caches, update them and look into the background requests in the logger while doing so. You'll see that some lists (e.g. Peter Lowe's) are already being downloaded over HTTPS.

**Comment by lewisje** [comment]
I wasn't sure how to check that, because when I mouse-over the link, I just get a link to the built-in version of the list, rather than the specific URL used to refresh the list; then again, I might just see that because I've unchecked the built-in list and instead use a custom version that is

- actually in ABP format rather than a HOSTS file
- excluding particular domains from being blocked that I regard to be false positives (currently `adf.ly` and `boldchat.com`)

Normally I'd just use whitelist directives, but because I *can* exclude particular domains via URL parameters, I *will*.

**Comment by gorhill** [comment]
List from `malwaredomainlist.com` is already downloaded through `https`.

List from MVPS can't be downloaded from `https`.
