### ISSUE TITLE
torrentsearchweb.ws

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#4539]
### URL(s) where the issue occurs

`[https://torrentsearchweb.ws]`

### Describe the issue

[ads]

### Versions

- Browser/version: [firefox v63]
- uBlock Origin version: [1.17.4]

### Settings

- [default]

**Comment by okiehsch** [comment]
Looks like this is fixed in the regional list `EasyList China`.
![image](https://user-images.githubusercontent.com/16838044/50675164-8f286b00-0fec-11e9-9f2c-d441fb5696d3.png)

**Comment by dumbusernameidk** [comment]
Hm I suppose I should drag that filter to mine then? I'm not chinese so I wouldn't need that filter list.

**Comment by okiehsch** [comment]
All ads on my end are chinese, that's why I suspected that the website was mainly used by chinese speakers.

Seeing as the site is actually in english if I search for something I will add a fix.
Does 
`torrentsearchweb.ws##+js(abort-on-property-read.js, __js_key)`
work for you without breaking anything?

**Comment by dumbusernameidk** [comment]
for some reason I can't even access the site anymore I get an internal server error page. so I can't even test it right now haha.
