### ISSUE TITLE
Delisted domain from malwaredomains.com

### ISSUE THREAD

**Issue by Devact** [uBlockOrigin/uAssets#459]
Hello,

This domain:
forms.zohopublic.com

is included in:
uAssets/thirdparties/mirror1.malwaredomains.com/files/justdomains
https://github.com/uBlockOrigin/uAssets/blob/master/thirdparties/mirror1.malwaredomains.com/files/justdomains

If you check the domain is delisted on malwaredomains.com:
http://mirror1.malwaredomains.com/files/domains.txt

I don't know if here is the right place to do a request to delist it...

Thank you!

**Comment by SMed79** [comment]
Hi, 
> I don't know if here is the right place to do a request to delist it...

Should be reported via email to 
http://scr.im/malwaredomai
http://www.malwaredomains.com/?page_id=13

**Comment by gorhill** [comment]
That filter list like all others is updated regularly by uBO so that users do end up with the updated version.

**Comment by okiehsch** [comment]
I think the issue is that `forms.zohopublic.com` seems to be commented out in the updadet version

![mal](https://user-images.githubusercontent.com/16838044/27254368-3623124e-5387-11e7-82d4-5c3e1038ce07.PNG)

but uBO still blocks it.
![image](https://user-images.githubusercontent.com/16838044/27254391-762c137c-5387-11e7-9e77-0effa2e690a2.png)

**Comment by gorhill** [comment]
I just forced an update and it's not blocked anymore.
