### ISSUE TITLE
investopedia.com - Content Breakage

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#484]
The videos do not load on http://www.investopedia.com when uBO is turned on they load fine if its turned off.

**SS:**
https://i.imgur.com/ZhJE0be.png (with uBO turned on)
https://i.imgur.com/0Gf5CzE.png (with uBO turned off)

**Error URL:**
http://www.investopedia.com/video/play/capitalism/

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by mapx-** [comment]
test
`@@||investopedia.com/video/play/$csp,domain=investopedia.com`

**Comment by okiehsch** [comment]
`@@*$csp,domain=investopedia.com`
Why not disable the csp for the whole site,is it really needed?

**Comment by mapx-** [comment]
the easylist original filter (blob / websocket) 
`|blob:$domain=investopedia.com`

probably was fighting some injected ads via websockets

**Comment by gorhill** [comment]
The breakage is not specific to uBO, the player is also broken for FF/ABP, so that `|blob:` filter should be removed from EasyList.

What is specific to uBO is that it can enforce `|blob:`-like filters on Chromium-based browsers and as a consequence the player also breaks on Chromium-based browsers with uBO.

Same issue was encountered on twitch.tv -- forbidding `blob:`-based URLs was breaking the player.

[I have inquired](https://forums.lanik.us/viewtopic.php?p=119446#p119446) to understand the purpose of the `|blob:` filter. To me it feels like the blocking should be done upstream, i.e. to block whatever network requests are used to obtain the data needed to create the `blob:` URLs.
