### ISSUE TITLE
frag-mutti.de [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5052]
URL(s) where the issue occurs

`https://www.frag-mutti.de/schlagsahnebecher-restlos-entleeren-a54498/`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 72 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.18.4

Settings

Default

**Comment by garry-ut99** [comment]
Big ad placeholders all over the site caused by `ghide` from "uBlock filters"
Example article subpage: `https://www.frag-mutti.de/fruechtemuesli-im-apfel-a61285/`

<details>
<summary>SCREENSHOOTS</summary>


![a (3)](https://user-images.githubusercontent.com/72945564/215355882-fd4bd1ed-d353-43e9-b2f5-4c2ee62fb97b.png)
![a (4)](https://user-images.githubusercontent.com/72945564/215355884-45d644c3-fe61-4b9f-9681-49172a4f8337.png)
![a (1)](https://user-images.githubusercontent.com/72945564/215355880-a286f188-3810-4107-b5bc-dfbb6434504a.png)
![a (2)](https://user-images.githubusercontent.com/72945564/215355881-c1f993bd-0168-40f8-9310-e4daedde3409.png)

</details>
