### ISSUE TITLE
apkonline.net{Antiadblock}

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5090]
### URL(s) where the issue occurs

`https://www.apkonline.net/runapk/create-androidapk.html?app=android_6.0_blank`

### Describe the issue

antiadblock
### Versions

- Browser/version: firefox desktop 65 stable
- uBlock Origin version: 1.18.4

### Settings

uBO's default settings+nano defender by LiCybora +decentraleyes

**Comment by drogga** [comment]
_Guys, sorry to bother, but since I found this old (Closed) issue ticket, which is very much related, I've decided to comment here, instead of creating a new one [I will delete it if it's problematic !, just say so]_

The Emulator page is now hosted on another site by OnWorks, which gets stuck on "Loading..." with uBlock Origin and ost of the filters, except the language/country based ones, only 3 of them I've enabled, it works by turning it off, but there are annoyances, so I will appreciate if you can do something to address it in the filters.
You can try: https://www.uptoplay.net/com.aefyr.sai

_More text here: https://github.com/drogga/TextWarrior/issues/23_

Thank in advance.

**Comment by stephenhawk8054** [comment]
About the site `https://www.uptoplay.net/com.aefyr.sai`, I can't use `replace` with this. Can anyone use it?

```adb
||uptoplay.net/playonline/popup2b.js$replace=/event\.isEmpty/false/gms
```

**Comment by Daxy7** [comment]
UBo developer build or AdGuard?

**Comment by stephenhawk8054** [comment]
uBO dev build

**Comment by gorhill** [comment]
> `||uptoplay.net/playonline/popup2b.js$replace=/event\.isEmpty/false/gms`

I don't see any instance of `uptoplay.net/playonline/popup2b.js` in browser's network tab.

**Comment by gorhill** [comment]
The mime of `https://www.uptoplay.net/playonline/popup2b.js` is `application/x-javascript`, which is not supported mime. I added it as a supported mime type, this will be in next dev build.

**Comment by BlazeFTL** [comment]
Off-Topic..But I Am Trying Replace On `https://5pdrzj2rqvg.tinys.click/vmqnkdF0MBnhM39DTjM`
Js = `https://5pdrzj2rqvg.tinys.click/js/app.js?ver=6.4.0`
On Second Page With 25 Sec Timer Theres A Popup 
I Have Tried Other Variations Too With Full Url
```
||tinys.click^$script,1p,replace=/window\.open/none/gms

**Comment by drogga** [comment]
Given that there's a huge banner on the top, which is black (partially blocked I guess, except its frame), invisible overlay on which I have to click the (`x`) button to close it, else I can't interact, and a consent, which uBlock cookies and other filters should usually take care of like on other pages, but they don't on this one and if I use one of the `I don't care about cookies` / `I still don't care about cookies` extensions it bypasses the consent, then the emulator doesn't load, so should I consider this set and done and try to address those on my end in `My filters`/`My rules` (I don't have much knowledge with the matter, if any), or...?

**Comment by mapx-** [comment]
I'd say it's enough - not a big deal to click "x", otherwise we get again the "loading..." stuff

**Comment by drogga** [comment]
I get it more than once, but ok.
