### ISSUE TITLE
@@ -> @@||

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#5162]
`@@safelinkunited.blogspot.com^$generichide`

**Comment by garry-ut99** [comment]
Big ad placeholders due to `ghide` from "uBlock filters": [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218320970-e3205cf5-b05e-4c35-985a-d00adffec44f.png)
No AA for me with `ghide` off, but still AA in the source code, 
thus if decide to not remove `ghide`, then optionally  `safelinkunited.blogspot.com##.adsbygoogle`
