### ISSUE TITLE
psprices.com

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5189]
`https://psprices.com/region-ru/game/301117/playstationrplus-podpiska-na-12-mesiatsev`

(On the right panel) antiadb @mapx- @okiehsch 

default sett.

**Comment by mapx-** [comment]
Can you use the site even getting that message ? (is it only an annoyance ?)

**Comment by bogachenko** [comment]
Seems to be yes. It looks like it's just a DOM.

**Comment by mapx-** [comment]
fixed as annoyance

**Comment by theinstantmatrix** [comment]
Anti-Adblock Script - BlockAdBlock

`https://psprices.com/region-us/game/2777916/the-messenger`

From AdguardTeam/AdguardFilters#51193

**Comment by uBlock-user** [comment]
@theinstantmatrix Already fixed in uBlock Annoyances. Did you activate that list ?

**Comment by theinstantmatrix** [comment]
@uBlock-user - Yes, I did activate that list, however, the website is updated to use BlockAdBlock, which was now already fixed in the main list. Apparently, it wasn't there before when the issue first opened. And they seem to also remove the anti-adblock message in place of that script, so this filter from uBO-annoyances

`psprices.com##+js(abort-current-inline-script.js, document.getElementById, block)`

can now be removed - I have already deactivated it using `#@#` on my list.

**Comment by theinstantmatrix** [comment]
Well, it seems like they removed BAB and put back in the annoyance.
I have already saved a copy of the page with BAB here for proof:

`https://web.archive.org/web/20200309180933/https://psprices.com/region-us/game/2777916/the-messenger`

@mapx- feel free to revert dd954d5 - though I would keep the ghide filter just in case they changed their website again.

**Comment by mapx-** [comment]
it's no harm if we still keeping the `ghide` filter too
