### ISSUE TITLE
americanexpress.com

### ISSUE THREAD

**Issue by ndaesik** [uBlockOrigin/uAssets#5367]
I'm newb on here, Thank you so much for contribute to block most of ads from most of sites, however, I selfishly don't want to spend much time on writing issues for every time I found some unbanned ads.
Is this gonna be okay to write down just the single line as like the below without any notes?

americanexpress.com###btiInlineBanner

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/README.md

"If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable."

You can open an issue at the `EasyList" repo. https://github.com/easylist/easylist/issues

**Comment by ndaesik** [comment]
Okay thanks! hope you have a great day :)
