### ISSUE TITLE
enrt.eu [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5389]
URL(s) where the issue occurs

`https://enrt.eu/hztYWVd`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 73 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.16

Settings

Default

**Comment by IThinkIAmCool** [comment]
`seulink.online##+js(aopr, app_vars.force_disable_adblock)
seulink.online##+js(set, blurred, false)
seulink.online##.banner-inner
seulink.online##^meta[http-equiv="refresh"]
##[href*="https://catastropheillusive.com/"]
##[href*="https://ads.enrt.eu/"]`

![image](https://user-images.githubusercontent.com/84580704/120066717-66ebac00-c080-11eb-8ca4-a237ae9f1a39.png)
from a soilink.online link

**Comment by mapx-** [comment]
> ^ don't fix the refresh issue.

it's firefox specific (html filtering)

**Comment by D4niloMR** [comment]
Update:
```adb
cl1ca.com,4br.me,fir3.net,seulink.*,encurtalink.*##+js(aopr, mm)
```
maybe this too, but this is already on adguard annoyances:
```adb
cl1ca.com,4br.me,fir3.net,seulink.*,encurtalink.*##+js(set, blurred, false)
```

Those filters are now obsolete/fixed by regional list
`https://github.com/uBlockOrigin/uAssets/issues/6725`
`fir3.net##+js(aopr, app_vars.force_disable_adblock)`
`fir3.net##.banner`
`fir3.net###link-view > [href][target="_blank"]`
`fir3.net##[href^="https://e9c1khhwn4uf.com/"]`
`fir3.net##^meta[content*="ads.enrt.eu"]`
`@@||fir3.net^$ghide`
`*$script,3p,denyallow=google.com|gstatic.com|recaptcha.net,domain=fir3.net`

`https://github.com/uBlockOrigin/uAssets/issues/6967`
`encurta.eu##+js(aopr, app_vars.force_disable_adblock)`
`encurta.eu##.banner-inner`
`encurta.eu##+js(nowoif)`

`https://github.com/uBlockOrigin/uAssets/issues/5389`
`enrt.eu,seulink.*##^meta[http-equiv="refresh"]`
`enrt.eu,seulink.online##+js(refresh-defuser)`
`enrt.eu,seulink.*##+js(aopr, app_vars.force_disable_adblock)`
`enrt.eu,seulink.*##.banner-inner`
`enrt.eu##[href*="builderall.net/"]`
`*$frame,script,3p,denyallow=google.com|gstatic.com|recaptcha.net,domain=enrt.eu|seulink.*`

I should make a PR?

**Comment by mapx-** [comment]
yes, do a PR , thanks.
Add `##+js(set, blurred, false)` too
