### ISSUE TITLE
thegatewaypundit.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#541]
`http://www.thegatewaypundit.com/`

Credit card debt ad on right.
`||www.thegatewaypundit.com/wp-content/uploads/cgl.jpg`

**Comment by gorhill** [comment]
Should be added to EasyList:

    thegatewaypundit.com##.thega-widget

**Comment by gorhill** [comment]
@fyi @ryanbr

**Comment by terrorist96** [comment]
@gorhill please leave it open. EasyList maintainers are unlikely to add it anytime soon. See: https://github.com/easylist/easylist/issues/415 Open since May 26.

**Comment by gorhill** [comment]
Maybe coming up with the actual solution is more motivating to deal with an issue rather than having to allocate time to investigate the issue. Every single bit of time spend on any one single issue is done at the expense of all other issues. Really the best is when people come up with well researched solutions to well defined issues.

**Comment by terrorist96** [comment]
Well on that particular issue someone even created a PR that's been sitting around for almost two months as well. So not sure what more could have been done.

**Comment by gorhill** [comment]
Because the solution does not look good, he created a filter with what appears to be a random looking string as part of it. The filter wouldn't work anymore, and might have been broken shortly thereafter. That is better:

    thegatewaypundit.com##a[href*="//midamericadebtrelief.com/"]

Because it's not based on a random class/id, it targets specifically the ad through its link.
