### ISSUE TITLE
ommantrameditation.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5440]
URL(s) where the issue occurs

`https://ommantrameditation.com/xbG9n`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 73 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.16

Settings

Default

**Comment by dumbusernameidk** [comment]
fake push notification

`ommantrameditation.com##+js(setTimeout-defuser.js, '0x)` works.

**Comment by okiehsch** [comment]
Thanks for investigating.
`ommantrameditation.com##+js(setTimeout-defuser.js, '0x)`
is necesarry if we can't disable the offending inline-script because of a race condition.
In this case 
`ommantrameditation.com##+js(abort-current-inline-script.js, Math, zfgloaded)`
works on my case and it is the preferable solution.

**Comment by dumbusernameidk** [comment]
yep that one works.

**Comment by dumbusernameidk** [comment]
site name changed to `techsyou.com`
