### ISSUE TITLE
quora.com: answer being blocked

### ISSUE THREAD

**Issue by spittingmadtruth** [uBlockOrigin/uAssets#5609]
### URL(s) where the issue occurs

`https://www.quora.com/How-does-Quora-use-machine-learning-in-2017`

### Describe the issue

Some answers are being hidden by uBlock.

#### Without uBlock
![image](https://user-images.githubusercontent.com/40901446/57883716-e5e45380-77db-11e9-9a7f-071d91ca360a.png)

#### With uBlock
![image](https://user-images.githubusercontent.com/40901446/57883733-f399d900-77db-11e9-8ff4-a177990f5c4a.png)

### Versions

- Browser/version: Version 73.0.3683.103 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.19.2

### Settings

Default

### Notes

The issue seems to be caused by this filter: `quora.com##.UnifiedAnswerPagedList > .paged_list_wrapper > div[id]:has(a[href][target="_blank"][rel="noopener nofollow"]:not(.external_link))`

**Comment by terrorist96** [comment]
Same issue.
`https://www.quora.com/Which-on-demand-gas-delivery-startup-e-g-Purple-Filld-Yoshi-will-take-the-market-What-are-the-relevant-factors`
Answer by `Shruti Singh` being blocked (when you hover your mouse over it or click) due to `quora.com##.pagedlist_item:has([href*="utm_campaign"])` rule.

**Comment by ghajini** [comment]
Since it is most new filed issue of `quora` among issue tracker,. I will post issue here....

@mapx-, @okiehsch
Click 2-3 stories to trigger signup annoyance
Signup annoyance filter needs update....
`https://prnt.sc/ogq8l3`

**Comment by yourduskquibbles** [comment]
@ghajini Does adding `quora.com##div[id$="_signup_wall_wrapper"]` to My Filters work for you?

**Comment by jeroonk** [comment]
Answer by *Alon Amit* also gets hidden on https://www.quora.com/How-do-you-find-the-positive-integer-solutions-to-frac-x-y+z-+-frac-y-z+x-+-frac-z-x+y-4 due to the rule (eec3e9d):

`quora.com##:xpath(//*[(text()='d')]/../../../../..)`

erroneously matching various MathJax equations containing the letter "d" and thereby blocking the whole answer itself, specifically on this line in the answer:
> [...] a d-dimensional manifold, with d = n - k

MathJax renders these with `<span class="mi">d</span>` and `<mi>d</mi>` elements.

As far as I can tell, the ads this filter targets are only matched on a `<p>` containing the text "a**d** by" or "promote**d** by" (with random hidden junk between each letter). A possible fix might be:

`quora.com##:xpath(//p[(text()='d')]/../../../../..)`

**Comment by mapx-** [comment]
thx

**Comment by ghajini** [comment]
@yourduskquibbles,
Soory for late responding iam not getting notifications about posts. ...'
Said filter works👍

**Comment by mapx-** [comment]
removed because breaking normal `sign in`

**Comment by 0x6900** [comment]
![image](https://user-images.githubusercontent.com/14212781/182852034-227f2433-4320-4204-b519-518bc99e090c.png)

A similar issues, that collapse all answers on the wabpage
