### ISSUE TITLE
viafree.dk anti-adblock 

### ISSUE THREAD

**Issue by trine5362** [uBlockOrigin/uAssets#5641]
### URL(s) where the issue occurs

`https://www.viafree.dk/programmer/reality/paradise-hotel/saeson-15/episode-21`

### Describe the issue

If you skip to after 12 min. into the video then ublockOrigin ad blocker is being detected. 

### Versions

- Browser/version: Chrome Version 74.0.3729.157
- uBlock Origin version: 1.19.2

### Settings

No changes

**Comment by mapx-** [comment]
@DandelionSprout

**Comment by mapx-** [comment]
test these filters
```
||freewheel-mtgx-tv.akamaized.net/$media,domain=viafree.dk|viafree.no|viafree.se,badfilter
||freewheel-mtgx-tv.akamaized.net/*.mp4$media,redirect=noopmp3-0.1s,domain=viafree.dk,badfilter
```

**Comment by trine5362** [comment]
If I add the two filters then ublockOrigin is no longer been detected but it takes 47 seconds before the video continues. Is it possible to reduce the waiting time?

**Comment by DandelionSprout** [comment]
I can confirm trine5362's qualms about the long loading times with those entries, as `Viafree` tries to load what seems to be 20-40 different ads before resuming with the program.

Since the four Nordic `Viafree` sites use pretty much the same underlying engine, since they're known to be **VERY** aggressive in their anti-adblocking efforts, and since the national versions of `Paradise Hotel` doesn't seem to be region-locked that I'm aware of, I'd have asked Frellwit for assistance about it [instead / as well] for that site.

**Comment by lassekongo83** [comment]
I can only manage to get rid of the preroll ads. What about letting the midroll ads play, but blur/darken them instead with CSS? (Ad sabotage, because the ads are not interesting at all.) I can also add a small message with `content:` explaining why the ad is blurred. Then add an eventlistener-defuser so the user can go and do something else in another tab while the counter counts down.

Or is that a bit farfetched?

**Comment by okiehsch** [comment]
It is your list and your call, I would probably only make sure that the user can go and do something else in another tab while the counter counts down.
Whatever you think is best.

**Comment by mapx-** [comment]
see this thread:
https://github.com/NanoAdblocker/NanoFilters/issues/337#issuecomment-495454157

**Comment by KiLL4FuNK** [comment]
anti-adblock

`https://www.viafree.dk/programmer/livsstil/boligkob-i-blinde-1/saeson-3/episode-5`

**Comment by okiehsch** [comment]
Fixed in the regional list.
