### ISSUE TITLE
tvad.me

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#577]
tvad.me

When you go to tvad.me it says, "Adblock will interfere with your experience. Kindly consider disabling your adblock on our domain.", "Show me how", and "Remind me later". Is there a way to fix that? Thanks.

![thevideo me](https://user-images.githubusercontent.com/26278182/28540780-89f39564-7084-11e7-861b-91452fc88ccc.jpg)

Firefox Developer Edition 55.0b11 (32-bit)
uBlock Origin 1.13.8

**Comment by js017** [comment]
Why did you close this post? Thanks.

**Comment by okiehsch** [comment]
I added a fix, it says **"closed this in 4d92503",** if you click on 4d92503 you will see that I added the
filter `@@||thevideo.me/js/jspc.js$script,first-party`, which fixes your issue on my end.

**Comment by js017** [comment]
Ok. I didn't know that's what "closed this in 4d92503" means, so that's helpful to know. There's been a few different websites that people on the forums have been able to help me find working filters for, and I was wondering how do you find a filter that will work for a certain websites? If I knew how to create my own custom filters for certain websites then I wouldn't need to ask people in the forums. Is there a tutorial or something available for that? Thanks.

**Comment by okiehsch** [comment]
I do not think that there is a tutorial and there are many different issues, from simply blocking a banner-ad to disabling an anti-adblock message and each issue can have different solutions, from simply
allowing a certain script, like in your issue here, to disabling some part of a sites inline-script, or manipulating 
a sites Document Object Model.
I am sorry but I can't five you a tutorial: How to create custom filters for certain websites.

**Comment by okiehsch** [comment]
If you only want to know how the filter-syntax works `https://adblockplus.org/en/filter-cheatsheet`
would be a .good place to start.

**Comment by SMed79** [comment]
@js017 read his thread https://adblockplus.org/forum/viewtopic.php?f=1&t=42628

**Comment by js017** [comment]
Ok. Thanks.
