### ISSUE TITLE
fapxl.com (NSFW)

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5795]
### Describe the issue

[Site has breakage + malware third party script running.]

### Versions

- Browser/version: [chrome v74]
- uBlock Origin version: [1.19.6]

### Settings

- [default]

### Notes

[The `/blockadblock.js` filter breaks the video player and the site runs a script from `browser-update.org`. I've made some filters that fix the two issues `@@||fapxl.com/skins/blank/js/blockadblock.js$script`
`fapxl.com##+js(addEventListener-defuser.js, DOMContentLoaded, $buo_f)`. For the bab it's an oddity but I don't see any actual anti-adblock on the site so maybe it's a bait script?]

**Comment by okiehsch** [comment]
Why do you think the `browser-update.org` request is malicious?

**Comment by dumbusernameidk** [comment]
Hm well i'm uncertain but it is actually blocked in adguard tracking protection filter list. Looking at it on google search maybe malicious was the wrong word. But I don't think it's necessary for it to run the script notifies you to update your browser.

**Comment by okiehsch** [comment]
It's in `Fanboys Annoyance's List` so it will probably not be added to `EasyPrivacy`.
I agree that it does some tracking, so I will add `||browser-update.org^$3p` to `uBO-privacy`.

**Comment by dumbusernameidk** [comment]
That'll work.

**Comment by josselex** [comment]
@okiehsch 

Hi, I'm operating browser-update.org
We are not tracking users in any way. Can browser-update.org be removed from the list?

**Comment by okiehsch** [comment]
@josselex 
I asked internally what other's thought about the filter `||browser-update.org^$3p` in `uBO-privacy` and if it should be removed.
There are different opinions from 
"I don't have a strong opinion about this, beside finding the service doubtful" to 
"Keep it blocked as 3rd party, websites shouldn't be checking and telling users to update their browser via 3rd party js, it's none of their business." or
"For me it's only an annoyance".

The fact that the request is also blocked by Firefox's tracking protection.
![image](https://user-images.githubusercontent.com/886325/68083421-cd6b0280-fe28-11e9-8e37-64913179cc18.png)
lead to a majority beeing in favour of keeping the filter in place.

Personally I don't think it is a good idea to have any third-party script checking the browser used
 and  - if the browser is considered outdated -  triggering a notification that alerts the user to "update your browser". 
If somebody asks me what they should do if they encounter such a notification I would certainly advise them to not click on it especially of they encountered it on a site like `fapxl.com`. 😉 
This issue is a case in point, the OP suspected that the notification is malicious.

**Comment by josselex** [comment]
@okiehsch
Thanks for your answer.
Maybe let me describe the rationale behind our project:
The project was born when webdevelopers had problems struggeling with decade old browsers still in use (Internet Explorer 6) which strongly affected how to build websites and was also a high security risk for users still using it.
That's why we wanted to give website owners the possibility to tell their visitors to update / switch their browser. We do this as a 3rd party because if every website implements this for themselves, a lot of users will be blocked or notified for no reason, because it is a lot of work to do this correctly.
Secondly we wanted to be sure that we take a lot of measures to not annoy users: showing the notification only one every day, giving the possibility to never show again, offer the users a selection of browsers available for their system. And we do not lock out users but only notify them, and try to fight this practice with this project.

Of course some users are still annoyed, but I think if every website would implement this for themselves, the situation would be much worse (blocking users from using the site, not taking care of small browsers, wrong notification, ...). And so far almost 40 million users updated their browser (about 5 million switched to cool alternatives like Firefox!! see http://browser-update.org/stat.html).

Of course doing it as a 3rd party is not perfect, that's why website can also self-host the script. But only for a minority of sites using the script, can do it that way.

Regarding the thought that the notification is malicious :
We are around for more than 10 years, and in fact I think one of the only notifications not malicious. So let's block the malicious one and not the legit ones :)
We point out at the update site that we do not offer downloads, but forward to the browser vendor's website.
And we do not track users! We only set one 1st party cookie with only the information if a user does not want to see the notification anymore.

Thanks''s for pointing out the point abaout Firefox. I will look into that. I discovered that we have one cross site cookie, but not set by us, but by our hoster (cloudflare), maybe that's why they think we're tracking. I will contact them and try to get rid of the cookie of our hoster.
