### ISSUE TITLE
pornhub.com [NSFW]

### ISSUE THREAD

**Issue by yspmedia** [uBlockOrigin/uAssets#5827]
### URL(s) where the issue occurs

`https://www.pornhub.com/view_video.php?viewkey=ph5cc8194f173ca`

### Describe the issue
same as #5799

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: FF 67.0.1 (64-bit)
- uBlock Origin version: v1.14.18

### Settings

- [List here all the changes you made to uBO's default settings]
- none
- Filters updated 5 mins ago..

**Comment by dumbusernameidk** [comment]
can't reproduce on chrome w/latest filters.

**Comment by mapx-** [comment]
> version: v1.14.18

@yspmedia why using that old version ?

**Comment by krystian3w** [comment]
maybe typo `9` to` 4` misclick?

**Comment by kulfoon** [comment]
> krystian3w : https://github.com/uBlockOrigin/uAssets/issues/5827#issuecomment-502403837 : maybe typo `9` to `4` misclick?

- There is no 1.19.18 version of uBO
- `9` and `4` do not lie side by side.
- I can't install 1.14.18 from the GitHub in Firefox 67 due to "extension is damaged".
- To type numbers / letters with the mouse clicks one had to use screen keyboard.

If yspmedia didn't mean 1.14.18, perhaps he meant v1.18.14 (however it's a bit old too).
