### ISSUE TITLE
thewrap.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#587]
An extreme amount of ad requests being made every second on http://www.thewrap.com. 250 requests for me while spending only about 4 minutes on the page. Most requests seem to be from the video player.

**SS:** https://i.imgur.com/7k3jUFJ.png
**Error URL:** http://www.thewrap.com/imax-moving-away-3d-consumers-shown-strong-preference/

_**Note:** Using uBO 1.13.8 on Chrome 59 with the default filters and settings._

**Comment by okiehsch** [comment]
What is your issue exactly?
Do you think this site fires that amount of requests because of some faulty filter?
The site loads fine on my end and there is no issue because of the blocked ad requests, as far as I can see.
It is not unusal to have a high amount of blocked ad requests on sites with an active video player.

**Comment by gorhill** [comment]
@gotitbro Please investigate before opening an issue here that there is an actual issue, not a presumed one along with asking that _someone else_ to validate your presumption that something _maybe_ is wrong.

Closing, will reopen if a case is made there is an _actual_ issue.

**Comment by gotitbro** [comment]
>not a presumed one along with asking someone else to validate your presumption

@gorhill Ok, got it
