### ISSUE TITLE
gorun.gr login frame doesn't show with ublockorigin on

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#5881]
https://gorun.gr/activity/#login

when ublockorigin is on, I can't get the login frame to show,
I tried to find the culprit with the logger,
but I didn't manage to,

can somebody help?

![Clipboard01](https://user-images.githubusercontent.com/24896778/60248131-a9bc0c80-98ca-11e9-8167-d909266f89f0.jpg)

got it:

```
@@||gorun-gr.r.worldssl.net^$script,domain=gorun.gr
@@||gorun.gr/wp-content/*$script,first-party

```

**Comment by mapx-** [comment]
@kargig @ryanbr

**Comment by kargig** [comment]
First of all please post the list of your adblock filter lists when you post about a problem, it's really hard to track what could be wrong otherwise.

With some testing I saw that the popup/login mentioned in this issue is getting blocked by "Fanboy’s Annoyance List". I don't think that either uBlockOrigin or [Greek adblock list](https://github.com/kargig/greek-adblockplus-filter) can/should do anything about that. IMO whitelisting should be done by the filter that's originally blocking the resources, not from any other.

**Comment by okiehsch** [comment]
>  I don't think that either uBlockOrigin or Greek adblock list can/should do anything about that. IMO whitelisting should be done by the filter that's originally blocking the resources, not from any other.

`uBO` will only add filters for issues that can be reproduced with a default setup.
`Fanboy’s Annoyance List` is not enabled by deault.
