### ISSUE TITLE
Problem with IDN sites.

### ISSUE THREAD

**Issue by BratSinot** [uBlockOrigin/uAssets#593]
### URL(s) where the issue occurs
For example on http://www.кингисепп-сегодня.рф/

### Describe the issue

For example, i want block **##.b-main-page-news-2__secondary-news** ads. So i create custom filter **www.кингисепп-сегодня.рф##.b-main-page-news-2__secondary-news**, but this didn't work. If i change this filter to **##.b-main-page-news-2__secondary-news** everything works fine.

### Screenshot(s)
![1.png](http://i.imgur.com/rwJbABE.png)
![2.png](http://i.imgur.com/CTCpS76.png)

### Versions

- Browser/version: Firefox 52.2
- uBlock Origin version: 1.13.8

### Settings

- Enable _Adblock Warning Removal List_ and _Anti-Adblock Killer | Reek_

### Notes

I think this problem connect with IDN DNS. Because i didn't see problem with English, only with Cyrillic syte.

**Comment by gorhill** [comment]
This is a uBO issue, not a filter issue.

The issue does not exist for:
- Chromium + uBO [whatever version]
- Firefox + uBO 1.13.9b0+

This was reported already: <https://github.com/gorhill/uBlock/issues/1937>.

I just forgot about it, it something I should have fixed a longtime ago. This was fixed with <https://github.com/gorhill/uBlock/commit/f1036395f71eb9616988c92279b362c092e0a463>.

I don't know whether I should release a version uBO/legacy 1.13.10 with the fix on AMO. You mind using the beta version from <https://github.com/gorhill/uBlock/releases>? This will be inevitable at some point since only the uBO/webext version will be on AMO.

**Comment by gorhill** [comment]
This is fixed in [1.14.6](https://github.com/gorhill/uBlock/releases/tag/1.14.6). You can use the latest version in the dev channel on AMO: <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta>.
