### ISSUE TITLE
Here Maps blocked while using Disconnect's Malvertising filter

### ISSUE THREAD

**Issue by gacelisnothing** [uBlockOrigin/uAssets#63]
### Issue

On entering `here.com`, uBlock politely blocked the site. I checked my filter lists to check on conflicts, and Disconnect's malvertising filter, which I've activated, caused the block. No other filters, as I've known has included `here.com` in any way.

Additionally, I purged the cache of the list, but it is still there.

### Browser, OS, and uBlock Origin version information

- Windows 10 version 1511 64-bit
- Mozilla Firefox 47.0
- Greasemonkey and Stylish installed, but turning off them does not resolve the issues anyway
- uBlock Origin 1.7.0

### Notes

- HERE.COM, as far as I known, was used as a filler mail address (like `mail@here.com`) for some demonstration of exploits instead of `example.com` (which would be obvious that this domain is really an example and it was 'safe' to block anyway).
- No other filters affected Here's block. I've enabled all of "Malware domains", no other filter settings were changed
- I haven't sent Disconnect a mail about this yet.

**Comment by gorhill** [comment]
uAssets will deal with issues caused by the default filter lists only, and even then, sometimes the fix will be left to maintainers of EasyList/EasyPrivacy when there is an issue with these.  _Malvertising filter list by Disconnect‎_ is not a default filter list -- you will have to report this to maintainers of that list.
