### ISSUE TITLE
[Resource abuse] dna-delivery.com

### ISSUE THREAD

**Issue by Amymone** [uBlockOrigin/uAssets#6433]
### URLs

`https://www.france.tv/france-2/direct.html`
`https://www.france.tv/actualites-et-societe/magazines-d-actu/860147-glyphosate-comment-s-en-sortir.html`

Sadly I think you need to be geolocalized in France for the video to play.

### Issue

The pages consume a lot of upload while the video is playing. I'm on wifi and it seems to take the entire bandwidth. I can feel the difference since downloads are also slower as a result.

I just played the video, I didn't opt-in to anything, and it seems to me that the website uses my connection to stream the video to other people. I think this is a blatant case of resource abuse, just like a crypto miner would use your CPU without asking. 

I couldn't find an opt-out setting, but I might have missed it.

![Crazy upload !?](https://i.imgur.com/Q912e6t.png)

- Browser version: Firefox 69.0.2
- uBlock Origin version: uBlock Origin 1.22.4

### Notes

I narrowed down the issue to the host `backend.dna-delivery.com`, because there are a lot of post requests to this host while the video is playing. Blocking it prevents the background upload  but doesn't prevent the video from playing. However I didn't find any abnormal upload in the browser console.

![HTTP traffic to backend.dna-delivery.com](https://i.imgur.com/dAFxJsH.png)

Among the information sent to this host, there are traffic counters with fields named "upload" and "p2p" so I guess it's some kind of peer to peer system which uses your connection to stream the video. It probably uses webRTC to stream it, which would explain why the traffic is not visible in the console, but I don't really know much about it.

![Upload meter in sent data](https://i.imgur.com/COuivls.png)

**Comment by llacb47** [comment]
Cannot view in US.
![image](https://user-images.githubusercontent.com/16567977/66719664-eef44380-edc0-11e9-98ac-2f89ed34e238.png)

**Comment by mapx-** [comment]
I see no opt-in /out option on page, I confirm

`||backend.dna-delivery.com^$domain=france.tv`

fixes without breaking the streaming

**Comment by Amymone** [comment]
Thanks for the fast answers, and sorry about the videos being blocked in the US.

Googling "backend.dna-delivery.com" points to this post: https://boards.4channel.org/g/thread/73093054/websites-can-leech-your-full-upload-and-expose
They say it's used on Dailymotion, but I don't see the behavior with Dailymotion.

I can indeed see it on `https://www.tf1.fr/tf1/direct` after creating a dummy account (it doesn't verify the email address), but I'm sure it will also be blocked for most countries outside France...

**Comment by okiehsch** [comment]
Why only for mobile?
If there is no opt-in or atleast a warning it should be added to the resource abuse list, in my opinion.

**Comment by okiehsch** [comment]
Does adding `france.tv##+js(nowebrtc)` also work?

**Comment by mapx-** [comment]
see also https://forums.lanik.us/viewtopic.php?f=62&t=43654

**Comment by okiehsch** [comment]
I see , so you don't think it should be blocked for all devices.
@gorhill what do you think?

**Comment by gorhill** [comment]
Bandwidth abuse is abuse regardless of the device, the filter should apply everywhere.

**Comment by gwarser** [comment]
For reference https://github.com/uBlockOrigin/uAssets/issues/3619

**Comment by llacb47** [comment]
Why is the filter limited to just that domain? The forum threads linked above show that thus service is used on many sites.

**Comment by okiehsch** [comment]
If it is used as an opt-in I don't think it should be blocked.

**Comment by llacb47** [comment]
Here's one: `https://www.rt.com/on-air/rt-uk-air/` Also you may want to consider changing the rule to `||streamroot.io^$domain=...` since that is the original script that loads the `dna-delivery` stuff. (if it is the same way on the `france.tv` site)

**Comment by okiehsch** [comment]
I can't check the `france.tv` site, let's wait until someone can confirm that `||streamroot.io^$domain=france.tv` works.

**Comment by llacb47** [comment]
Another site with no opt-in: `https://www.digitalconcerthall.com/en/concert/22386` Test account: Username: `pivajolaf@mail62.net` Password: `pivajolaf@mail62.net`

**Comment by okiehsch** [comment]
I can't reproduce any noticable upstream spikes on my end. with those two domains.
At `https://www.rt.com/on-air/rt-uk-air/`  my upstream spiked at 5 MiB/s

**Comment by Amymone** [comment]
I can confirm upload spikes on `https://www.rt.com/on-air/rt-uk-air/`. It's also the case for `sporttube.com` and `eurovisionsports.tv` but it's less noticeable, maybe because video quality is lower.

I tried `||streamroot.io^$domain=france.tv`, I think it prevents uploading but there are still a few requests to backend.dna-delivery.com, strangely. However `||streamroot.io^$domain=rt.com` prevents the video from playing on `https://www.rt.com/on-air/rt-uk-air/` for me, it gets stuck with the buffering animation.

**Comment by llacb47** [comment]
Maybe you didn't purge your cache of those sites after adding those filters, and that's why some requests were left over.

**Comment by Amymone** [comment]
I did disable cache in the network console. The first requests to backend.dna-delivery.com come from `https://www.france.tv/build/js/desktop.fcb05db119e20ff9806f.bundle.js`, so it seems to me there is also a bundled script independently calling dna-delivery.

**Comment by llacb47** [comment]
Oh, that makes sense. As for the RT issue, maybe it is region-related, I will test it when I get the chance.

**Comment by Amymone** [comment]
> I can indeed see it on `https://www.tf1.fr/tf1/direct` after creating a dummy account (it doesn't verify the email address), but I'm sure it will also be blocked for most countries outside France...

Did somebody have the chance to check this one?

**Comment by mapx-** [comment]
I get only `https://cdn.streamroot.io/dna-client/5.15.1/dna-client.js` but no 
`backend.dna-delivery.com` requests or upload spikes

**Comment by llacb47** [comment]
@Amymone `https://www.rt.com/on-air/rt-uk-air/` plays fine for me when blocking `streamroot.io`.

`https://www.tf1.fr/tf1/direct` blocked in United States.

**Comment by Amymone** [comment]
`tf1.fr` has been puzzling me because it doesn't call `backend.dna-delivery.com` like the others but I still have the upload spikes on my side. I think I found the reason: it calls `strmt.tf1.fr` instead with the same requests.

**Comment by Amymone** [comment]
@llacb47 I re-checked, it indeed plays fine. Sorry, it seems I messed up the first test :woman_shrugging:
So blocking `streamroot.io` might also be an option. It works for `tf1.fr` too.

**Comment by gusai-streamroot** [comment]
Hello uBlockOrigin maintainers,

First and foremost, thanks for your active role in making the internet better.

I am the owner of [CDN Mesh Delivery product](https://streamroot.io/cdn-mesh-delivery/): we noticed a drop in our users for customers France Televisions and Russia Today, due to our service “backend.dna-delivery.com”, being blocked since this issue (6433) in uBlockOrigin.

France Televisions specifies in its terms & conditions -for free watching of content- that high usage of bandwidth is expected: "2.2.1 L’accès à certains services sur et/ou depuis les Sites et Applications FRANCE TELEVISIONS peut être subordonné à l’acceptation de conditions spécifiques d’utilisation et/ou de vente auxquelles tout Utilisateur souhaitant accéder auxdits services doit adhérer. Les Applications sont gratuites hors coût d’abonnement Internet à l’opérateur et hors surcoût éventuel facturé par l’opérateur via les Applications, pour le chargement et l’envoi des données. L’utilisation des applications pouvant engendrer une consommation importante de données, particulièrement la consultation de vidéos, FRANCE TELEVISIONS recommande l’utilisation des Applications dans le cadre d’un forfait adapté, type « illimité » ou en mode Wifi." (https://www.francetelevisions.fr/cgu, section 2.2.1.)

Russia Today specifies in its terms & conditions that "[RT] do not warrant that: [...] iv. the results of using the services will meet your requirements. Your use of the services is solely at your own risk." (https://www.rt.com/terms-of-use/, section Limitation of Liability, paragraph 4.)

In addition to the T&C:
- Broadcasters can leverage [our activation/deactivation API](https://support.streamroot.io/hc/en-us/articles/360008861134) to let viewers opt-in / opt-out of peer-to-peer.
- We already have many mechanisms in place to protect users from overuse of resources (bandwidth, CPU, RAM), e.g. as per article "I’m concerned about overloading my viewers’ upload bandwidth" in [FAQ](https://streamroot.io/faq/).

I got the PullRequest [8428](https://github.com/uBlockOrigin/uAssets/pull/8428) closed without any explanation, mentioning just a link to a [previous comment](https://github.com/uBlockOrigin/uAssets/issues/6433#issuecomment-541453547) on this issue that does not apply to our specific case:

> Bandwidth abuse is abuse regardless of the device, the filter should apply everywhere.

Our solution is not abusing of bandwidth: as clearly stated in France Televisions and Russia Today T&C, a viewer agrees to high usage of bandwidth to be able to watch the videos free of charge.
A person that does not agree to these T&C must NOT use the service at all, therefore the fruition of the service without our solution active (due the uBlockOrigin rule) is an infringement of the aforementioned T&C.

For all the aforementioned reasons, would you please consider the removal of “backend.dna-delivery.com” from the list of blocked domains?

I thank you in advance for your understanding and cooperation.

Thanks in advance and best regards,
Giovanni Usai
name_dot_surname_at_lumen_dot_com

PS: I am sorry, I opened duplicate PR [8429](https://github.com/uBlockOrigin/uAssets/pull/8429) as the previous one had been closed without any explanation and I couldn't reopen it.

**Comment by uBlock-user** [comment]
your thoughts @gorhill ?

**Comment by gusai-streamroot** [comment]
Hello @gorhill ,

thank you for taking the time to answer.

I understand well where this comes from.
To be completely transparent, we encourage our customers to implement an opt-out (we provide [the API](https://support.streamroot.io/hc/en-us/articles/360008861134) for them to do so).

That being said, I'd like to understand better your view of what is the "reasonably expected bandwidth" consumed? Bear in mind that our system will push most of the upload to users who have high available upload bandwidth (we apply the same technique as TCP to detect congestion and aggressively stop upload if we do detect it).
So most users actually benefit from our solution by getting less rebuffering and the ability to watch videos in higher bitrates. 
I understand well that from an outside perspective our technology might seem invasive and aggressive but I'd love to take 10minutes of your time and propose a different vision here.

Thanks again for your time and best regards,
Giovanni Usai
name_dot_surname_at_lumen_dot_com

**Comment by uBlock-user** [comment]
>  we encourage our customers to implement an opt-out

Must be _opt-in_, and not the other way around, that's what explicit user consent is meant.

**Comment by gusai-streamroot** [comment]
Hello, 

sorry, when I wrote _opt-out_ I meant both ways.
Depending on the usage of variables for [our activation/deactivation API](https://support.streamroot.io/hc/en-us/articles/360008861134), customers can do implement _opt-in_ as well, and this is what we suggest to them.

Again, your reply doesn't seem pertinent and I ask reconsideration of our case to @gorhill .

Thanks in advance and best regards,
Giovanni

**Comment by mapx-** [comment]
> customers can do implement opt-in

but they didn't. So, you should ask your customers to implement such functionality. When the users will have the explicit choice on-screen we'll remove those filters.

**Comment by gorhill** [comment]
>  your reply doesn't seem pertinent

T&C does not trump explicit user consent. I don't know how else it can be states more clearly.

**Comment by Amymone** [comment]
How about applying the same rule to `tf1.fr` as suggested earlier since it has no opt-in either? (French only again sorry) Blocking `streamroot.io` there instead of `dna-delivery.com` does the job for me.

**Comment by CrazzyIvan** [comment]
The resource abuse continues on `france.tv` as the company has changed the domain names to evade the blocking (that's way easier than enforcing a proper opt-in, apparently).

The calls to their services are now using the alias domain `backend.irsdn.net` instead of `backend.dna-delivery.com`. Additionally, their script is now downloaded from `cdn.irsdn.net` (it seems that it was downloaded from `streamroot.io` before).

The filter should be updated, however I guess they are going to pull the same naive trick again. I suggest switching the filter to `france.tv##+js(nowebrtc)` as suggested earlier by @okiehsch to solve the problem once and for all. I just tested and it works perfectly.

**Comment by Amymone** [comment]
`france.tv##+js(nowebrtc)` works for me!

**Comment by dest4** [comment]
Hello there, Streamroot developer speaking to follow up on this topic.
Could we find a middle ground regarding the following entries? https://github.com/uBlockOrigin/uAssets/blob/58666c47c8e2e75976fc92b833ecd809afd7f5be/filters/resource-abuse.txt#L115-L119

Here would be the plan:
1) we somehow feature detect the presence of ublock origin in our stack. Is there a reliable way to do that that does not involve a network request? Otherwise, if policy permits:

- we could create a (nowebrtcupload) scriptlet that would expose a flag, say `window.__nowebrtcupload__ = true`. 
- alternatively, add a special HTTP header to requests to `backend.dna-delivery.com` and friends.

2) if flag is detected, we keep WebRTC connectivity on, but disable upload of bulk media content, which voids the resource abuse issue. The amount of data exchanged (RX/TX) will be very similar to the scenario where only the HTTP stack is active.

**Comment by mapx-** [comment]
@gorhill
