### ISSUE TITLE
Websites That Still Show Ads

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#6465]
https://www.vesti-online.com/
http://www.rts.rs
https://pcpress.rs
https://www.blic.rs
https://www.happytv.tv/
https://idjtv.com
https://dnevnik.hr/
https://novosadska.tv/
http://www.rtvpink.com/
http://www.pink.rs/
https://www.danas.rs

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/README.md

> If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

**Comment by okiehsch** [comment]
If you can make the case that extended syntax is necessary I will reopen.
Only dumping a list of sites that show "ads" is not sufficient.

**Comment by GKid94** [comment]
What is the syntax and how do I know if it's needed for the issue to be fixed

**Comment by krystian3w** [comment]
`-abp-contains` / `-abp-has` should be moved to EasyList.

**Comment by okiehsch** [comment]
> What is the syntax

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#procedural-cosmetic-filters

> how do I know if it's needed for the issue to be fixed

Rule of thumb is "normal" banner ads don't need extended syntax and can be fixed in `EasyList`.
Extended syntax is mostly needed to deal with 
- anti-adblock
- ad-reinsertion
- popups/popunders
- video ads

**Comment by GKid94** [comment]
Those websites have normal picture ads

**Comment by okiehsch** [comment]
You can open an issue at https://github.com/easylist/easylist/issues

**Comment by GKid94** [comment]
Ok thx
