### ISSUE TITLE
seriescr.com stops at Cloudflare ddos page

### ISSUE THREAD

**Issue by kwade00** [uBlockOrigin/uAssets#6478]
### URL(s) where the issue occurs

`https://seriescr.com/`

### Describe the issue

They always keep Cloudflare in 'attack mode'. Loading stops on the Cloudflare 'Checking browser' screen. Hangs on this rule:
seriescr.com##+js(nobab)

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Waterfox 56.2.14
- uBlock Origin version: 1.23.0

### Settings

- Filters used (besides this one):
Badware, Privacy, Resource Abuse, Unbreak, EasyPrivacy, Malware Domain List, Malware Domains, Peter Lowe's

### Notes

If I disable the filter, then re-enable it without updating, this rule no longer appears and the website works. If I click update, the ruleset changes significantly and this rule re-appears, even though both rulesets show a 'last updated' date of 2019-06-01.
Also, no ad-blocker warning appears with 'nobab' removed from the rules. I know they have one, because I have another browser using only ABP without uBO and I get the warning there. It appears uBO is handling this ad-blocker-blocker just fine somewhere else.

**Comment by uBlock-user** [comment]
because of `seriescr.com##+js(nobab)` 

Internal team discussion -- https://github.com/orgs/uBlockOrigin/teams/ublock-filters-volunteers/discussions/245

**Comment by okiehsch** [comment]
An earlier internal discussion about cloudflare ddos and `bab-defuser`. https://github.com/orgs/uBlockOrigin/teams/ublock-filters-volunteers/discussions/204

**Comment by llacb47** [comment]
I'm sure it was an interesting discussion :))

**Comment by okiehsch** [comment]
**bab-defuser on sites using cloudflare ddos protection**

The filter will break the browser check, so the site will never load.
Examples: NanoMeow/QuickReports#1161 (comment) and uBlockOrigin/uAssets#907 (comment)

Alternative filter `##+js(setInterval-defuser.js, visibility, 1000)` works fine and can be used for those sites.

 @gorhill
gorhill on May 9
This is a problem, the documentation for eval says:

If you use the eval function indirectly, by invoking it via a reference other than eval, as of ECMAScript 5 it works in the global scope rather than the local scope.

uBO needs to call via reference in order to trap eval, so the cloudflare script broke because it expected the local scope to be available. Not sure if that can be fixed in bab-defuser.js.

 @okiehsch
okiehsch on May 9 • 
 Author
No problem, we can use the setInterval or generichide filter for sites using cloudflare/ddos and blockadblock.
