### ISSUE TITLE
navbharattimes.indiatimes.com | Breakage

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#6564]
### URL(s) where the issue occurs

`https://navbharattimes.indiatimes.com`

### Describe the issue

The page becomes blank once the site has fully loaded.

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

Default

**Comment by ghajini** [comment]
Yes I was just suppose report this
recent rule (by @okiehsch brother)

indiatimes.com##+js(std, objSubPromo)

Is causing breakage

**Comment by ghajini** [comment]
I explained them here also not to generalise rule on indiatimes.com but only on specific site

https://github.com/NanoMeow/QuickReports/issues/785#issuecomment-552501863

https://github.com/NanoMeow/QuickReports/issues/785#issuecomment-552501863

**Comment by llacb47** [comment]
Oops, sorry about that...

**Comment by okiehsch** [comment]
> indiatimes.com##+js(std, objSubPromo)
Is causing breakage(all news pages including home page gone blank)

My bad, I should have tested other `indiatimes` pages before adding that filter.

**Comment by ghajini** [comment]
### URL=

`https://navbharattimes.indiatimes.com/metro/mumbai/power-road-and-water/scam-is-more-electricity-bill-bjp-leader-kirit-somaiya-accused/articleshow/77435670.cms`

### Issue=

Amazon widget ads

### Platform =

Firefox mobile nightly 82.0.1
Ublock origin 1.29.2

### Screenshot(s)=

https://user-images.githubusercontent.com/20338483/92319380-1b4a2b80-f035-11ea-9a31-3bb8e222177c.jpg

https://user-images.githubusercontent.com/20338483/92319388-2bfaa180-f035-11ea-859e-75430d81804a.jpg

### Filters =

`navbharattimes.indiatimes.com##.parallaxDiv.ad1`

`||malayalam.samayam.com/off-url-forward/amazon_widget.cms$subdocument,domain=navbharattimes.indiatimes.com`

**Comment by ghajini** [comment]
**issue=**

embed video doesn't play

**url=**

`https://navbharattimes.indiatimes.com/state/madhya-pradesh/bhopal/kandahar-plane-hijack-bhopal-honeymoon-celebrating-returning-couple-told-175-hour-horror-story-after-21-years/articleshow/79937039.cms`

**screenshot=**
https://user-images.githubusercontent.com/20338483/103074418-8bce8580-45ef-11eb-8009-2e1b1a6f34ea.png

due to easylist rule `||imasdk.googleapis.com^$3p`
adding this work `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=navbharattimes.indiatimes.com`

firefox,ubo1.31
