### ISSUE TITLE
Techradar Anti Adblock Popup

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#6580]
Techradar shows a anti adblock popup https://www.techradar.com/news/free-email-client

![4324234](https://user-images.githubusercontent.com/18757054/69002226-ea083f80-08ea-11ea-830f-40d5b86c2597.jpg)

**Comment by okiehsch** [comment]
Already fixed in the `uBO-annoyances` list. That list is not enabled by default you have to enable it.
![image](https://user-images.githubusercontent.com/16838044/69002270-3acc6800-08ec-11ea-8783-0073f554c18a.png)

You can continue to use the site by simply clicking "Continue with Adblocker", so as far as uBO is concerned that is only an annoyance and no anti adblock wall.

**Comment by GKid94** [comment]
Ok thx
