### ISSUE TITLE
How to skip video ads this website

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#6588]
`https://cartoonth12.com/yu-gi-oh-%E0%B8%A2%E0%B8%B9%E0%B8%81%E0%B8%B4-gx-ss2-67/`

### Describe the issue

How to skip video ads this website

### Screenshot(s)

![ภาพ](https://user-images.githubusercontent.com/43577606/69051885-29907200-0a38-11ea-8c03-37218b2f7212.png)

### Versions

- Browser/version: firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

![ภาพ](https://user-images.githubusercontent.com/43577606/69051905-3c0aab80-0a38-11ea-8547-7e4a0fa9d5db.png)

### Notes
Thanks in advance

**Comment by Fuyuppe** [comment]
Thank you

**Comment by Fuyuppe** [comment]
![ภาพ](https://user-images.githubusercontent.com/43577606/69056474-a1fc3080-0a42-11ea-8591-f6a518ba5503.png)
Why this website still detect when I press F5

**Comment by mapx-** [comment]
Did you update uBo filters list ?

**Comment by mapx-** [comment]
You should use only uBo default lists, you added as custom lists a lot of other lists which could generate some conflicts if you don't know what's their goal

**Comment by Fuyuppe** [comment]
> 
> 
> Did you update uBo filters list ?

Of course
sometime work 
![ภาพ](https://user-images.githubusercontent.com/43577606/69057099-dcb29880-0a43-11ea-91e1-c72b0d9d9362.png)


But when I press F5 

![ภาพ](https://user-images.githubusercontent.com/43577606/69057135-e936f100-0a43-11ea-97a8-ac0c48bcad0b.png)

Same url 
https://cartoonth12.com/yu-gi-oh-%E0%B8%A2%E0%B8%B9%E0%B8%81%E0%B8%B4-gx-ss2-67/
You should try to do

**Comment by mapx-** [comment]
What if you add this filter too 
`@@||cartoonth12.com^$generichide`

**Comment by Fuyuppe** [comment]
> @@||cartoonth12.com^$generichide

Ok now working
I'm really thank you

**Comment by garry-ut99** [comment]
### 1

Anti-adblock is back, example video: `https://cartoonth12.com/douluo-dalu-soul-land-%e0%b8%95%e0%b8%b3%e0%b8%99%e0%b8%b2%e0%b8%99%e0%b8%88%e0%b8%ad%e0%b8%a1%e0%b8%a2%e0%b8%b8%e0%b8%97%e0%b8%98%e0%b9%8c%e0%b8%a0%e0%b8%b9%e0%b8%95%e0%b8%96%e0%b8%b1%e0%b8%87-14/`

### 2

Ads are back: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219874993-faf1dd09-b2ad-4783-af7a-59c2af934c03.png) - a new `.webp` graphic extension appeared since then:
https://github.com/uBlockOrigin/uAssets/blob/fc28599fdbae3a5b44231e97181bf087ae04f737/filters/filters.txt#L15902

**Comment by garry-ut99** [comment]
Now can't watch videos at all, video is black, no play button, when I added `cartoonth12.com#@#.video-player.responsive-player`, at least play button is back and video is trying to load, but then anti-adblock appears.

As for ads, they are gone, but it's weird `*.webp` have been fixed by cosmetic filters, despite `*.gif` were fixed by network filter in the past.

**Comment by mapx-** [comment]
> Now can't watch videos at all, video is black

see the video container (left bottom)
![image](https://user-images.githubusercontent.com/10303732/219881542-135b1e38-0b97-4025-bb39-eb5297270f10.png)

meaning: `select video server` (`เลือกเซิฟเวอร์วีดีโอ`)

click it, you'll see
`main video` (`วีดีโอหลัก`)

click it
