### ISSUE TITLE
Ad placeholders on myanimelist.net

### ISSUE THREAD

**Issue by txtsd** [uBlockOrigin/uAssets#6730]
### URL(s) where the issue occurs

https://myanimelist.net/anime/21/One_Piece

### Describe the issue

Ad placeholders should not show.

### Versions

- Browser/version: Firefox 72.0b9
- uBlock Origin version: 1.24.2

### Notes
This filter gets rid of them:
`myanimelist.net##.mal-ad-unit`

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by krystian3w** [comment]
similar: https://github.com/easylist/easylist/issues/4589

**Comment by krystian3w** [comment]
Also I see pop-up with Cookies/Privacy Policy:

`myanimelist.net##.modal-content:-abp-has(.text > b:-abp-contains(Privacy Policy))`

@kiboke you accept this in addon only?

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/README.md

If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

- anti-adblock
- ad-reinsertion
- popups/popunders
- site breakage
- video ads
will always be fixed in uAssets even if they don't require extended syntax.

**Comment by krystian3w** [comment]
`myanimelist.net#?#.modal-content:-abp-has(.text > b:-abp-contains(Privacy Policy))`

EasyList Cookies avoid use `-abp-has` / `-abp-contains`


@okiehsch

**Comment by okiehsch** [comment]
Addressed in annoyances.

**Comment by kiboke** [comment]
> Also I see pop-up with Cookies/Privacy Policy:
> 
> `myanimelist.net#?#.modal-content:-abp-has(.text > b:-abp-contains(Privacy Policy))`
> 
> @kiboke you accept this in addon only?

No, all cookie warning on this site are hidden by css rules.
