### ISSUE TITLE
mediafire.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6867]
### URL(s) where the issue occurs

`http://www.mediafire.com/error.php?errno=320&origin=download`

### Describe the issue

Fake button

### Screenshot(s)

<img width="815" alt="fkebutton" src="https://user-images.githubusercontent.com/48647394/72989617-e7483000-3dee-11ea-9ddc-5a86e83a6959.PNG">

### Versions

- Browser/version: Firefox 72.0.2
- uBlock Origin version: uBlock Origin v1.24.2

### Settings

[settings.txt](https://github.com/uBlockOrigin/uAssets/files/4103329/settings.txt)

**Comment by Raidware** [comment]
there are extra scape due to ads. @mapx- 

`https://www.mediafire.com/file/t0073wm5od8z3mw/X-Ray_1.18.2.mcpack/file`
![Screenshot_20241108_181820](https://github.com/user-attachments/assets/56ccd2fe-03c7-401a-899f-40c08eb1b49d)
![Screenshot_20241108_181832](https://github.com/user-attachments/assets/ffd3af8f-3fa2-461e-ae0c-50abd3d3c034)

**Comment by mapx-** [comment]
test

```adb
mediafire.com##.center:style(margin-top:50px !important)
```

**Comment by Raidware** [comment]
> test
> 
> ```
> mediafire.com##.center:style(margin-top:50px !important)
> ```

fixed
