### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#702]
"Check availability" hotel ads on `https://www.google.com/maps`.

**SS:** https://i.imgur.com/vSsZcF6.png

**Error URL:** `https://www.google.com/maps/place/TGI+Star+Holiday+Resort,+Yercaud/@11.7840942,78.2016393,17z/data=!3m1!4b1!4m5!3m4!1s0x3babf5d5da3ad68b:0x8d22fcb98680acdd!8m2!3d11.784089!4d78.203828?dcr=0`

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by okiehsch** [comment]
So you want to hide `Check availibility` feature of Google Maps?

**Comment by gotitbro** [comment]
They are ads are they not?

**Comment by mapx-** [comment]
It's a very useful feature.

You should hide it on your own @gotitbro

**Comment by gorhill** [comment]
I am thinking this is a primary feature of the site, hence it should not be blocked, but then at this link, <https://www.google.ca/search?hl=en&q=Hotel+Aradhana+Inn>, the same widget to check for availability is hidden with EasyList's `###rhs_block .mod > .gws-local-hotels__booking-module`.

**Comment by SMed79** [comment]
What about the tracking pixel?
https://forums.lanik.us/viewtopic.php?f=62&t=38242

**Comment by okiehsch** [comment]
Well, if you click one of the booking services you are getting redirected through `googletraveladservices.com` but I still would not disable the whole feature.

**Comment by gorhill** [comment]
Was the issue here ever brought up in EasyList forums?

**Comment by SMed79** [comment]
I ask only if it should be blocked here.

**Comment by gorhill** [comment]
@SMed79 you brought in another issue in the middle of another one and now the conversation is confusing. My comment was about the ads, OP's topic. Let's stick to this please.

**Comment by SMed79** [comment]
Sorry, i removed my above comments.

Please remove these too 
https://github.com/uBlockOrigin/uAssets/issues/702#issuecomment-330347571
https://github.com/uBlockOrigin/uAssets/issues/702#issuecomment-330350062

Thank You.

**Comment by gotitbro** [comment]
What did @SMed79 say?

With the same logic that this is useful so are google ads when searching for products. In the end these are just ads and as a user by installing an ad blocker I have already chosen to block these.

**Comment by okiehsch** [comment]
@gotitbro so you would dissable the booking feature of `google.com/flights` too?

![delt](https://user-images.githubusercontent.com/16838044/30570943-b7e41598-9ce4-11e7-969b-d6c4b15b4c2b.PNG)

Now in this example case I want to fly with delta and the Ads link me to the delta online booking service.
I would argue that this is one of, if not the, primary feature of google flights and should not be disabled.

**Comment by gotitbro** [comment]
That is a standalone Google Flight service, people expect to see this when they visit that website. Here, I am looking at a place in Google Maps but then am presented with the ads which I expected to be blocked.

**Comment by okiehsch** [comment]
I can see your point but you are only presented with the ads if you are looking at a specific hotel and one could argue that many people will expect to see the `check availibility feature` of Google Maps if they are looking at a specific hotel just like I expect to see the `booking feature` of Google Flight if I look at specific flight connections.

**Comment by uBlock-user** [comment]
```
google.com##.section-hotel-prices-container
google.com##.section-hotel-prices-header-container
google.com##.section-date-range-selection-container
```

**Comment by gotitbro** [comment]
@uBlock-user Thanks for that but I don't think filters are an issue here, the issue is whether these ads should be blocked or not it would be great if you could chime in with your opinion.

**Comment by uBlock-user** [comment]
They wouldn't be added because here the meaning of "Ad" differs here specifically. Here by "ads", Google is providing a service with the help of 3rd party service providers, it's not advertising some 
random malware/adware shit which is the usual case with blogs but rather advertising the "service" provided by 3rd party service providers making you aware that you can book it directly rather than doing it the old-school way. Hence these "ads" are essentially "services" provided by 3rd party service providers but Google calls them "Ads" as Google is **promoting** those 3rd party service providers. So it's a grey area and not as black and white which is the usual case.

This is why I posted the filters, they won't be added but if you don't want to see them, you can block them yourself.

**Comment by gorhill** [comment]
Consider this page: <https://www.expedia.ca/dailydeals?langid=4105&mcicid=home.topdeals.16524237>.

The same way it wouldn't make sense to remove the "Featured Hotel Deals" in the page above, because this is essentially a primary feature of Expedia, it looks to me that the availability lookup in Google Maps is in the same category.

If we agree with this, then we have to question why the same widget is being removed from the "Web" section of the site with this link: <https://www.google.ca/search?hl=en&q=Hotel+Aradhana+Inn>.

It's why it would be nice to have feedback about this from EasyList maintainers -- they are the ones who added the filter for this.

One argument which I can see could be made is because there is no way for EasyList to know whether the widget on the right-hand side of the page is really related to what was searched, while with Google Maps it is always related, because you have to click on the specific location.

**Comment by gotitbro** [comment]
@gorhill That is the issue here with Google Maps, I am trying to view info about the hotel. I don't necessarily wan't advertised booking to be shown to me especially if I have chosen to block them.

> widget on the right-hand side of the page is really related to what was searched

It is definite related to what was searched as Google uses the same Knowledge Graph on Google Maps that it does on search.

@ryanbr @khrin @monzta Please provide some insight.

**Comment by mark-otaris** [comment]
Some insight: https://easylist.to/2011/07/11/the-definition-of-advert-and-link-exchange-policy.html.

More insight: https://support.google.com/hotelprices.

Even more insight: https://easylist.to/pages/policy.html.
