### ISSUE TITLE
www.intego.com/mac-security-blog

### ISSUE THREAD

**Issue by dustinec** [uBlockOrigin/uAssets#7126]
### URL(s) where the issue occurs

`https://www.intego.com/mac-security-blog/`

### Describe the issue

When you visit the website for the first time (private browsing will trigger it) there is an overlay on the entire screen. It goes away when you click anywhere on the webpage.

### Screenshot(s)

![intego](https://user-images.githubusercontent.com/49384770/77219513-ea208200-6b0c-11ea-8f18-e0098592289d.jpg)

### Versions

- Browser/version: Firefox 74.0
- uBlock Origin version: 1.25.2

### Settings

`https://github.com/dustinec/firefox-settings/blob/master/ublock-settings.txt`

### Notes

This can be blocked with (ironically named) `www.intego.com##.roadblock`

**Comment by okiehsch** [comment]
@ryanbr With your annoyance list enabled it looks like the screenshot of the OP.
With a default setup it looks like this.
![image](https://user-images.githubusercontent.com/16838044/77219780-397ca780-6b39-11ea-80f6-461d62c1fac0.png)
The suggested filter of the OP works fine.

@dustinec this will not be fixed in `uAssets` it is not an anti adblock message, the purpose of the overlay, i.e. self advertisement, is broken by your annoyance list.
