### ISSUE TITLE
Brainly Ad Problem

### ISSUE THREAD

**Issue by TristramGreenman** [uBlockOrigin/uAssets#7195]
### 

`https://brainly.com/app/ask?entry=hero&q=bruh`

I made a previous post where I was given this code to put into my filters on ublock origin to fix the issue, 
`brainly.com##+js(abort-on-property-write.js, jsData)` 
But I think Ublock did something to where it completely deletes all the questions. There is suppose to be questions displayed in the link above but as you can see with ublock origin they are not displayed. I would like this fixed and have no ads on the answers when you click a questions. Thanks in advance for the help.

### https://gyazo.com/299da37c4cf78f98f672b609a2ee5a46 (what the problem currently looks like)
https://gyazo.com/7a3b47e4ac54c6590eff65424593b3a0 (what i want it to look like)
https://gyazo.com/1ce8750090a352c379a9f209dadaf52c ( i also want no ads on the answers)

### 

- Browser/version: [chrome/latest]
- uBlock Origin version: [1.24.4]

### https://gyazo.com/c780ee6d8d82f55771a084b281f76eed

- I have only added a "my filter" which would be this code 
`brainly.com##+js(abort-on-property-write.js, jsData)`

**Comment by JobcenterTycoon** [comment]
Anti Adblock message is back. Example: `https://brainly.com/question/1713545`

**Comment by tunceray1** [comment]
Please add the `eodev.com` domain name on line 8344.

`https://eodev.com/gorev/28356544`

<details>
 <summary> ad image</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/140217932/640a58cc-063a-4786-977a-cce8fffee1ac)


</details>

This cannot be reproduced with the adguard extension. The problem seems to be caused by uBlock Origin
