### ISSUE TITLE
some bad filters in uBlock Unbreak list

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#7319]
### URL(s) where the issue occurs

in uBlock Unbreak

### Describe the issue

1) bad filters, they won't work, coz ,`badfilter` option must be at the end of the filter, and not in the middle: 
https://github.com/uBlockOrigin/uAssets/blob/cd1dac34228b374f09ddd94c69d061b2858644c9/filters/unbreak.txt#L1269-L1271

2) btw. - I found them just accidentialy while gathering data for https://github.com/uBlockOrigin/uBlock-issues/issues/1008#issuecomment-624644557, coz uBO logger doesn't report them as invalid, so I wonder whether uBO just forgot that `,badfilter` unlike all other $options, cannot change it's order and must be placed at the end, perhaps uBO's parser bug?

### Versions

- Browser/version: Firefox 75 
- uBlock Origin version: 1.26.3b16

**Comment by gorhill** [comment]
`badfilter` can be anywhere in the option list, they were valid filters.

**Comment by mapx-** [comment]
ok .. however I updated the filters with the last from EL

**Comment by kulfoon** [comment]
> `badfilter` can be anywhere in the option list, they were valid filters.

That's odd, coz before I opened an issue, I was trying to disable some other filter by putting `,badfilter` somewhere inside between the other options, and it didn't work, and then as soon I put it at the end, it begun to work, unfortunatelly I don't remeber what was the filter I was trying to disable, now I checked again with some other filter and it worked, so I don't know, either a bug affecting just some of filters or perhaps some mistake at my side, I apologize then.

**Comment by uBlock-user** [comment]
```
@@||google.com^$ghide
@@||google.com^$badfilter,ghide
```

@gorhill That works but the filter count in `My filters` becomes `1 out of 1 `instead of `0 out of 0` ??

**Comment by gorhill** [comment]
badfilter'ed filters are reflected in the total count of network filters, not the per-list count. A filter in one list can be discarded due to a `badfilter` filter in another list, and the need to discard or not will not be known before all the `badfilter` filters have been loaded in memory, at which point the list(s) to which filters belong is information no longer available.

So in your case `My filters` contains a valid filter and is counted as such. It's later discarded because of the matching `badfilter`, which happens to be in the same list but it could well have been in another list.
