### ISSUE TITLE
zergnet.com

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uAssets#739]
I don't see `zergnet.com` domain blocked in any of the default lists.

For instance, try:

http://www.rollingstone.com/music/lists/tom-petty-50-greatest-songs-w506653/american-girl-w506655

Toggle off cosmetic filtering for the site, and see all those Zergnet-related "Around the web" appearing -- they were apparently blocked by some cosmetic filters somewhere (probably `##.zergnet-widget` in EasyList). Also, see how often the logger reports network requests from `zergnet.com`.

So I am wondering why is `zergnet.com` not wholly blocked just like `taboola.com` (blocked by @pgl) -- it's just the same kind 3rd-party bloated crap. Is it known to break stuff when wholly blocked?

Insights welcomed.

**Comment by gorhill** [comment]
At least for now I added a filter for `zergnet.com/zerg-inf-multi.js`, from perusing the content of the script, this should be safe, this at least prevents the site from being populated with zergnet widgets, which are anyways cosmetically filtered in EasyList.

**Comment by pgl** [comment]
@gorhill, I don't include `zergnet.com` because it at least *pretends* to be a content-driven site. I try really hard to avoid false positives, and arguably there's content on "ZergNet" that people might want to read. 

`taboola.com` on the other hand, styles itself as "Native Advertising".

**Comment by Zhangsun321** [comment]
yea.. i like zergnet when i have 'nothing to do'

**Comment by gotitbro** [comment]
@pgl @gorhill Zergnet is basically Outbrain/Taboola for publishers. Publishers pay Zergnet to promote their articles on sites of other publishers that have installed the Zergnet advertising "recommendation" widget on their websites.

Like an advertiser cycle for publishers basically https://www.zergnet.com/info.

These are just ads and should be blocked, at least the third party requests (so that users who wish to go to Zergnet can still do so).

Another thing to note is that Zergnet owns and heavily promotes its own websites through the Zergnet widget. These websites include (these are basically clickbait, sensationalist sites):
- Looper.com
- NickiSwift.com
- Grunge.com
- TheList.com
- Mashed.com
