### ISSUE TITLE
How to block "data:image/png;base64" on roundcube 

### ISSUE THREAD

**Issue by nauved** [uBlockOrigin/uAssets#7414]
### URL(s) where the issue occurs

Roundcube webmail Larry theme is now injecting data:image/png;base64 avatars for every user.  But these images pop up elsewhere too.  It's becoming an epidemic!  I'm hoping there might be a generic solution to block this visual assault wherever it appears.

### Describe the issue

uBlock Origin is unable to identify or "capture"  these "faux images".

### Screenshot(s)

Similar to the icon at the top left of this write screen.  They are ubiquitous.  Some are still actual images that can be blocked.

### Versions

- Browser/version: Firefox Quantum 68.7.0esr (32-bit)
- uBlock Origin version: uBlock Origin v1.20.0

### Settings

Not applicable afaik

### Notes

I only found one mention of "data:image/png;base64" at https://github.com/uBlockOrigin/uAssets/issues/212. And search elsewhere hasn't turned up anything so far.  Perhaps you could point me in the right direction to find a solution.

**Comment by Yuki2718** [comment]
1. Github issue is not for question. The correct place for question is https://www.reddit.com/r/uBlockOrigin/
2. URL is needed even if the issue is ubiquitous.
3. I believe there's no ubiquitous solution to data URL scheme but you can use HTML filter on Firefox to completely remove them unless peculiar encoding is used (per site, per selector solution). Ofc cosmetic filtering can hide them too.
