### ISSUE TITLE
cliqz.com

### ISSUE THREAD

**Issue by AlbertoGP** [uBlockOrigin/uAssets#743]
### URL(s) where the issue occurs

`https://cliqz.com/whycliqz/transparency`
`https://hpn-collector.cliqz.com` <- Data collection endpoints are under this host name.
`https://hpn-sign.cliqz.com/` <- Register, sign-up etc. are here.

Other endpoints and assets downloaded by the extension:
`https://cdn.cliqz.com/human-web/patterns`
`https://cdn.cliqz.com/human-web/patterns-anon`
`https://safe-browsing.cliqz.com/config`
`https://safe-browsing-quorum.cliqz.com/`
`https://safe-browsing-quorum.cliqz.com/config`

### Describe the issue

This is a Firefox extension which exfiltrates the user's browsing history.
It will be pre-installed in 1% of the Firefox downloads in Germany starting next week.

Discussion in HackerNews: https://news.ycombinator.com/item?id=15421708
Announcement from Mozilla: https://blog.mozilla.org/press-uk/2017/10/06/testing-cliqz-in-firefox/
Quote from the announcement:
> Next week, we will be launching our most significant test so far. Less than one percent of users in Germany installing Firefox from our main download page will receive a version of Firefox with Cliqz recommendations enabled out of the box.
> This experiment also includes the data collection tool Cliqz uses to build its recommendation engine. Users who receive a version of Firefox with Cliqz will have their browsing activity sent to Cliqz servers, including the URLs of pages they visit. Cliqz uses several techniques to attempt to remove sensitive information from this browsing data before it is sent from Firefox.

### Screenshot(s)

Not applicable.

### Versions

- Browser/version: Firefox 56
- uBlock Origin version: -

### Settings

- No changes.

### Notes

The source code of the Cliqz Firefox extension can be obtained as follows:
```
mkdir cliqz; cd cliqz
wget 'https://addons.mozilla.org/firefox/downloads/latest/cliqz/addon-521900-latest.xpi'
unzip addon-521900-latest.xpi
```

**Comment by gwarser** [comment]
This may not work - https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#differences-with-ubolegacy

>uBO/webext has limited access to behind-the-scene network requests, unlike uBO/legacy which had full access to all behind-the-scene network requests. For example, you won't be able to see (and block) network requests made by other extensions. Related: "Support moz-extension: urls in MatchPattern".

**Comment by AlbertoGP** [comment]
Thank you very much for this information. I wasn't aware of it.

**Comment by gorhill** [comment]
uBO/webext does not have access to other extensions' network requests, so there is nothing it can do.

**Comment by shevegen** [comment]
My comment is not related to the issue per se, but I have been wondering about mozilla quite a lot lately. But anyway, this is also not the thing I wanted to write - due to the deprecation of ALSA by Mozilla, I can no longer upgrade to the "latest and greatest" firefox, since then I would have no audio anymore. However had, the popup "upgrade to the latest firefox" keeps on coming about. My idea was to just let ublock block that popup, which would be kind of fun - to no longer depend on Mozilla and instead re-define the WHOLE "browser experience" on my own ...  ;-)

Anyway, this is out of the scope of ublock origin but I just wanted to mention it, in particular as to when blocking content starts and where it ends. I heavily dislike mozilla trying to push cliqz, pocket and what not onto the people though.

Perhaps one day we would have a model such as ublock origin for the whole browser. That way mozilla could not push certain things onto the users at will.

**Comment by SMed79** [comment]
> `https://hpn-collector.cliqz.com` <- Data collection endpoints are under this host name.

@yous @mitchellkrogza fyi.

**Comment by mitchellkrogza** [comment]
Thanks @SMed79 added to Ultimate Hosts 👍
