### ISSUE TITLE
Accuweather animated radar not working

### ISSUE THREAD

**Issue by wildcard418** [uBlockOrigin/uAssets#7539]
### URL(s) where the issue occurs
Any animated radar page:
```
https://www.accuweather.com/en/us/colorado/weather-radar
https://www.accuweather.com/en/us/texas/weather-radar
https://www.accuweather.com/en/us/california/weather-radar
```

### Describe the issue
The animated radar doesn't load the radar images over the map. The map appears, but there is no radar images on top of it.
The play button works, but it still shows no animation at all.

Disabling uBlock origin, of course, fixes the issue. I've dug down and found the issue is originating from the EasyPrivacy filter list. If I disable that filter, the issue is resolved.

This problem occurs in latest Firefox and Chrome.

 

### Screenshot(s)

![accuweather](https://user-images.githubusercontent.com/46544275/84171614-40c89880-aa38-11ea-9278-224b88da3778.png)

Screenshot attached.

### Versions

- Browser/version: Firefox 77.0.1 & Chrome 83.0.4103.97
- uBlock Origin version: uBlock Origin v1.27.10

### Settings

- No changes from default, other than some whitelisted pages.

Disabling the EasyPrivacy filter list fixes the issue.

**Comment by mapx-** [comment]
needing 
`@@||connatix.com/*/connatix.renderer.infeed.min.js$script,domain=accuweather.com`

**Comment by PIZZA90** [comment]
`https://www.accuweather.com/`

cant "Go-Back"

**Comment by mapx-** [comment]
I cannot reproduce such an issue

**Comment by PIZZA90** [comment]
i dont like do videos, but see this:

**0:14**  spaming the go-back button of Chrome browser (no working)
**0:26**  turning **OFF** "_uBlock filters - Privacy_" and look works well
**0:55**  turning **ON** "_uBlock filters - Privacy_" a default filter list.. the problem back

https://user-images.githubusercontent.com/33556647/149343902-c4410724-a3d8-47f0-8dfc-a7882c2bf952.mp4

1. Full default settings
2. No problem with Firefox
3. No problem whit my laptop even with Chrome
4. I can reproduce only in this compunter with uBO ON

- maybe it's some nonsense, but WHY works with **uBO** or "_uBlock filters - Privacy_" OFF... is a mistery not resolved 🤣
 Maybe this issue is a stupid thing, but is very strange.

**Comment by gorhill** [comment]
Remember: <https://github.com/uBlockOrigin/uAssets/issues/11224#issuecomment-1007729397>.

**Comment by gorhill** [comment]
> not using Adguard lists gorhill this timegrin

Maybe not, but my point is that you had _customized_ uBO and yet reported using default settings. This now cast doubt on your reports, and I wanted to remind you to _truthfully_ test with default settings/lists.
