### ISSUE TITLE
jp.zaful.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7664]
Forgive me to skip the necessary steps as it's 100% identical to https://github.com/easylist/easylist/issues/5554 (the link in the issue works).
It was fixed on EL side but it turned out Peter Lowe's also blocks `logsss.com` so the issue is not resolved on uBO. While
`@@||geshopcss.logsss.com^$script,image,xhr,domain=zaful.com`
works, I wonder if @pgl can change the entry to `analytics.logsss.com` so that those non-uBO user can also be saved.

**Comment by pgl** [comment]
@Yuki2718 I'm afraid I only list the highest level part of a domain that I can.

**Comment by Yuki2718** [comment]
@pgl Yeah I'm aware of that policy. I thought there may be an exception if it causes false positives as you've been working hard to minimize it and actually found such cases e.g. `afl.rakuten.co.jp` is not blocked entirely but instead its subdomains are covered by your list, isn't it because the former caused an issue?

**Comment by krystian3w** [comment]
In the past asked for add `||apple.com-*.live^$all` / `||apple.com-*.xyz^$all` insead of ban instead of banning single names.
It seems the list has conversions to a wildcard compatible file (for ABP).

But it didn't work out, and that wildcard went to the uBO: https://github.com/uBlockOrigin/uAssets/blob/e37d0778f73c6b73b14e42cc2ee51bab968b7623/filters/badware.txt#L395
