### ISSUE TITLE
postimg.org

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#775]
**URL where the issue occurs**

`https://postimg.org/image/3dv9z4fz0b/`

**Describe the issue

`piguiqproxy.com` ads at `postimg.org`

**Screenshot**

http://i.imgur.com/YUVdNvp.png

**Versions**

Chromium 61.0.3163.100
uBo 1.14.12

**Settings**

uBO's default settings

**Filter**
```
postimg.org##script:inject(abort-current-inline-script.js, MutationObserver, 676574456c656d656e747342795461674e616d65)
```

**Comment by uBlock-user** [comment]
Filter doesn't get applied due to race conditions. You should rather neutralize `performance` instead.

**Comment by mapx-** [comment]
working for me

alternative filter:
`||piguiqproxy.com/api$xmlhttprequest,redirect=nooptext,domain=postimg.org`

**Comment by uBlock-user** [comment]
Yes that also works or neutralise the `performance`

**Comment by okiehsch** [comment]
The does get applied to the first [piguiqproxy.com/](https://n7-r98d2.piguiqproxy.com/feb4NDgADVAOA1sAWQUNUFpWAQQNUAgFWQENBQxVAVIBBlkADgJEbUMWVVFMXFdQGg4aU1-1AZ1VKU1daGhgaUFlAWRYCTxpXV1lVXUwWAhYOAAwGDQMLDA0FDQ0IAg1RCwwIUQwEDAQPUg8FAFEJAgwFAFcJA15QGhgaRhoOD0lFDAlWCQULBQgHWQQIVQ0EWwFaVw5WDwIAA1sMXFcIUA0EDAENAAABDwwIA1oEAFYLDA8HCQMNBQ0BDAFdAABRWgAJUQkMC1YIBVkFCAcNBFtVWgQOAQ9XAFZbAlwDCAwNVwxQDQQAAQ8ACAFaDAAD-CwQPVgkMDQcNAwwFXQEAAVoACVEJAAtRCAxZVggFDQVbB1oEDlUPBAABW1c)-xhr request - which is partly a copy of the `inline-script` the filter does not apply because of a race condition - and this fixes the issue at hand.

**Comment by uBlock-user** [comment]
Well in Chromium 63, it fails to apply even once and this happens - 

![](https://i.gyazo.com/5c9e78dd7f5ee35ec80d2a33906fedb7.png)

**Comment by uBlock-user** [comment]
Also if you just want to block ads why not add `||piguiqproxy.com^$third-party` ?

**Comment by mapx-** [comment]
`||piguiqproxy.com^$third-party` => you'll get exactly the page you posted above.

**Comment by okiehsch** [comment]
[This](https://camo.githubusercontent.com/01608236b08361df308ff703cd44818f5630c652/68747470733a2f2f692e6779617a6f2e636f6d2f35633965373864643766356565333565633830643261333339303666656462372e706e67)
also happens with Chrome and Firefox but it only happens if you block xhr-requests to `piguiqproxy.com` which is also the reason why adding `||piguiqproxy.com^$third-party` makes no sense.

**Comment by mapx-** [comment]
I tested chrome 63 (dev), still working fine (ublock filters filter or my redirect filter above)

**Comment by uBlock-user** [comment]
It does makes sense, it's an ad-server, the source of your issue. By blocking it, you kill ads.

Ofcourse th inline-script is designed to destroy the page incase the ad-server is blocked and that is what happens in the picture from your comment https://github.com/uBlockOrigin/uAssets/issues/775#issuecomment-338729650

**Comment by uBlock-user** [comment]
Also for page breakage, I already posted the filter in https://github.com/uBlockOrigin/uAssets/issues/775#issuecomment-338725329 

Add that and the page breakage issue goes away.

**Comment by okiehsch** [comment]
I meant that it does not make sense in this case because it breaks the page.
````
postimg.org##script:inject(abort-current-inline-script.js, MutationObserver, 676574456c656d656e747342795461674e616d65)
`````
fixes the issue while not breaking the site if you use uBO with a default setup and I highly doubt any default filter list will add `||piguiqproxy.com^$third-party` because it would break hundreds of high traffic sites.
`https://publicwww.com/websites/%22%22676574456c656d656e747342795461674e616d65%22%22/`

**Comment by uBlock-user** [comment]
> and I highly doubt any default filter list will add ||piguiqproxy.com^$third-party because it would break hundreds of high traffic sites.

Oh, so you're keeping the solution rather generic to avoid breakage for other blockers ? Okay, I understand that. Mine was ofcourse uBO specific solution only.

**Comment by okiehsch** [comment]
Just fyi `postimg.com##script:inject(abort-on-property-read.js, performance)` does not work on my end whith Chrome , it does work with Firefox.

**Comment by uBlock-user** [comment]
@okiehsch It's for patching the page once it breaks not for blocking ads. You need to block the domain first

**Comment by okiehsch** [comment]
That is what I meant, if I add 
````
postimg.com##script:inject(abort-on-property-write.js, performance)
||piguiqproxy.com^$third-party
````
the page is broken using Chrome, with Firefox there is no `piguiqproxy.com-request`, so the page renders fine.

**Comment by uBlock-user** [comment]
Try

```
||piguiqproxy.com^$third-party
postimg.com##script:inject(abort-on-property-read.js, performance)
```

**Comment by okiehsch** [comment]
````
||piguiqproxy.com^$third-party
postimg.com##script:inject(abort-on-property-read.js, performance)
```` 
breaks the page using Chrome on my end.

**Comment by mapx-** [comment]
breaks the page for me too

**Comment by uBlock-user** [comment]
It's `postimg.org` not `postimg.com`, my bad! Please test again.

**Comment by okiehsch** [comment]
That works.

**Comment by uBlock-user** [comment]
Yeah I've a bad habit of misplacing `.org` with `.com`, sorry 'bout that.

**Comment by okiehsch** [comment]
No problem.
I think a possible generic fix for all `piguiqproxy-sites` could be 
`||piguiqproxy.com/api$xmlhttprequest,redirect=nooptext` but I would have to look into that later.

**Comment by uBlock-user** [comment]
Yes that will do too, either one of them is fine. I have been using `##script:inject(abort-on-property-read.js, performance)` for `kimcartoon.me`, `torrentz2.eu` and others and they're working fine so far.

**Comment by okiehsch** [comment]
The advantage of using `redirect` instead of `inject` is that we would not have to specify a domain.

**Comment by uBlock-user** [comment]
Yes that, and the only disadvantage would if they decide to swap domain names.

**Comment by mapx-** [comment]
blank page 
example `https://postimg.org/image/1jrqvw7hmj/`

`postimg.org#@#.td-ad`

**Comment by okiehsch** [comment]
The picture at `https://postimg.org/image/1jrqvw7hmj/` is blocked, because it is called "ads", which results in `https://s1.postimg.org/28l0fwv0n3/ads.png` being blocked by `/ads.png` in EasyList".
I could add an exception filter, but that would only affect this exact case, i.e. all uploaded pictures called "ads".
