### ISSUE TITLE
Floating "Close" button on livemint.com

### ISSUE THREAD

**Issue by Bluedot449** [uBlockOrigin/uAssets#7762]
`https://www.livemint.com/science/health/who-will-get-covid-19-vaccine-in-india-first-committee-meets-today-11597234515887.html`

## Steps to reproduce

1. Go to the above website
2. Scroll down a bit
3. See the floating "Close" button appear 

I'm not sure if the floating banner just beside the "Close" could also be blocked. 

**Changed settings in uBO:** None. 

**Lists Enabled bedside default ones**: Adguard Base, Adguard Mobile Ads, uBO Annoyances, Fanboy's Annoyances. 

**Environment:**

Browser: Firefox on Android (Fenix): 79.0.3.
uBO: 1.29.0

Floating "close" button:

![Screenshot_20200813_124148](https://user-images.githubusercontent.com/69183387/90104777-5ad27000-dd34-11ea-8eb8-8486c10c852e.jpg)

**Comment by mapx-** [comment]
add
```
livemint.com##.eclt-rsttble
livemint.com##.btnClose
```

@ryanbr

**Comment by Bluedot449** [comment]
Is it not the correct place to report these type of issues?

Can you please point me to the place I should report these;

• Pop-up tabs when clicked anywhere on the webpage
• Cookie dialogues
• Unbkocked Ads
• Anti-adblocks
• annoying contents covering part of the pages (like black boxes)
• websites pop-up to new tabs to download a malicious apps and programs.

-------- Original Message --------

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/README.md

"If an issue can be fixed without using extended syntax, i.e. [scriptlet injection](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection), [redirect](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect), [procedural cosmetic filters](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#procedural-cosmetic-filters), etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

- anti-adblock
- ad-reinsertion
- popups/popunders
- site breakage
- video ads

will always be fixed in uAssets even if they don't require extended syntax.


If the ABP-compatible fixes are for high-traffic sites, they should be added to uBO filters until they are added to EasyList."

**Comment by Bluedot449** [comment]
I definitely read the `Readme` but I didn't understand much. That's why the question so I don't waste anybody's time here by reporting it here when I shouldn't have. 

Apart from the anti-adblock I didn't understand much. 

From the commit it seems I should have reported this in the `Easylist`.

I'll only report Anti-adblocks here then.

Thanks for the response.

**Comment by mapx-** [comment]
You should report here:
```
anti-adblock
ad-reinsertion 
popups/popunders
site breakage
video ads
```
