### ISSUE TITLE
I want to contribute coin-miner filter list to uBlock please

### ISSUE THREAD

**Issue by PeterDaveHello** [uBlockOrigin/uAssets#785]
Hi there,

I've noticed that pull request is not welcome as the main project [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) mentions, just want to make sure if it possible or how to contribute to the filter list, as I see this uAssets repo but I didn't see the filter list in this repo.

I've make some changes in my own forked uBlock repo:

Commits:
 - https://github.com/PeterDaveHello/uBlock/commit/c8c133a85b7f15a82187fb1f88f643fd84312b96
https://github.com/PeterDaveHello/uBlock/commit/4737a3db3e92138a3f78bb8405bbfcdb1180f0f6

Branch:
 - https://github.com/PeterDaveHello/uBlock/tree/block-coin-miner

Which would add "NoCoin adblock list"(https://github.com/hoshsadiq/adblock-nocoin-list) in the filter list, would you please let me know how can I do it or I just can't?

Many thanks!

**Comment by okiehsch** [comment]
If you think uBlock should add a filter list you can open an issue at https://github.com/gorhill/uBlock.
It has been done before. https://github.com/gorhill/uBlock/issues/3089.

I see no reason to add https://github.com/hoshsadiq/adblock-nocoin-list, because at a quick glance all entries except `||api.inwemo.com^$third-party` are already included in https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt, which is enabled by default in uBO.
`inwemo.com` has a mandatory opt-in as far as I can see, so unless someone can provide an example of it
starting mining without user interaction I don't think it should be added to `resource-abuse.txt`, as I already stated in another [case](https://github.com/uBlockOrigin/uAssets/issues/770#issuecomment-337754701).

**Comment by PeterDaveHello** [comment]
@okiehsch thanks for your prompt reply, I'll take a look at the resource you gave me 😄
