### ISSUE TITLE
Citytv.com telling me to disable adblock when I press live

### ISSUE THREAD

**Issue by w4tadrag** [uBlockOrigin/uAssets#7962]
### 
![image](https://user-images.githubusercontent.com/32439406/94380008-bb114b80-0101-11eb-9526-9f25b4015fa6.png)

### Versions

- Browser/version:  Chrome 85.0.4183.121
- uBlock Origin version: 1.29.2

### Settings
default setting

**Comment by okiehsch** [comment]
I can't get the video to play even using a canadian IP.
Does 
`||utility.rogersmedia.com/utility.js$script,redirect=noop.js,domain=citytv.com`
work for you.

**Comment by llacb47** [comment]
Test `||rogersmedia.com/utility$script,redirect=noopjs,important`

**Comment by okiehsch** [comment]
Can you play the video?

**Comment by llacb47** [comment]
Yes, with your filter. For completeness' sake I would prefer to redirect all of the rogersmedia utility antiadblock scripts though. Especially since the script sends an unnecessary payload to `utilityx.herokuapp.com`.

![image](https://user-images.githubusercontent.com/16567977/94384733-48a86780-0111-11eb-9c7d-06c9ec092f72.png)

**Comment by okiehsch** [comment]
OK. I don't think the "important" is necessary though.
