### ISSUE TITLE
peliculasgoogleone.net [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#7964]
URL(s) where the issue occurs

`https://peliculasgoogleone.net/los-ultimos-dias-desierto-2015-1080p-brrip-latino-ingles-googledrive-lachapelhd/`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 85 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.29.2

Settings

Default

**Comment by KiLL4FuNK** [comment]
enter the link

**Comment by KiLL4FuNK** [comment]
to download

**Comment by garry-ut99** [comment]
(no AA for me with `ghide` off) Ad placeholders caused by `ghide` from: "uBlock Filters" + "spa, por: AdGuard Spanish/Portuguese": [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218099280-6da99b21-aaa5-4121-a931-06cba9850167.png) `https://mexicogob.com/cuando-depositan-mi-beca-para-empezar-en-enero-2023-y-cuanto-pagaran/` I'm not sure whether I Should report it separately on AG tracker or Yuki will take care.

**Comment by mapx-** [comment]
@Yuki2718

**Comment by garry-ut99** [comment]
`https://todoandroid.live/como-hacer-un-hard-reset-a-cualquier-movil/`
Ad placeholders `.adsbygoogle` all over the site, caused by `ghide` from "uBlock Filters", on both main page and subpages [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219370409-8ccee008-0a9c-4f9e-bb55-54393bb0d447.png) ,  no AA for me with `ghide` off.
