### ISSUE TITLE
mrbigandtall.ca

### ISSUE THREAD

**Issue by Toshiba1127** [uBlockOrigin/uAssets#8051]
### URL(s) where the issue occurs

`https://www.mrbigandtall.ca/`

### Describe the issue

Annoyance. Asks you to subscribe

### Screenshot(s)

![image](https://user-images.githubusercontent.com/64008639/96449723-90547780-1215-11eb-81e3-1aecc7bdd053.png)

### Versions

- Browser/version: Chrome 86.0
- uBlock Origin version: 1.30.4

### Settings

- Have uBlock filters – Annoyances enabled

**Comment by uBlock-user** [comment]
Add `mrbigandtall.ca###joinTheClubPopupContainer` to my Filters or report this to Fanboy/AdGuard Annoyances tracker.

**Comment by Toshiba1127** [comment]
Thanks
I thought this could be added to uBlock filters – Annoyances, but ok i will try to report to AdGuard Annoyances. I'm avoiding Fanboy at all since they are not responding and their filters are totally unstable and broken

**Comment by krystian3w** [comment]
Currently, AdGuard Annoyance allows  to use: 

https://github.com/gorhill/uBlock/wiki/Resources-Library
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#subjectstylearg

So this is where the argument that the website does not scroll (because they blocked it with a CSS or some `JS` kind of `EventListener`) disappears/It loses its power.
