### ISSUE TITLE
uBlock Filters prevents links to some torrent and adult sites from opening in new tab

### ISSUE THREAD

**Issue by LurkerHub** [uBlockOrigin/uAssets#8123]
Note: some of the links are for NSFW sites.

### URL(s) where the issue occurs

Put the following into a file:

```
<a href="https://pt.xhamster.com/photos/gallery/sfw-3dcg-gallery-7075906">xhamster</a><br>
<a href="https://rarbg.to/torrents.php?search=tt0082398">rarbg</a><br>
<a href="https://thepiratebay.org/search/For%20Your%20Eyes%20Only%201981/0/99/200">the pirate bay</a><br>
<a href="https://www.torlock.com/all/torrents/For%20Your%20Eyes%20Only.html">torlock</a><br>
<a href="https://www.torrentdownloads.me/search/?search=For%20Your%20Eyes%20Only+1981">torrent downloads</a><br>
```

Load the file in Firefox.
Right-click on the links and try to open them in a new tab.

### Describe the issue

Please see above.

When trying to open in a new tab, the tab opens and immediately closes.
(opening in the same tab or in a new window works)

If I uncheck the "uBlock filters" in the filter list, the problem disappears.

### Versions

- Browser/version: Firefox developer edition 83.0b5 (64-bit)
- uBlock Origin version: v1.30.6

### Settings

Advanced mode enabled.

### Notes

The same behaviour occurs when trying to open similar links from web pages, search engines, etc. in a new tab.
Using a local file is just for convenience.

**Comment by uBlock-user** [comment]
Works fine, test on default settings.

**Comment by LurkerHub** [comment]
Does not work for me on default settings.

Steps performed:
1. Disabled all addons except uBO.
2. Reset uBO to default settings.
3. Restarted browser.

Problem still happens.

When middle-clicking on a link, the network monitor shows:

![image](https://user-images.githubusercontent.com/20542915/98418944-01878d80-2052-11eb-886d-febf68160415.png)

![image](https://user-images.githubusercontent.com/20542915/98418958-09473200-2052-11eb-86c1-1441b4e5604f.png)

Unchecking "uBlock filters" in Filter Lists makes the problem go away.

For some reason the middle click (open in new tab) is interpreted by the filter as a popup?

**Comment by LurkerHub** [comment]
I think I found the issue.

The problem happens when `browser.tabs.loadInBackground` is set to `false`.

Go to `about:preferences#general`
Under "Tabs" check "When you open a link in a new tab, switch to it immediately"

Description edited.

This is a bug.  Please re-open.

**Comment by uBlock-user** [comment]
Filter list issue, caused by Easylist filter -- `/^https?:\/\/.*[&%+=]/$popup,domain=mixdrop.co|powvideo.net|powvldeo.cc|prox4you.xyz|putlocker.fyi|putlocker.ninja|putlocker.style|putlockers.fm|putlockers.mn|putlockers.movie|rarbg.to|rarbgaccess.org|rarbgmirror.com|rarbgmirror.org|rarbgmirrored.org|rarbgproxy.org|rarbgprx.org|rarbgunblock.org|rarbgway.org|readcomiconline.to|repelis.net|seehd.pl|sendit.cloud|sendspace.com|sendvid.com|sportp2p.com|steamplay.cc|streamplay.life|streamplay.to|thepiratebay.org|thepiratebay10.org|torlock.com|torrentdownloads.me|torrentfunk2.com|uiz.io|ukpirate.org|unblockall.org|unblocker.cc|up-load.io|upload.ac|uploadproper.com|uploadproper.net|upstream.to|uptobox.com|userscloud.com|vev.io|vidbull.tv|videobin.co|vidlox.me|vidoza.co|vidoza.net|vidtomp3.com|vidup.io|vipbox.live|vipstand.se|vshare.eu|y2mate.com|yify-movies.net|youwatch.org|youzik.com|zippyshare.com`

@ryanbr

**Comment by alexolog** [comment]
I am seeing the same issue.

Can this be reopened and fixed?

**Comment by ghajini** [comment]
similar problem i was explaining repeatedly but no one cared that time https://github.com/uBlockOrigin/uAssets/issues/5374#issuecomment-567769421

**Comment by mapx-** [comment]
> The problem only happens when browser.tabs.loadInBackground is set to false.

**Comment by alexolog** [comment]
Fix works.  Thank you!

**Comment by alexolog** [comment]
The problem is happening again.
