### ISSUE TITLE
myntra.com breakage

### ISSUE THREAD

**Issue by sanGtH** [uBlockOrigin/uAssets#8240]
### Description
The overall functionality of the website is hampered. But when UblockOrigin is OFF for this site,
the webiste functions normally. Observed on FF and Chrome.

### A specific URL where the issue occurs

`https://www.myntra.com/men-clothing?src=bc`

### Steps to Reproduce
1. Goto the above link
2. On the left panel, you'll find filter checkboxes. I am unable to check any checkbox.
3. On the bottom of page, when you click on the **Next**, the next page won't load.
4. When you add an item to the cart, it won't get added. 

### Expected behavior:
The website should work the way it works when UblockOrigin is OFF.

### Actual behavior:
The normal functions (filtering the items or adding to cart etc) of the webstie are getting hampered when UblockOrigin is **ON**.

### Your environment
* uBlock Origin version:  **v1.30.6**
* Browser Name and version: FF 79.xx Chrome 86.xx
* Operating System and version: Windows 7 64 bit

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by sks4903440** [comment]
@stephenhawk8054 The changes in commit [bde1b38](https://github.com/uBlockOrigin/uAssets/commit/bde1b38d42dc74443489c2c784c9f9536113db59) is breaking the myntra website on firefox. Can we revert this ?

### Description
Multiple functionality of the website is hampered. But when UblockOrigin is OFF for this site,
the website functions normally. Observed on FF and Chrome.

### A specific URL where the issue occurs
https://www.myntra.com/tshirts/hm/hm-men-white-3-pack-t-shirts-slim-fit/12696160/buy

### Steps to Reproduce
      Visit the url and try adding the product to your wishlist

### Expected behavior:
You should be able to add the product to your wishlist
You should be able to view your details in profile section

### Actual behavior:
Adding the product to your wishlist won't work
In the profile dropdown on top right, you won't find your details even when logged in

### Your environment
    uBlock Origin version: v1.47.4
    Browser Name and version: FF 111.0
    Operating System and version: MacOS 13.2.1

**Comment by PacificCosmophile** [comment]
Terrms & Privacy policy checkbox not appearing on login page when uBlock is on ⬇️

https://github.com/user-attachments/assets/ea8f5253-78bb-4125-9b21-8e204ce393fd

When uBlock is off ⬇️

https://github.com/user-attachments/assets/5de2166c-6079-4810-bf20-b9887bf417df

**Comment by mapx-** [comment]
add

```adb
myntra.com#@#.consentContainer
```

@ryanbr
