### ISSUE TITLE
[Anti Adblock] Bild.de

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#8257]
### URL(s) where the issue occurs

`https://www.bild.de/regional/thueringen/thueringen-aktuell/neustadt-an-der-orla-30-vermummte-attackieren-menschen-in-thueringen-74073656.bild.html`

### Describe the issue

After a few seconds you get redirected to: `https://www.bild.de/adblockwall.html` telling you to disable the adblocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/14368203/99903371-376c7900-2cc4-11eb-82da-60b54f4d7506.png)

### Versions

- Browser/version: Edge 86.0.622.69
- uBlock Origin version: 1.30.6

### Settings

- Enabled all ublock and easylist Germany

**Comment by uBlock-user** [comment]
gorhill added the fix recently, force update uBlock Filters.

**Comment by Symbai** [comment]
That fixed it

**Comment by Symbai** [comment]
Going have to reopen the issue. It turns out they were pretty fast on bypassing the fix. But now it takes like 20 seconds just staying at their homepage until you get a different anti adblock redirection.

1. Visit: `https://www.bild.de/`
2. Wait up to 30 seconds, tab can be in background while you wait
3. You get redirected to `https://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html`

![image](https://user-images.githubusercontent.com/14368203/99909327-22a1dc80-2ce8-11eb-8aa7-cb3afbb249fb.png)

**Comment by uBlock-user** [comment]
No change, test on default settings + all other extensions disabled.

**Comment by lain566** [comment]
I can reproduce anti-adblock on the home page with Edge.

The website no longer redirects me to an anti-adblock page when I add this filter

`bild.de##+js(aopr, SmartAdServerASMI)`

@Symbai Does this work for you?

**Comment by Symbai** [comment]
@lain566 Yes this works!

**Comment by JobcenterTycoon** [comment]
The fix doesn’t work when i have the private mode enabled (tested in Firefox). Its posible to fix that?

**Comment by lain566** [comment]
It works for me in incognito mode with Tracking Protection enabled.

**Comment by JobcenterTycoon** [comment]
ok i see i can only reproduce when i open the direct link.

**Comment by Mennaruuk** [comment]
Alas, the issue is back:
`https://www.bild.de/unterhaltung/leute/leute/elon-musk-treibt-dogecoin-kurs-nach-oben-75178958.bild.html`
`https://www.bild.de/sport/fussball/fussball-international/mussolini-urenkel-romano-floriani-mussolini-bei-lazio-rom-75209112.bild.html`
`https://www.bild.de/video/clip/sport-videos/suele-geht-zu-chelsea-wenn-75209034-75213964.bild.html`
![image](https://user-images.githubusercontent.com/52135169/106952811-98222400-66ff-11eb-81ef-848b9c54bd0a.png)

Seemingly, the anti content blocker isn't always consistent. For example, these are sites where I didn't encounter this anti content blocker, but YMMV:
`https://www.bild.de/unterhaltung/leute/leute/elon-musk-treibt-dogecoin-kurs-nach-oben-75178958.bild.html`
`https://www.bild.de/sport/fussball/fussball-international/mussolini-urenkel-romano-floriani-mussolini-bei-lazio-rom-75209112.bild.html`
`https://www.bild.de/video/clip/sport-videos/suele-geht-zu-chelsea-wenn-75209034-75213964.bild.html`

**Comment by lain566** [comment]
I'm unable to reproduce the anti-adblock
@okiehsch Can you reproduce the anti-adblock?

**Comment by okiehsch** [comment]
No, I tried a few minutes ago.

**Comment by Mennaruuk** [comment]
Is there a particular filter list I need to have checked?

**Comment by okiehsch** [comment]
I can't reproduce with a default setup + EasyList Germany.

![image](https://user-images.githubusercontent.com/16838044/106969489-31c2f300-674b-11eb-9d1b-a5bf8ffcc316.png)

**Comment by Mennaruuk** [comment]
That’s it! EasyList Germany solved it for me, thank you!
