### ISSUE TITLE
dvdgayonline.com - Anti-adblock

### ISSUE THREAD

**Issue by Innerbeard** [uBlockOrigin/uAssets#8309]
### URL(s) where the issue occurs

https://dvdgayonline.com/

### Describe the issue

Anti-adblocker blocks access to the webpage. I can use the element picker to remove the banner and the red overlay but the blur filter persists.

### Screenshot(s)

https://i.redd.it/9lc4pyreit261.png

### Versions

- Browser/version: Version 87.0.4280.66 (Official Build) (64-bit)
- uBlock Origin version: v1.31.0

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0b9563e01c1af4d4c774a390f1fa180641942d82

force update uBlock Filters in a while.

**Comment by Innerbeard** [comment]
Already did that. They are up to date. The problem persists.

**Comment by uBlock-user** [comment]
I literally added the filter only 2 minutes ago, so you didn't get the updated version of the filterlist. Wait 10 minutes or more and force update again.

**Comment by Innerbeard** [comment]
My bad. I closed and reopened chrome and it worked. Thank you.

**Comment by uBlock-user** [comment]
So that was a cache issue. 

Just a side note, Github will serve you old cache if the resource in question is being accessed by multiple people sequentially, so be patient and wait a good long while before forcing updates again after you have already forced an update and didn't receive the update version.
