### ISSUE TITLE
https://bilanx.dcard.tw/v1/events

### ISSUE THREAD

**Issue by c2xusnpq6** [uBlockOrigin/uAssets#8382]
```
https://www.dcard.tw/f/cycu/p/234999716 --> https://bilanx.dcard.tw/v1/events
```
![圖片](https://user-images.githubusercontent.com/75058881/102559285-7696ba00-410a-11eb-9cd2-2724354cf419.png)
![圖片](https://user-images.githubusercontent.com/75058881/102559312-8910f380-410a-11eb-89fe-d51a95c9908f.png)
![圖片](https://user-images.githubusercontent.com/75058881/102559361-a219a480-410a-11eb-94ad-6f0288e91484.png)

**Comment by c2xusnpq6** [comment]
![圖片](https://user-images.githubusercontent.com/75058881/102559625-40a60580-410b-11eb-8c89-f5ec4e53533e.png)

**Comment by uBlock-user** [comment]
Why do remove the template like before ? That template exists for a reason, fill it out.

**Comment by mapx-** [comment]
You should explain what's your issue.
Needing an account ?

That json on my side even disabling uBO:

![image](https://user-images.githubusercontent.com/10303732/102585713-2d923600-4109-11eb-8878-396dda49581d.png)

**Comment by c2xusnpq6** [comment]
@mapx- @uBlock-user No account required
![圖片](https://user-images.githubusercontent.com/75058881/102597256-56401d00-4155-11eb-8782-87b365a5c4dd.png)

**Comment by c2xusnpq6** [comment]
No account required @mapx- @uBlock-user 
![圖片](https://user-images.githubusercontent.com/75058881/102597918-41b05480-4156-11eb-911d-307e27f9f3b7.png)

**Comment by uBlock-user** [comment]
I can see that, what exactly are you reporting ?

**Comment by Yuki2718** [comment]
Please note, we don't block a request just because it sends user info. You have to prove blocking the request doesn't affect sites' operation as far as you can. I've read arguments in Futa filter and if I understand correctly you didn't in the previous issue.
@tasi788 @bestpika If you're okay I want to hear your opinion on this.

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/issues/6725

**Comment by bestpika** [comment]
> Please note, we don't block a request just because it sends user info. You have to prove blocking the request doesn't affect sites' operation as far as you can. I've read arguments in Futa filter and if I understand correctly you didn't in the previous issue. And DO NOT delete template, if you repeat this we have to mark you as a spammer.
> @tasi788 @bestpika If you're okay I want to hear your opinion on this.

In the previous issue about "shopback", since this site provides cashback by tracking users' purchases from this site to other sites, blocking that tracking would cause the feature to be abnormal, making it impossible for users to get the cashback.

However, in this issue of "dcard", since I have not tested this site (no account for this site), I cannot determine if blocking the request will cause the site to be abnormal.
And @c2xusnpq6 did not the first test whether the blocking would cause the site to be abnormal before opening the issue.

**Comment by tasi788** [comment]
as I know `bilanx.dcard.tw` is a `data tracking`, however I don't know if block that will cause any functional problem of the site.

**Comment by Yuki2718** [comment]
@tasi788 Thx, I confirmed that sends user info, and usually this kind of analytics is not terribly false-positive prone. But as the site is Taiwanese popular SNS which should have many function only available after login, I wanted to hear from those who have more insight on this than us.

**Comment by tasi788** [comment]
> @tasi788 Thx, I confirmed that sends user info, and usually this kind of analytics is not terribly false-positive prone. But as the site is Taiwanese popular SNS which should have many function only available after login, I wanted to hear from those who have more insight on this than us.

actually I have account, if there have any news I'll that you know.

**Comment by Yuki2718** [comment]
Sorry, I mistakenly edited your comment.

Very appreciated :D

**Comment by tasi788** [comment]
After a short test, `|| bilanx.dcard.tw/v1/events` work fine for me with logged account.
