### ISSUE TITLE
Is it necessary to block wasm for entire .space tld? Breaks my site

### ISSUE THREAD

**Issue by wmurphyrd** [uBlockOrigin/uAssets#8389]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://hub.vreign.space/WwVhpm9/bossy-artistic-barbecue`

### Describe the issue

I've deployed Mozilla's Hubs Immersive Web meetings platform to a .space domain. The platform uses `wasm` for optimized physics simulations in the virtual space among other things. uBlock is filtering requests scripts and breaking functionality of the site.

The filter is located here: 
https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt#L36

### Versions

- Browser/version: FF 84.0 (64-bit) for Ubuntu
- uBlock Origin version: 1.31.0

### Settings

- all default

**Comment by uBlock-user** [comment]
Not seeing any `.wasm` resource getting blocked, how to reproduce ?

**Comment by uBlock-user** [comment]
Was added to block coin-miners on the site.

**Comment by wmurphyrd** [comment]
@uBlock-user 
Here's the log showing the block at the above URL


```
+1
.space^*.wasm$3p
--
hub.vreign.space
3
xhr
https://hub-vreign-assets.vreign-internal.space/hubs/assets/wasm/ammo.wasm-8640fe8d5bf91d2e84ea56e0c1307ba9.wasm
```
>Was added to block coin-miners on the site.

Which site? this is blocking an entire TLD

**Comment by uBlock-user** [comment]
All sites, few years ago. Filter removed.

**Comment by wmurphyrd** [comment]
Thank you so much! :pray:

**Comment by JobcenterTycoon** [comment]
I found more outdated filters

`.info^$script,3p,domain=oload.info|oload.tv|openload.co|streamango.com|streamcherry.com` can be removed because every domain got taken down

`||darking01.tk^$3p`
`||darking02.tk^$3p`
`||darking03.tk^$3p`
`||darking04.tk^$3p`
`||darking06.tk^$3p`
`||darking08.tk^$3p`
`||darking09.tk^$3p`
`||megabanners.cf^$websocket` 
`||edgeno.de^$script,3p,domain=~edgemesh.com` dead domains

`||rapidvideo.com/J5xj_2.js` got taken down

`||reactor.cc^$csp=worker-src 'none'`
`||reactor.cc^*.wasm`
`||theappguruz.com/vendor/composer/installed.js$script` EasyPrivacy already cover this
