### ISSUE TITLE
Unblocked content on typeracer.

### ISSUE THREAD

**Issue by nathanielcwm** [uBlockOrigin/uAssets#8475]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://play.typeracer.com/

### Describe the issue
While ads are blocked the ad placeholder is not removed on the new responsive design.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/22572406/104793928-88d64780-57df-11eb-99b9-9bc90acd1beb.png)

### Versions

- Browser/version: Firefox 84.0.2
- uBlock Origin version: 1.32.4

### Settings

[my-ublock-backup_2021-01-16_09.45.57.txt](https://github.com/uBlockOrigin/uAssets/files/5823653/my-ublock-backup_2021-01-16_09.45.57.txt)

### Notes

Element picker removes it with this:
`##.newNorthWidget > .AdContainer-728x90.AdContainer.embedded_ad_wrapper`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/README.md

"If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

- anti-adblock
- ad-reinsertion
- popups/popunders
- site breakage
- video ads
will always be fixed in uAssets even if they don't require extended syntax."
