### ISSUE TITLE
myabandonware.com

### ISSUE THREAD

**Issue by AroKol78** [uBlockOrigin/uAssets#8505]
ubo legacy [myList](https://user-images.githubusercontent.com/70756447/102889523-1a5dce00-445b-11eb-9dfa-8919f5ae110c.PNG) +"Polskie Filtry Elementów Irytujących - Scrollujące Filmiki"

`https://www.myabandonware.com/`
in the middle of the page [myabandonware1.png](https://user-images.githubusercontent.com/70756447/105640862-c478ad80-5e80-11eb-8c5a-09727dbd4069.PNG)

`https://www.myabandonware.com/game/smash-t-v-5x3`
in the middle of the page (after game screenshots) [myabandonware2.png](https://user-images.githubusercontent.com/70756447/105640879-f5f17900-5e80-11eb-8ed5-ed102612939e.PNG)

---
maybe this (i don't have great skills)
```
myabandonware.com##[class^="item itemListGame be"]
myabandonware.com##[class="avp wgm"]
||myabandonware.com/media/img/wgm/
||myabandonware.com/media/img/gog/
```

**Comment by okiehsch** [comment]
Report to `EasyList`.  https://github.com/easylist/easylist


We do not fix such issues.
https://github.com/uBlockOrigin/uAssets/blob/master/README.md
"If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

- anti-adblock
- ad-reinsertion
- popups/popunders
- site breakage
- video ads

will always be fixed in uAssets even if they don't require extended syntax."
