### ISSUE TITLE
unblocked.name / unblockit.ltd

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8544]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
A]
`http://yts.unblocked.name`
`http://ibit.unblocked.name/torrent/Joker-2019--U175Gt4/`
& many sites listed under `unblocked.name`

B]
```
unblockit.ltd
https://yts.unblockit.ltd
https://eztv.unblockit.ltd
```
& many sites listed under `unblockit.ltd`

### Describe the issue

popup ads & propeller stuff
nordvpn promotions

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.33

### Settings

 uBO's default settings
-

**Comment by uBlock-user** [comment]
```
unblocked.name##+js(nowoif)
unblocked.name##+js(aeld, , 0x)
unblocked.name##+js(nostif, 0x)
unblocked.name##+js(nosiif, 0x)
unblocked.name##.cborz-bordered
||jstatic.org^
||zunsoach.com^
```

any breakage from these ?

**Comment by ghajini** [comment]
I will test today, there are so many sites

**Comment by ghajini** [comment]
1.
`https://yts.unblocked.name/movies/malcolm-marie-2021`
magnet links blocked
propeller crap still loads

2. eg
`http://thepiratebay.unblocked.name/`

clicking on these sections `| Browse Torrents | Recent Torrents | TV shows | Music | Top 100` don't load
similar with other listed sites ,their subsections don't load

3.
propeller crap still loads
(scriptlets not worked)
```
||unblocked.name/zpp/*$script,domain=unblocked.name
/hy.js$script,domain=unblocked.name
```
also add
`unblocked.name##+js(acis, adcashMacros)`

**Comment by ghajini** [comment]
This much is sufficient

```
unblocked.name,unblockit.ltd##[style*="decoration"]:not([style^="width"])
||unblocked.name/zpp/*$script,domain=unblocked.name
/hy.js$script,domain=unblocked.name
unblocked.name##+js(aopr, GetWindowHeight)
unblocked.name##+js(aopr, decodeURIComponent)
||ctrlaltdel99.com^
unblocked.name,unblockit.ltd##+js(acis, adcashMacros)
```

**Comment by felix-22** [comment]
Moving here as this seems to be a proper place, and to avoid off-topic in the another thread:

> uBlock-user : https://github.com/uBlockOrigin/uAssets/issues/10162#issuecomment-938610797 : 
> > `||unblocksite.pw^$doc`
>
> Why that website ?

<br>
<br>

Because it was about the subdomain, I visited the subdomain: `gfxtra.unblocksite.pw` and after clicking various things on the site, it redirects to some suspicious/badware sites:

Example 1:

<details>
  <summary>(screenshoot 1) clicking the red X button on right-top to close the message</summary>
  
  
![222](https://user-images.githubusercontent.com/75935068/136565477-5ecdca4e-cd6c-45d5-b989-f4a84cf096c1.png)

</details>

<details>
  <summary>(screenshoot 2) redirects to some unwanted sites which are blocked in EasyList</summary>
  
![333](https://user-images.githubusercontent.com/75935068/136565490-673dfd59-2815-4145-a0ec-7ecc9a1a527c.png)
  
</details>

Example 2:

<details>
  <summary>(screenshoot 3) clicking Ice Road banner on the right</summary>
  
![555](https://user-images.githubusercontent.com/75935068/136566149-70668efa-1011-4845-8ed2-f808eb4ad3aa.png)

</details>

<details>
  <summary>(screenshoot 4) opens some suspicious popups and redirects to some suspicious sites/redirectors</summary>
  
![777](https://user-images.githubusercontent.com/75935068/136566180-236490b5-e67f-46fe-aa21-294a9b7c0b8f.png)

</details>

- more subdomains: `https://www.google.com/search?q=site%3A*.unblocksite.pw` I'm not sure, but many of them seems like a farm, I've visited some of them, and all looks similiar.
- ok, I don't know what this all crap is, some badware fake VPN farm or a legitimate VPN service? 
- I've found almost  ~300 `.pw` subdomains of VPN farm, also I've found different main domains of the same farm (which gives total count 6 x 300 = 1800):
  - `ihavenotv.unblockedsite.net` ==> `https://www.google.com/search?q=site%3A*.unblockedsite.net`
  - `snahp.unblocked2.xyz` ==> `https://www.google.com/search?q=site%3A*.unblocked2.xyz`
  - `demonoid.siteunblocked.cc` ==>  `https://www.google.com/search?q=site%3A*.siteunblocked.cc`
  - unblocked.name ==> https://github.com/uBlockOrigin/uAssets/issues/8544#issue-803325224
  - unblockit.ltd ==> https://github.com/uBlockOrigin/uAssets/issues/8544#issue-803325224
- this one seems a legitimate site: `watchasian.unblocksite.pw`
