### ISSUE TITLE
https://winiso.pl/ has ads

### ISSUE THREAD

**Issue by ticotaco72** [uBlockOrigin/uAssets#8558]
### Prerequisites

- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://winiso.pl/

### Describe the issue

 
Baner on the top isn't blocked
### Versions

- Browser/version: Firefox 85.0 64 bit Linux
- uBlock Origin version: 1.33.2

### Settings

-

**Comment by uBlock-user** [comment]
read here: https://github.com/uBlockOrigin/uAssets/blob/master/README.md

If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

anti-adblock
ad-reinsertion
popups/popunders
site breakage
video ads
will always be fixed in uAssets even if they don't require extended syntax.

This means you should report such issues at easylist repository:
https://github.com/easylist/easylist/issues
