### ISSUE TITLE
adrenaline.com.br

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#8596]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

``https://adrenaline.com.br/artigos/v/67784/the-medium-na-rtx-3080-rx-6800-xt-e-no-series-x-ray-tracing-dlss-e-fidelity-fx``

### Describe the issue

There is a PT-BR message that says "``- Continua após a publicidade -``", and in English that means "Continues after advertising", that is, there is an ad after this message. But since the ad is blocked by uBlock Origin, I think the warning about the ad should be removed too.

 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/30274161/108432358-00562700-7223-11eb-8393-274d81132746.png)

### Versions

- Browser/version: Google Chrome Version 88.0.4324.182 (Official version) 64 bits
- uBlock Origin version: 1.33.2

### Settings

I use the default settings.

### Notes

No additional notes.

**Comment by okiehsch** [comment]
Add
`adrenaline.com.br##center.mb-4.mt-2 > small`
ro your filter list.
We only fix sites that need atleast one extended syntax filter.

See our readme  https://github.com/uBlockOrigin/uAssets/blob/master/README.md

"If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

- anti-adblock
- ad-reinsertion
- popups/popunders
- site breakage
- video ads
will always be fixed in uAssets even if they don't require extended syntax."

**Comment by adranger** [comment]
@Tiagoquix Ative a lista `spa, por: AdGuard Spanish/Portuguese`. Informei o problema no repositório adequado: https://github.com/AdguardTeam/AdguardFilters/issues/75515
