### ISSUE TITLE
srek.net links for exe.io are broken

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#8745]
I found out after investigating https://github.com/AdguardTeam/AdguardFilters/issues/78006

**Comment by garry-ut99** [comment]
Another breakage: thumbnails broken + chat widget broken: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218766079-1b8126d7-ba93-4dcb-a748-795cb0979481.png)
Fixed: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218767641-49e0b554-24c8-4796-b9b4-dd19e9924deb.png) (fixed chat widget: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218769276-6994da18-414b-4557-8276-15d9fde07a78.gif) )


Breakage caused by: 
- `*$script,3p,denyallow=cloudflare.com|google.com|gstatic.com|recaptcha.net,domain=cuts-url.com|eio.io|exe.app|exee.io|srek.net`

Example solution:
- to fix broken thumbnails: appending domains `|mybuckyshop.com|cloudfront.net` to `denyallow=` works
- to fix broken chat widget: `|echatsoft.com|echatsoft.com.w.cdngslb.com` to `denyallow=` works
- complete solution: 
   - `|mybuckyshop.com|cloudfront.net|echatsoft.com|echatsoft.com.w.cdngslb.com` to `denyallow=`
   - or to remove `srek.net` from `domain=` if not needed anymore

**Comment by ghajini** [comment]
> > `srek.net`
> 
> Another breakage: thumbnails broken + chat widget broken: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218766079-1b8126d7-ba93-4dcb-a748-795cb0979481.png) Fixed: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218767641-49e0b554-24c8-4796-b9b4-dd19e9924deb.png) (fixed chat widget: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218769276-6994da18-414b-4557-8276-15d9fde07a78.gif) )
> 
> Breakage caused by:
> 
>     * `*$script,3p,denyallow=cloudflare.com|google.com|gstatic.com|recaptcha.net,domain=cuts-url.com|eio.io|exe.app|exee.io|srek.net`
> 
> 
> Example solution:
> 
>     * to fix broken thumbnails: appending domains `|mybuckyshop.com|cloudfront.net` to `denyallow=` works
> 
>     * to fix broken chat widget: `|echatsoft.com|echatsoft.com.w.cdngslb.com` to `denyallow=` works
> 
>     * complete solution:
>       
>       * `|mybuckyshop.com|cloudfront.net|echatsoft.com|echatsoft.com.w.cdngslb.com` to `denyallow=`
>       * or to remove `srek.net` from `domain=` if not needed anymore
> 
> 
> Not sure whether section Recommended = Sponsored and should be hidden.

can you provide more details  such as a link?

**Comment by garry-ut99** [comment]
It's already provided at the beginning/top of my comment.

**Comment by ghajini** [comment]
ok these seems to be some shortener links, require those other links

**Comment by garry-ut99** [comment]
No other links, it's about a single website at the beginning of my comment:

> garry-ut99 : https://github.com/uBlockOrigin/uAssets/issues/8745#issuecomment-1429857633 : `srek.net`

**Comment by ghajini** [comment]
i know ,i know ,iam talking about  other part `domain=cuts-url.com|eio.io|exe.app|exee.io|srek.net`

**Comment by garry-ut99** [comment]
Ok, I wasn't using any other links users usually use on shortener sites, I just visited directly `srek.net` and noticed it was broken.
