### ISSUE TITLE
playview.io anti-adblock

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#893]
URL(s) where the issue occurs

https://playview.io/

Describe the issue

anti-adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
anti-adblock ?

`https://playview.io/`

**Comment by mapx-** [comment]
No anti adb for me, details ? screenshot ?

**Comment by okiehsch** [comment]
Try with Chrome, I get some weird result.

**Comment by mapx-** [comment]
still nothing obvious ... only a red button (`ver en`) pointing to `adsrv.me`

**Comment by okiehsch** [comment]
OK, I found the issue the site is broken on my end because of Chromes integrated Adblocker.
![image](https://user-images.githubusercontent.com/16838044/51712737-a70d7080-2027-11e9-9e18-540eea6b769a.png)

@KiLL4FuNK if you have the same issue you will have to check the "Always allow ads on this site" box for the page to work properly.

**Comment by mapx-** [comment]
oh, I have it disabled
