### ISSUE TITLE
rethmic.com [Anti-Adblock]

### ISSUE THREAD

**Issue by Robbie8592** [uBlockOrigin/uAssets#8945]
### URL(s) where the issue occurs

`https://rethmic.com/course/php-web-development-with-mysql-0503-direct-free-download`

### Describe the issue

Getting a banner to disable my adblocker after the 20 second countdown

### Screenshot(s)

![image](https://user-images.githubusercontent.com/29841633/115641694-9b34b580-a2e7-11eb-9896-8c7437c55e3e.png)

### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: 1.34.0

### Settings

Default Settings
-

### Notes

None

**Comment by Robbie8592** [comment]
On fix 1e4c919 the banner went away but after the newest 1b524b7 fix the banner is back

**Comment by bogachenko** [comment]
> 
> 
> On fix 1e4c919 the banner went away but after the newest 1b524b7 fix the banner is back

The rule `rethmic.com##+js(set-constant.js, chk_adblocker, noopFunc)` in the commit https://github.com/bogachenko/fuckfuckadblock/commit/1e4c9196f197f049dbcd85f859b2d19b357ec86f was breaking the 20 second countdown, so that's why it was deleted.
My anti-adblock trigger is related to the blocking of the domain `cpabuild.com`, so if you unblock this domain there will be no anti-adblock and nothing breaks the 20 second countdown.

Whatever it was, I'm a third-party dick who is not in any way connected with this repository, wait for the moderators of this repository.

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by krystian3w** [comment]
Try with disabled Nano Defender.

**Comment by Omega-6** [comment]
https://urlfilter.adtidy.org/v2/checkDomain?domain=seositespeed.com
