### ISSUE TITLE
capital.fr ad leftovers

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9524]
https://github.com/uBlockOrigin/uAssets/issues/5341 follow-up

I even added AdGuard's french list.

Encountered in Opera with its built-in VPN enabled.

**Comment by garry-ut99** [comment]
Ad placeholders all over the site, caused by `ghide` in "uBlock filters":
[SCREENSHOOT 1](https://user-images.githubusercontent.com/72945564/214820013-3ffb0fdd-16a6-47ec-a0a3-fa7efb488890.png), [SCREENSHOOT 2](https://user-images.githubusercontent.com/72945564/214820215-1b8e80f7-a88a-41c3-82b6-dab8abd747b9.png), [SCREENSHOOT 3](https://user-images.githubusercontent.com/72945564/214820220-09750d30-664f-41ff-9d75-ab2e31bcf6c4.png)
