### ISSUE TITLE
frkn64modding.com

### ISSUE THREAD

**Issue by thinksheiscool** [uBlockOrigin/uAssets#9814]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://frkn64modding.com/category/all-mods/ets2/`

### Describe the issue

anti adblocking mechanism

### uBlock Origin version

1.37.2

### Browser name and version

Google Chrome 92.0.4515.159 (Official Build) (64-bit)

### Settings

![image](https://user-images.githubusercontent.com/89113298/130326173-dac26291-0871-417c-8a36-bd97dff985a0.png)

### Notes

https://github.com/AdguardTeam/AdguardFilters/issues/91884

**Comment by garry-ut99** [comment]
Ad placeholders all over the site caused by `ghide` from "uBlock filters".

<details>
<summary>SCREENSHOOTS</summary>

![ww (3)](https://user-images.githubusercontent.com/72945564/215356958-c670e4dd-da44-473f-bae8-4c1954e7a88c.png)
![ww (4)](https://user-images.githubusercontent.com/72945564/215356959-5f5c2dd9-435e-4bb6-a020-a5cb65b64161.png)
![ww (1)](https://user-images.githubusercontent.com/72945564/215356955-3d84988f-fe0b-4dc5-b636-3d512daa9bc8.png)
![ww (2)](https://user-images.githubusercontent.com/72945564/215356957-3169ad00-d2a8-4362-85d8-7e6b4b37fa88.png)

</details>
